export const APPLICATION_HEADER_HEIGHT =
  44;

export const APPLICATION_ACTIVITY_RAIL_WIDTH =
  44;

export const APPLICATION_ACTIVITY_PANEL_WIDTH =
  296;

export const APPLICATION_ACTIVITY_BUTTON_SIZE =
  32;

export const APPLICATION_ACTIVITY_BUTTON_INSET =
  6;