import { createA8QuestionCatalogEntry } from "../../A8SimultaneousEquationsCatalogFactory";

export const N5_MATHS_2025_P2_Q10 = createA8QuestionCatalogEntry({
  year: 2025,
  paper: "P2",
  questionNumber: "10",
  pdfPage: 25,
  printedPageLabel: "page 12",
  mode: "CONTEXT_DERIVED_TOTAL",
  equations: [{ a: 7, b: 3, c: 2400 }, { a: 3, b: 4, c: 1300 }],
  variableSymbols: ["p", "e"],
  solution: [300, 100],
  numberTypes: ["INTEGER", "ALGEBRAIC"],
  responseRegions: [
    { id: "Q10_SPACE_A", partIds: ["Q10_a"], topPt: 169.0, bottomPt: 238.6, boundaryConvention: "Bottom of part (a) instruction to the next contextual statement." },
    { id: "Q10_SPACE_B", partIds: ["Q10_b"], topPt: 300.6, bottomPt: 370.1, boundaryConvention: "Bottom of part (b) instruction to the third contextual statement." },
    { id: "Q10_SPACE_C", partIds: ["Q10_c"], topPt: 424.2, bottomPt: 774.8, boundaryConvention: "Bottom of part (c) instruction to the top of the footer/barcode block." },
  ],
  answerSpaceCategory: "FULL_PAGE",
  estimatedWritingLines: 15,
  promptWordCount: 104,
  promptSentenceCount: 9,
  algebraicallyExplicit: false,
  context: {
    domain: "lorry load mass",
    objectLabels: ["paving-slab stack", "edging-block stack"],
    relationshipLabels: ["first lorry load", "second lorry load"],
    unitDimension: "mass",
    unitSymbol: "kg",
    currency: false,
    namedPeople: true,
    realWorldUnits: true,
    firstRelationshipSummary: "Seven stacks of the first type and three of the second have a total mass of 2400 kilograms.",
    secondRelationshipSummary: "Three stacks of the first type and four of the second have a total mass of 1300 kilograms.",
    targetSummary: "Use the solved stack masses to find the total for six first-type stacks and five second-type stacks.",
    explicitVariableDefinitions: true,
    derivedCoefficients: [6, 5],
    derivedValue: 2300,
  },
});
