import {
  G1_CROSS_CORPUS_GENERATION_INVARIANTS,
  G1_GENERATOR_SCOPE,
} from "../../../03_SkillCatalog/03-Geometric/GEO-G1-GradientTwoPoints/G1CrossCorpusAnalysis";
import {
  G1_BEST_FIT_GENERATION_ENVELOPE,
  G1_CALIBRATION_DECISIONS,
  G1_CONTEXTUAL_MODEL_GENERATION_ENVELOPE,
  G1_LINE_EQUATION_GENERATION_ENVELOPE,
  G1_SYMBOLIC_GENERATION_ENVELOPE,
} from "../../../03_SkillCatalog/03-Geometric/GEO-G1-GradientTwoPoints/G1CrossCorpusCalibration";
import {
  G1_DIFFICULTY_GENERATION_GUARDRAILS,
  G1_DIFFICULTY_SCORING_RULES,
} from "../../../03_SkillCatalog/03-Geometric/GEO-G1-GradientTwoPoints/G1DifficultyCalibration";
import {
  G1_BEST_FIT_GRAPH_GENERATION_GUARDRAILS,
  G1_CONTEXT_GRAPH_GENERATION_GUARDRAILS,
  G1_COORDINATE_DIAGRAM_GENERATION_GUARDRAILS,
  G1_SYMBOLIC_SURFACE_GENERATION_GUARDRAILS,
} from "../../../03_SkillCatalog/03-Geometric/GEO-G1-GradientTwoPoints/G1SurfaceCalibration";

export const G1_GENERATOR_FAMILY_EVIDENCE = Object.fromEntries(
  G1_GENERATOR_SCOPE.map((profile) => [profile.family, profile]),
) as {
  [K in (typeof G1_GENERATOR_SCOPE)[number]["family"]]: Extract<
    (typeof G1_GENERATOR_SCOPE)[number],
    { family: K }
  >;
};

export const G1_GENERATOR_INVARIANTS = G1_CROSS_CORPUS_GENERATION_INVARIANTS;
export const G1_GENERATOR_CALIBRATION_DECISIONS = G1_CALIBRATION_DECISIONS;
export const G1_GENERATOR_DIFFICULTY_RULES = [
  ...G1_DIFFICULTY_SCORING_RULES,
  ...G1_DIFFICULTY_GENERATION_GUARDRAILS,
] as const;

export const G1_GENERATOR_LINE_GUARDRAILS = G1_LINE_EQUATION_GENERATION_ENVELOPE.generatorGuardrails;
export const G1_GENERATOR_CONTEXT_GUARDRAILS = [
  ...G1_CONTEXTUAL_MODEL_GENERATION_ENVELOPE.generatorGuardrails,
  ...G1_CONTEXT_GRAPH_GENERATION_GUARDRAILS,
] as const;
export const G1_GENERATOR_BEST_FIT_GUARDRAILS = [
  ...G1_BEST_FIT_GENERATION_ENVELOPE.generatorGuardrails,
  ...G1_BEST_FIT_GRAPH_GENERATION_GUARDRAILS,
] as const;
export const G1_GENERATOR_SYMBOLIC_GUARDRAILS = [
  ...G1_SYMBOLIC_GENERATION_ENVELOPE.generatorGuardrails,
  ...G1_SYMBOLIC_SURFACE_GENERATION_GUARDRAILS,
] as const;
export const G1_GENERATOR_COORDINATE_VISUAL_GUARDRAILS = G1_COORDINATE_DIAGRAM_GENERATION_GUARDRAILS;
