import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("1", 17, "QUESTION", "P2", 3, 2024);

export const N5_MATHS_2024_P2_Q1 = {
  identity: {
    id: "N5_MATH_2024_P2_Q1",
    schemaVersion: "N5_CATALOG_V2",
    courseId: "N5_MATH",
    paperContextId: "N5_MATH_2024_P2_CONTEXT",
    year: 2024,
    paper: "P2",
    questionNumber: "1",
    answerCatalogId: "N5_MATH_2024_P2_Q1_MS",
  },
  sourceLayout: {
    sourcePages: [17],
    printedPageLabels: ["Page 3"],
    continuesAcrossPages: false,
    answerSpace: {
      category: "LARGE",
      estimatedWritingLines: 7,
      responseSurfaceVisualIds: [],
      separateFinalAnswerAreaPresent: false,
      measurementMethod: "MANUAL_ESTIMATE",
      sourceMeasurements: [],
      notes: "A substantial blank working region separates Q1 from Q2 on the shared source page.",
    },
    sourceEvidence: [evidence],
  },
  structure: {
    structureType: "SINGLE",
    totalMarks: 3,
    parts: [{
      id: "Q1_MAIN",
      label: "",
      marks: 3,
      primarySkillId: "num-n4-appreciation-depreciation",
      secondarySkillIds: [],
      conceptIds: ["num-n4-2-depreciation"],
      topic: "NUM",
      commandTypes: ["CALCULATE"],
      responseTypes: ["NUMBER"],
      dependsOnPartIds: [],
      sharedInformationIds: [],
      visualElementIds: [],
      standardProfile: "C",
      thinkingProfile: "OPERATIONAL",
      calculatorBurden: "CALCULATOR_NATURAL",
    }],
    dependencyType: "INDEPENDENT",
    sharedStimulus: false,
    sharedVisuals: false,
    sharedGivenData: false,
    requiredResultProvided: false,
  },
  curriculum: {
    primaryTopic: "NUM",
    primarySkillId: "num-n4-appreciation-depreciation",
    secondarySkillIds: [],
    primaryConceptId: "num-n4-2-depreciation",
    conceptIds: ["num-n4-2-depreciation"],
    paperSuitability: "P2",
    standardProfile: "C",
    thinkingProfile: "OPERATIONAL",
    crossSkillQuestion: false,
    skillMarkDistribution: { "num-n4-appreciation-depreciation": 3 },
    conceptMarkDistribution: { "num-n4-2-depreciation": 3 },
  },
  task: {
    commandTypes: ["CALCULATE"],
    responseTypes: ["NUMBER"],
    responseCount: 1,
    explicitMethodCue: false,
    methodRestricted: false,
    workingRequestedInPrompt: false,
    justificationRequested: false,
    contextualConclusionRequested: false,
    visualResponseRequired: false,
  },
  mathematics: {
    primaryGoal: "Apply a fixed annual percentage depreciation for three periods to a monetary starting value.",
    subgoals: [
      { id: "Q1_S1", summary: "Convert the annual depreciation rate into a retention multiplier.", dependsOnSubgoalIds: [] },
      { id: "Q1_S2", summary: "Apply the multiplier over three annual periods and evaluate the resulting value.", dependsOnSubgoalIds: ["Q1_S1"] },
    ],
    operationTypes: ["MULTIPLY", "EVALUATE"],
    requiredFormulaIds: [],
    requiredTheoremIds: [],
    stageCount: 2,
    intermediateQuantityTypes: ["annual retention multiplier", "three-year depreciated value"],
    methodSelectionRequired: false,
    solutionCountExpected: 1,
    validitySelectionRequired: false,
    representationTransitions: [],
  },
  information: [
    { id: "Q1_INFO_START", informationType: "starting value", normalisedContent: "initial laptop value is 460 pounds", value: 460, unit: "GBP", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: null, usedByPartIds: ["Q1_MAIN"] },
    { id: "Q1_INFO_RATE", informationType: "percentage decrease", normalisedContent: "value depreciates by 26 percent per year", value: 26, unit: "percent", source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: null, usedByPartIds: ["Q1_MAIN"] },
    { id: "Q1_INFO_YEARS", informationType: "period count", normalisedContent: "depreciation is applied for three years", value: 3, unit: "years", source: "TEXT", explicitness: "EXPLICIT", role: "CONSTRAINT", visualElementId: null, usedByPartIds: ["Q1_MAIN"] },
  ],
  reasoning: {
    reasoningTypes: ["DIRECT_PROCEDURE", "MULTI_STAGE", "CONTEXT_INTERPRETATION"],
    difficulty: {
      overallDifficulty: "LOW",
      methodSelectionLoad: "VERY_LOW",
      arithmeticLoad: "MEDIUM",
      algebraicLoad: "VERY_LOW",
      representationLoad: "VERY_LOW",
      languageLoad: "LOW",
      contextInterpretationLoad: "LOW",
      reasoningDepth: "LOW",
      dependencyCount: 0,
      difficultyDrivers: ["compound rather than fixed-amount depreciation", "three repeated annual periods"],
    },
  },
  numbers: {
    numberTypes: ["INTEGER", "PERCENTAGE", "DECIMAL", "POWER"],
    nonCalculatorFriendly: false,
    exactAndApproximateMixed: false,
    simplificationVisibility: "NOT_APPLICABLE",
    expectedFinalValueForm: "DECIMAL",
    intermediateValueSize: "MEDIUM",
    finalValueSize: "MEDIUM",
    dominantInputFormat: "CURRENCY",
    dominantOutputFormat: "CURRENCY",
    magnitudeNotes: null,
  },
  calculator: {
    status: "CALCULATOR_ALLOWED",
    burden: "CALCULATOR_NATURAL",
    requiredFunctions: ["powers"],
    modeSensitive: false,
    modeRequirements: [],
    notes: "Repeated multiplication by a decimal retention factor is naturally evaluated with a calculator.",
  },
  parameterDesign: {
    deliberatelyConstructedValues: true,
    exactResultDesigned: false,
    roundingDesigned: false,
    factorisableDesigned: false,
    perfectSquareDesigned: false,
    pythagoreanTripleUsed: false,
    niceRatioUsed: false,
    validSolutionCountDesigned: null,
    parameterConstraints: ["annual depreciation rate lies strictly between 0 and 100 percent", "period count is a small positive integer", "resulting monetary value remains positive"],
    safeVariationAxes: ["starting monetary value", "depreciation rate", "period count", "replaceable asset context"],
    invariantRelationships: ["the same percentage decrease is applied to the updated value each year"],
    degeneracyConditionsToAvoid: ["zero or 100 percent rate", "values that make fixed-amount subtraction indistinguishable from compound change"],
  },
  constraints: {
    mathematicalDomainConstraints: [],
    contextValidityConstraints: ["The depreciated value must remain non-negative."],
    calculatorModeConstraints: ["Calculator use is permitted on Paper 2."],
    methodConstraints: [],
    presentationConstraints: [],
  },
  answerSpecification: {
    answerForm: "APPROXIMATE",
    simplestFormRequired: false,
    rationalDenominatorRequired: false,
    positivePowersRequired: false,
    scientificNotationRequired: false,
    precisionType: "NONE",
    precisionValue: null,
    units: { dimension: "currency", unitSymbol: "GBP", conversionRequired: false, unitsExplicitlyRequested: false },
    multipleAnswersRequired: 1,
    domainRestriction: null,
    contextualWordsRequired: false,
    coordinateOrderRelevant: false,
    bracketsRelevant: false,
    visualAnswerRequired: false,
  },
  context: {
    contextualised: true,
    contextDomain: "asset depreciation",
    contextRole: "MATHEMATICALLY_RELEVANT",
    namedPeoplePresent: true,
    currencyPresent: true,
    realWorldUnitsPresent: true,
    realismConstrainsAnswer: false,
    contextObjects: ["laptop", "monetary value"],
    contextCanBeSafelyReplaced: true,
  },
  language: {
    informationDensity: "LOW",
    scaffoldingLevel: "LOW",
    bulletStructureUsed: false,
    naturalLanguageInterpretationRequired: true,
    promptSummary: "A purchased asset loses a fixed percentage of its value each year; calculate its expected value after three years.",
    styleNotes: null,
    promptStructure: {
      sentenceCount: 3,
      promptWordCount: 32,
      introductionStyle: "NAMED_PERSON_PURCHASE_AND_STARTING_PRICE",
      relationshipStatementStyle: "SEPARATE_SENTENCE_STATING_ANNUAL_PERCENTAGE_DEPRECIATION",
      commandStyle: "DIRECT_FUTURE_VALUE_CALCULATION",
      temporalStructure: "YEAR_ON_YEAR",
      informationOrder: ["ASSET_AND_STARTING_VALUE", "ANNUAL_DEPRECIATION_RATE", "PERIOD_COUNT", "FUTURE_VALUE_TARGET"],
      normalisedPromptStructure: ["Introduce an asset and its current monetary value.", "State a repeated annual percentage decrease.", "Ask for the value after a specified number of years."],
      usesPronounReference: true,
      lexicalFeatureTags: ["named-person context", "asset depreciation", "annual change"],
      generatorVariationNotes: "Vary the asset, starting value, annual depreciation rate and period count while preserving compound change.",
    },
  },
  visuals: notApplicable("No supplied visual material is used in this Question."),
  mathematicalModel: notApplicable(),
  specialisedProfiles: {
    arithmetic: notApplicable(),
    percentage: catalogValue({
      relationshipType: "COMPOUND",
      percentageValues: [26],
      multiplierValues: [0.74],
      periods: 3,
      originalValueKnown: true,
      finalValueKnown: false,
      reverseCalculationRequired: false,
      expressionStyles: ["ANNUAL_CHANGE"],
      knownValueRoles: ["INITIAL_VALUE"],
      requestedValueRole: "FINAL_VALUE",
      workingStepCount: 1,
      inverseCalculationProducesExactResult: false,
      compoundRateStructure: "FIXED_RATE",
      compoundStages: [{ percentageValue: 26, multiplier: 0.74, periods: 3 }],
      totalPeriods: 3,
    }, [evidence], "CATALOGUE_CLASSIFICATION", "HIGH", null),
    powersSurdsScientific: notApplicable(),
    algebra: notApplicable(),
    equationsInequalities: notApplicable(),
    functionsGraphs: notApplicable(),
    statistics: notApplicable(),
    geometryMeasureCircleSimilarity: notApplicable(),
    trigonometry: notApplicable(),
    bearings: notApplicable(),
    coordinateGeometry: notApplicable(),
    vectors: notApplicable(),
  },
  family: {
    familyId: "NUM_COMPOUND_PERCENTAGE_DEPRECIATION",
    subFamilyId: null,
    familyConfidence: "HIGH",
    structuralSignature: ["starting monetary value", "fixed annual percentage decrease", "multiple periods", "future value"],
    surfaceStyleIds: ["CONTEXTUAL_COMPOUND_PERCENTAGE", "ASSET_DEPRECIATION"],
    relatedFamilyIds: ["NUM_COMPOUND_PERCENTAGE_DECREASE_WITH_ROUNDING"],
  },
  surface: {
    abstractOrContextual: "CONTEXTUAL",
    proseAmount: "MEDIUM",
    visualAmount: "NONE",
    layoutComplexity: "LOW",
    informationOrderCanVarySafely: true,
    visualPlacementCanVarySafely: true,
  },
  generation: {
    readiness: "PARTIAL",
    linkedGeneratorFamilyIds: ["NUM_COMPOUND_PERCENTAGE_DEPRECIATION"],
    invariantMathematics: ["compound percentage decrease over several periods"],
    variableParameters: ["starting value", "percentage rate", "period count", "asset context"],
    parameterConstraints: ["rate and periods produce a sensible positive result"],
    safeContextVariations: ["electronics depreciation", "vehicle depreciation", "equipment depreciation", "other asset-value decline"],
    safeRepresentationVariations: [],
    unsafeVariations: ["replace compound depreciation with a fixed annual cash decrease"],
    difficultyControls: ["number of periods", "percentage complexity", "starting-value complexity"],
    requiredVisualCapabilities: [],
    requiredValidationChecks: ["mark total and part structure remain valid", "generated values satisfy parameter constraints", "compound multiplier is applied for the stated number of periods"],
    provenance: "GENERATION_ANALYSIS",
  },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(false, "P2", 2024, true),
} satisfies QuestionCatalogEntry;
