import type { GeneralMarkingPolicyCatalogEntry } from "../AnswerCatalogTypes";
import { answerIntegrity, generalPolicyEvidence } from "../AnswerCatalogHelpers";

const policyEvidence = [generalPolicyEvidence("P1", 2024), generalPolicyEvidence("P2", 2024)];

export const GENERAL_2024_RULE_IDS = [
  "N5_MATH_2024_RULE_ILLUSTRATIVE_AND_GENERIC_SCHEMES",
  "N5_MATH_2024_RULE_POSITIVE_MARKING",
  "N5_MATH_2024_RULE_SEEK_GUIDANCE_IF_UNCOVERED",
  "N5_MATH_2024_RULE_ONE_MARK_PER_MARK_POINT",
  "N5_MATH_2024_RULE_FOLLOW_THROUGH_COMPARABLE_DIFFICULTY",
  "N5_MATH_2024_RULE_WORKING_REQUIRED_UNLESS_SPECIFIED",
  "N5_MATH_2024_RULE_ANY_VALID_METHOD",
  "N5_MATH_2024_RULE_TRIVIAL_ERROR_MARK_LOSS",
  "N5_MATH_2024_RULE_TRANSCRIPTION_NEXT_PROCESS",
  "N5_MATH_2024_RULE_HORIZONTAL_VERTICAL_MARKING",
  "N5_MATH_2024_RULE_FINAL_SIMPLIFICATION",
  "N5_MATH_2024_RULE_COR_GUIDANCE",
  "N5_MATH_2024_RULE_LATER_WORK_AFTER_CORRECT",
  "N5_MATH_2024_RULE_CORRECT_WORK_WRONG_PART",
  "N5_MATH_2024_RULE_LEGITIMATE_VARIATION",
  "N5_MATH_2024_RULE_OMITTED_UNITS",
  "N5_MATH_2024_RULE_BAD_FORM",
  "N5_MATH_2024_RULE_REPEATED_ERROR_WITHIN_QUESTION",
  "N5_MATH_2024_RULE_SHOW_THAT_FINAL_MARK_FT",
  "N5_MATH_2024_RULE_CHECK_ALL_WORK",
  "N5_MATH_2024_RULE_SCORED_OUT_WORK",
  "N5_MATH_2024_RULE_MULTIPLE_ATTEMPTS_BY_STRATEGY",
] as const;

export const N5_MATHS_2024_GENERAL_MARKING_POLICY = {
  id: "N5_MATH_2024_GENERAL_MARKING_POLICY",
  schemaVersion: "N5_CATALOG_V2",
  courseId: "N5_MATH",
  year: 2024,
  affectedPapers: ["P1", "P2"],
  sourceDocumentId: "N5_MATH_2024_MS",
  rules: [
    { id: GENERAL_2024_RULE_IDS[0], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Use the illustrative scheme for commonly covered methods and the generic scheme when a mathematically valid response is not represented by the illustrations.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[1], scope: "ASSESSMENT", category: "POSITIVE_MARKING", normalisedRule: "Accumulate credit for demonstrated mathematics rather than deducting marks from a maximum for errors or omissions.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[2], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Where a response is not covered by the general or detailed instructions and its treatment is uncertain, obtain marking guidance rather than inventing a rule.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[3], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Each marked point is worth one mark and half marks are not used.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[4], scope: "ASSESSMENT", category: "FOLLOW_THROUGH", normalisedRule: "Continue to assess work after an error and award later credit only where the subsequent mathematical demand remains similar to that intended by the scheme.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[5], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Full credit normally requires appropriate working; a correct unsupported answer receives no mark unless the detailed instructions explicitly state otherwise.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[6], scope: "ASSESSMENT", category: "VALID_METHODS", normalisedRule: "Accept any mathematically correct method unless a particular method is required or excluded.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[7], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "A trivial or casual mathematical error can remove the opportunity for the associated mark, subject to the stated transcription exception.", penaltyLimit: "PER_OCCURRENCE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[8], scope: "ASSESSMENT", category: "TRANSCRIPTION", normalisedRule: "A transcription error normally removes the opportunity for the next process mark, except where the subsequent work clearly continues with the intended mathematical object as specified by policy.", penaltyLimit: "PER_OCCURRENCE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[9], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "When a question explicitly invokes horizontal/vertical marking for paired solutions, choose the complete horizontal or vertical allocation that benefits the candidate; do not combine the two allocations.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[10], scope: "ASSESSMENT", category: "PRESENTATION", normalisedRule: "Simplify numerical final answers as far as expected at this level unless the detailed instructions state a different requirement.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[11], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Source-listed commonly observed responses guide treatment of the listed and sufficiently similar non-routine responses.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[12], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Do not apply a generic penalty to work written after a correct answer unless detailed instructions say otherwise.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[13], scope: "ASSESSMENT", category: "OTHER", normalisedRule: "Do not apply a generic penalty to correct working placed in the wrong part of a question unless detailed instructions say otherwise.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[14], scope: "ASSESSMENT", category: "VALID_METHODS", normalisedRule: "Do not penalise legitimate numerical or algebraic variation unless a question-specific instruction makes the form mark-bearing.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[15], scope: "ASSESSMENT", category: "UNITS", normalisedRule: "Do not apply a generic penalty for omitted units unless the detailed instructions make units mark-bearing.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[16], scope: "ASSESSMENT", category: "PRESENTATION", normalisedRule: "Do not apply a generic penalty for bad form; it only affects credit where subsequent mathematics or detailed instructions make it consequential.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[17], scope: "QUESTION", category: "REPEATED_ERROR", normalisedRule: "Do not impose an additional generic penalty for repeating the same error within a question, but the protection does not carry between questions or papers.", penaltyLimit: "NONE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[18], scope: "ASSESSMENT", category: "FOLLOW_THROUGH", normalisedRule: "For a required-result or show-that task, the final mark is not normally available as follow-through from an earlier error unless the detailed instructions explicitly allow it.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[19], scope: "ASSESSMENT", category: "POSITIVE_MARKING", normalisedRule: "Inspect all working even after a fundamental misunderstanding because later independent credit may remain available; a correct-looking final answer does not by itself justify full credit.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[20], scope: "ASSESSMENT", category: "SCORED_OUT_WORK", normalisedRule: "Consider legible scored-out work when it has not been replaced; where a replacement is supplied, assess the replacement rather than the superseded work.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
    { id: GENERAL_2024_RULE_IDS[21], scope: "ASSESSMENT", category: "MULTIPLE_ATTEMPTS", normalisedRule: "Within one strategy, assess unidentified multiple attempts and use the lowest resulting mark; across different valid strategies, compare the strategy results and award the highest.", penaltyLimit: "NOT_APPLICABLE", sourceEvidence: policyEvidence },
  ],
  sourceEvidence: policyEvidence,
  integrity: answerIntegrity(),
  review: {
    status: "REVIEWED",
    sourceFactsComplete: true,
    classificationComplete: true,
    generationAnalysisComplete: false,
    counterpartCrossChecked: true,
    visualEvidenceCrossChecked: true,
    unresolvedIssues: [],
    validationNotes: [
      "The 2024 Paper 1 and Paper 2 general-marking-principle sections were cross-checked and contain the same policy substance.",
      "Rules are stored as source-linked normalisations rather than historical marking prose or generator templates.",
    ],
    reviewedAt: null,
  },
} satisfies GeneralMarkingPolicyCatalogEntry;
