import type { GeneralMarkingPolicyCatalogEntry } from "../AnswerCatalogTypes";
import { answerIntegrity, generalPolicyEvidence } from "../AnswerCatalogHelpers";

const evidence = generalPolicyEvidence();

export const N5_MATHS_2014_GENERAL_MARKING_POLICY = {
  id: "N5_MATH_2014_GENERAL_MARKING_POLICY",
  schemaVersion: "N5_CATALOG_V2",
  courseId: "N5_MATH",
  year: 2014,
  affectedPapers: ["P1", "P2"],
  sourceDocumentId: "N5_MATH_2014_MS",
  rules: [
    {
      id: "N5_MATH_2014_RULE_MARK_TO_INSTRUCTIONS",
      scope: "ASSESSMENT",
      category: "OTHER",
      normalisedRule: "Award marks using the general principles together with the detailed question-specific instructions.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_POSITIVE_MARKING",
      scope: "ASSESSMENT",
      category: "POSITIVE_MARKING",
      normalisedRule: "Accumulate credit for demonstrated mathematical knowledge, skills and understanding rather than deducting from a maximum for errors.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_SPECIFIC_GUIDELINES_CONTROL",
      scope: "ASSESSMENT",
      category: "OTHER",
      normalisedRule: "Question-specific assessment guidelines determine the credit available for the response.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_ANY_VALID_METHOD",
      scope: "ASSESSMENT",
      category: "VALID_METHODS",
      normalisedRule: "Accept any mathematically correct method unless the question explicitly requires or excludes a particular method.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_FOLLOW_THROUGH_COMPARABLE_DIFFICULTY",
      scope: "ASSESSMENT",
      category: "FOLLOW_THROUGH",
      normalisedRule: "After an error, continue to consider later credit when the subsequent mathematical demand remains approximately comparable; do not award the follow-through opportunity when the error materially simplifies the later work.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_TRANSCRIPTION_PROCESSING",
      scope: "ASSESSMENT",
      category: "TRANSCRIPTION",
      normalisedRule: "A transcription error normally removes the opportunity for the associated processing mark.",
      penaltyLimit: "PER_OCCURRENCE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_SCORED_OUT_WORK",
      scope: "ASSESSMENT",
      category: "SCORED_OUT_WORK",
      normalisedRule: "Legible scored-out work can be considered if it has not been replaced; where a replacement is supplied, mark the replacement rather than the superseded attempt.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_MULTIPLE_ATTEMPTS_LOWEST",
      scope: "ASSESSMENT",
      category: "MULTIPLE_ATTEMPTS",
      normalisedRule: "Where multiple attempts remain, assess all attempts and use the lowest resulting mark.",
      penaltyLimit: "NOT_APPLICABLE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_LATER_WORK_AFTER_CORRECT",
      scope: "ASSESSMENT",
      category: "OTHER",
      normalisedRule: "Do not penalise work written after a correct answer unless a question-specific instruction says otherwise.",
      penaltyLimit: "NONE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_CORRECT_WORK_WRONG_PART",
      scope: "ASSESSMENT",
      category: "OTHER",
      normalisedRule: "Do not penalise correct working placed in the wrong part unless a question-specific instruction says otherwise.",
      penaltyLimit: "NONE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_LEGITIMATE_VARIATION",
      scope: "ASSESSMENT",
      category: "VALID_METHODS",
      normalisedRule: "Do not penalise legitimate mathematical variation in a solution unless a question-specific instruction restricts it.",
      penaltyLimit: "NONE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_BAD_FORM",
      scope: "ASSESSMENT",
      category: "PRESENTATION",
      normalisedRule: "Do not apply a generic penalty solely for bad form unless the detailed question instructions make presentation mark-bearing.",
      penaltyLimit: "NONE",
      sourceEvidence: [evidence],
    },
    {
      id: "N5_MATH_2014_RULE_REPEATED_ERROR_WITHIN_QUESTION",
      scope: "QUESTION",
      category: "REPEATED_ERROR",
      normalisedRule: "Do not impose an additional generic penalty for repeating the same error within one question unless the detailed instructions say otherwise.",
      penaltyLimit: "NONE",
      sourceEvidence: [evidence],
    },
  ],
  sourceEvidence: [evidence],
  integrity: answerIntegrity(),
  review: {
    status: "REVIEWED",
    sourceFactsComplete: true,
    classificationComplete: true,
    generationAnalysisComplete: false,
    counterpartCrossChecked: true,
    visualEvidenceCrossChecked: true,
    unresolvedIssues: [],
    validationNotes: [
      "The Paper 1 and Paper 2 general-principles pages were cross-checked and carry the same 2014 rules.",
      "Rules are paraphrased and source-linked; no historical marking prose is used as a generator template.",
    ],
    reviewedAt: null,
  },
} satisfies GeneralMarkingPolicyCatalogEntry;
