import type { Skill } from "@/shared-types/AssessmentTypes";

export const NQ_N5_NUM_N02_IndicesAndScientificNotation: Skill[] = [
  {
    id: "num-n02-indices",
    code: "N2",
    domain: "NUM",
    text: "Simplify expressions using the laws of indices",
    paperSuitability: "BOTH",
    tags: ["numerical", "indices"],
    concepts: [
      {
        id: "num-n02-c01-product-and-quotient-indices",
        code: "N2.1",
        label: "N2.1 Product / quotient rules · a^m × a^n",
        shortLabel: "Product / quotient rules",
        badge: "a^m × a^n",
        fullDescription:
          "Indices - Multiplication and division using positive and negative indices including fractions",
        teacherNote:
          "Use multiplication and division laws of indices, including positive and negative powers.",
        standard: "C+A",
        marks: 2,
        promptStyleId: "B",
        metadata: {
          standardTier: "C+A",
          thinkingType: "operational",
          paperSuitability: "BOTH",
          calculator: "none",
          interactionType: "core",
          stepCount: "single",
          topicTags: ["indices", "multiplication", "division", "negative powers"],
          canBePrimary: true,
        },
      },
      {
        id: "num-n02-c02-power-of-a-product",
        code: "N2.2",
        label: "N2.2 Power of a product · (ab)^m",
        shortLabel: "Power of a product",
        badge: "(ab)^m",
        fullDescription: "Indices - (ab)^m = a^m b^m",
        teacherNote:
          "Distribute a power across a product correctly.",
        standard: "C+A",
        marks: 2,
        promptStyleId: "B",
        metadata: {
          standardTier: "C+A",
          thinkingType: "operational",
          paperSuitability: "BOTH",
          calculator: "none",
          interactionType: "core",
          stepCount: "single",
          topicTags: ["indices", "laws of indices", "products"],
          canBePrimary: true,
        },
      },
      {
        id: "num-n02-c03-power-of-a-power",
        code: "N2.3",
        label: "N2.3 Power of a power · (a^m)^n",
        shortLabel: "Power of a power",
        badge: "(a^m)^n",
        fullDescription:
          "Indices - (a^m)^n = a^mn and (a^m)^n forms",
        teacherNote:
          "Use the power-of-a-power law to simplify expressions.",
        standard: "C+A",
        marks: 2,
        promptStyleId: "B",
        metadata: {
          standardTier: "C+A",
          thinkingType: "operational",
          paperSuitability: "BOTH",
          calculator: "none",
          interactionType: "core",
          stepCount: "single",
          topicTags: ["indices", "power of a power"],
          canBePrimary: true,
        },
      },
      {
        id: "num-n02-c04-fractional-indices",
        code: "N2.4",
        label: "N2.4 Fractional indices · a^(m/n)",
        shortLabel: "Fractional indices",
        badge: "a^(m/n)",
        fullDescription: "Indices - a^(m/n) = nth root of a^m",
        teacherNote:
          "Convert between fractional index form and radical form correctly.",
        standard: "A",
        marks: 3,
        promptStyleId: "A",
        metadata: {
          standardTier: "A",
          thinkingType: "operational",
          paperSuitability: "BOTH",
          calculator: "none",
          interactionType: "core",
          stepCount: "multi",
          topicTags: ["indices", "fractional indices", "roots"],
          canBePrimary: true,
        },
      },
    ],
  },
  {
    id: "num-n02-scientific-notation",
    code: "N2",
    domain: "NUM",
    text: "Scientific Notation",
    paperSuitability: "BOTH",
    tags: ["numerical", "scientific notation", "standard form"],
    concepts: [
      {
        id: "num-n02-c05-scientific-notation-calculations",
        code: "N2.5",
        label: "N2.5 Scientific notation calculations · a×10^n",
        shortLabel: "Scientific notation calculations",
        badge: "a×10^n",
        fullDescription: "Calculations using scientific notation",
        teacherNote:
          "Perform calculations in scientific notation and present the final answer correctly.",
        standard: "C+A",
        marks: 3,
        promptStyleId: "B",
        metadata: {
          standardTier: "C+A",
          thinkingType: "operational",
          paperSuitability: "BOTH",
          calculator: "optional",
          interactionType: "either",
          stepCount: "multi",
          topicTags: ["scientific notation", "standard form", "operations"],
          canBePrimary: true,
          canBeSupporting: true,
          canBeOutputSkill: true,
        },
      },
    ],
  },
];