export const BUILDER_DEFAULT_HUD_HEIGHT = 170;
export const BUILDER_DIVIDER_WIDTH_PX = 8;

export const QUESTION_NUMBER_COL_PX = 30;
export const QUESTION_MARKS_COL_PX = 42;
export const QUESTION_COL_GAP_PX = 10;

export const QUESTION_TEXT_COL_LEFT_PX =
  QUESTION_NUMBER_COL_PX + QUESTION_COL_GAP_PX;

export const DEFAULT_QUESTION_SPACING_BASE_PX = 48;

export const DRAFT_BOTTOM_CONTROLS_HEIGHT_PX = 38;
export const DRAFT_BOTTOM_CONTROLS_GAP_PX = 10;

export const DRAFT_EDIT_BUTTON_RIGHT_PX = 86;