export const ASSESSMENT_WORKSPACE_DEFAULT_HUD_HEIGHT =
  170;

export const ASSESSMENT_WORKSPACE_DIVIDER_WIDTH_PX =
  8;

export const ASSESSMENT_WORKSPACE_MIN_HUD_HEIGHT =
  88;

export const ASSESSMENT_WORKSPACE_MIN_PREVIEW_HEIGHT =
  120;

export const ASSESSMENT_WORKSPACE_TOP_BAR_HEIGHT =
  65;

export const ASSESSMENT_WORKSPACE_HUD_RESIZE_HANDLE_HEIGHT =
  12;

export const ASSESSMENT_WORKSPACE_DEFAULT_LEFT_PANE_RATIO =
  1 / 2.25;

export const ASSESSMENT_WORKSPACE_MIN_LEFT_PANE_RATIO =
  0.28;

export const ASSESSMENT_WORKSPACE_MAX_LEFT_PANE_RATIO =
  0.62;