<ClassCoverageDetails
  courseId={
    schoolClass.courseId
  }
  selection={
    selection
  }
  onSelectionChange={
    setSelection
  }
  completedSkillIds={
    schoolClass.completedSkillIds
  }
  completedConceptIds={
    schoolClass.completedConceptIds
  }
  theme={
    theme
  }
  courseAccent={
    courseAccent
  }
/>