import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("3",21,"QUESTION","P2",5);
export const N5_MATHS_2014_P2_Q3={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q3",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"3",answerCatalogId:"N5_MATH_2014_P2_Q3_MS"},sourceLayout:{sourcePages:[21],printedPageLabels:["Page 5"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":16,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Three parts share a ticket-price context and provide substantial working space."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"MULTIPART",totalMarks:6,parts:[{"id":"Q3_a","label":"a","marks":1,"primarySkillId":"alg-a08-simultaneous-equations","secondarySkillIds":[],"conceptIds":["alg-a8-1"],"topic":"ALG","commandTypes":["WRITE_DOWN"],"responseTypes":["EQUATION"],"dependsOnPartIds":[],"sharedInformationIds":["Q3_INFO_BILL"],"visualElementIds":[]},{"id":"Q3_b","label":"b","marks":1,"primarySkillId":"alg-a08-simultaneous-equations","secondarySkillIds":[],"conceptIds":["alg-a8-1"],"topic":"ALG","commandTypes":["WRITE_DOWN"],"responseTypes":["EQUATION"],"dependsOnPartIds":[],"sharedInformationIds":["Q3_INFO_BEN"],"visualElementIds":[]},{"id":"Q3_c","label":"c","marks":4,"primarySkillId":"alg-a08-simultaneous-equations","secondarySkillIds":[],"conceptIds":["alg-a8-1"],"topic":"ALG","commandTypes":["CALCULATE"],"responseTypes":["MIXED"],"dependsOnPartIds":["Q3_a","Q3_b"],"sharedInformationIds":["Q3_INFO_BILL","Q3_INFO_BEN"],"visualElementIds":[]}
],dependencyType:"SHARED_SETUP",sharedStimulus:true,sharedVisuals:false,sharedGivenData:true,requiredResultProvided:false},curriculum:{"primaryTopic":"ALG","primarySkillId":"alg-a08-simultaneous-equations","secondarySkillIds":[],"primaryConceptId":"alg-a8-1","conceptIds":["alg-a8-1"],"paperSuitability":"P2","standardProfile":"C+A","thinkingProfile":"MIXED","crossSkillQuestion":false,"skillMarkDistribution":{"alg-a08-simultaneous-equations":6},"conceptMarkDistribution":{"alg-a8-1":6}
},task:{"commandTypes":["WRITE_DOWN","CALCULATE"],"responseTypes":["EQUATION","MIXED"],"responseCount":4,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Translate two contextual purchase statements into simultaneous linear equations and solve for two ticket prices.","subgoals":[{"id":"Q3_S1","summary":"Define variables for adult and child ticket prices and form the first equation.","dependsOnSubgoalIds":[]},{"id":"Q3_S2","summary":"Form the second equation from the second purchase.","dependsOnSubgoalIds":[]},{"id":"Q3_S3","summary":"Eliminate or substitute to solve for one ticket price.","dependsOnSubgoalIds":["Q3_S1","Q3_S2"]},{"id":"Q3_S4","summary":"Use the first solved value to find the other ticket price.","dependsOnSubgoalIds":["Q3_S3"]}
],"operationTypes":["MODEL","SOLVE","REARRANGE","SUBSTITUTE"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":4,"intermediateQuantityTypes":["two linear equations","one solved ticket price"],"methodSelectionRequired":true,"solutionCountExpected":2,"validitySelectionRequired":false,"representationTransitions":[{"from":"purchase context","to":"simultaneous linear equations","purpose":"represent ticket totals algebraically"},{"from":"simultaneous equations","to":"contextual prices","purpose":"interpret the solved variables"}
]},information:[{"id":"Q3_INFO_BILL","informationType":"purchase","normalisedContent":"five adult tickets plus three child tickets cost 158.25","value":"5 adults + 3 children = 158.25","unit":"£","source":"TEXT","explicitness":"EXPLICIT","role":"RELATIONSHIP","visualElementId":null,"usedByPartIds":["Q3_a","Q3_c"]},{"id":"Q3_INFO_BEN","informationType":"purchase","normalisedContent":"three adult tickets plus two child tickets cost 98","value":"3 adults + 2 children = 98","unit":"£","source":"TEXT","explicitness":"EXPLICIT","role":"RELATIONSHIP","visualElementId":null,"usedByPartIds":["Q3_b","Q3_c"]}
],reasoning:{"reasoningTypes":["REPRESENTATION_TRANSLATION","MULTI_STAGE","METHOD_SELECTION","CONTEXT_INTERPRETATION"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"MEDIUM","arithmeticLoad":"MEDIUM","algebraicLoad":"MEDIUM","representationLoad":"VERY_LOW","languageLoad":"MEDIUM","contextInterpretationLoad":"LOW","reasoningDepth":"MEDIUM","dependencyCount":2,"difficultyDrivers":["translating prose totals into equations","choosing elimination or substitution","decimal money arithmetic"]}
},numbers:{"numberTypes":["INTEGER","DECIMAL"],"nonCalculatorFriendly":false,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["two equations have a unique positive solution","ticket prices are realistic positive currency values","coefficients are small whole-number ticket counts"],"safeVariationAxes":["ticket counts","two total costs","purchase context"],"invariantRelationships":["two independent linear equations in the same two unknown prices"],"degeneracyConditionsToAvoid":["proportional equations","negative or zero ticket price","unreasonably awkward currency values"]},constraints:{"mathematicalDomainConstraints":[],"contextValidityConstraints":["Both solved ticket prices must be positive and realistic."],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"MIXED","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":"currency","unitSymbol":"£","conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":4,"domainRestriction":null,"contextualWordsRequired":true,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":true,"contextDomain":"ticket pricing","contextRole":"MODEL_DEFINING","namedPeoplePresent":false,"currencyPresent":true,"realWorldUnitsPresent":true,"realismConstrainsAnswer":true,"contextObjects":["adult ticket","child ticket","theatre purchase"],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"HIGH","scaffoldingLevel":"HIGH","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":true,"promptSummary":"Two ticket purchases with different adult/child counts and totals are converted into simultaneous equations and solved for both prices.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:catalogValue({"expansionRequired":false,"factorisationRequired":false,"completingSquareRequired":false,"rationalExpressionPresent":false,"changeOfSubjectRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),equationsInequalities:catalogValue({"equationFamily":"SIMULTANEOUS_LINEAR","inequalityPresent":false,"algebraicMethodRequired":false,"repeatedSubstitutionInvalid":true,"expectedSolutionCount":2,"rejectedSolutionReason":null},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"ALG_SIMULTANEOUS_EQUATIONS_FROM_TWO_PURCHASES","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["two contextual totals","two unknown unit prices","form equations","solve unique system"],"surfaceStyleIds":["MULTIPART_CONTEXT_TO_EQUATIONS"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"CONTEXTUAL","proseAmount":"HIGH","visualAmount":"NONE","layoutComplexity":"MEDIUM","informationOrderCanVarySafely":false,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["ALG_SIMULTANEOUS_EQUATIONS_FROM_TWO_PURCHASES"],"invariantMathematics":["two independent purchase equations","unique positive solution"],"variableParameters":["item counts","unit prices","derived totals","context goods/services"],"parameterConstraints":["determinant non-zero","prices positive and contextually sensible"],"safeContextVariations":["tickets","food items","admission prices","product bundles"],"safeRepresentationVariations":[],"unsafeVariations":["dependent equations","negative solution"],"difficultyControls":["coefficient relationships","whether elimination requires scaling one or both equations"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
