import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("9",27,"QUESTION","P2",11);
export const N5_MATHS_2014_P2_Q9={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q9",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"9",answerCatalogId:"N5_MATH_2014_P2_Q9_MS"},sourceLayout:{sourcePages:[27],printedPageLabels:["Page 11"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":11,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Large lower-page working area follows the algebraic-fraction prompt."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:3,parts:[{"id":"Q9_MAIN","label":"","marks":3,"primarySkillId":"alg-a05-operations-algebraic-fractions","secondarySkillIds":[],"conceptIds":["alg-a5-1"],"topic":"ALG","commandTypes":["EXPRESS"],"responseTypes":["EXPRESSION"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":[]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"ALG","primarySkillId":"alg-a05-operations-algebraic-fractions","secondarySkillIds":[],"primaryConceptId":"alg-a5-1","conceptIds":["alg-a5-1"],"paperSuitability":"P2","standardProfile":"C+A","thinkingProfile":"OPERATIONAL","crossSkillQuestion":false,"skillMarkDistribution":{"alg-a05-operations-algebraic-fractions":3},"conceptMarkDistribution":{"alg-a5-1":3}
},task:{"commandTypes":["EXPRESS"],"responseTypes":["EXPRESSION"],"responseCount":1,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Subtract two algebraic fractions with different linear denominators and simplify to one fraction.","subgoals":[{"id":"Q9_S1","summary":"Form the common denominator x(x+5).","dependsOnSubgoalIds":[]},{"id":"Q9_S2","summary":"Rewrite both fractions over the common denominator and combine numerators.","dependsOnSubgoalIds":["Q9_S1"]},{"id":"Q9_S3","summary":"Simplify the numerator while retaining the stated domain restrictions.","dependsOnSubgoalIds":["Q9_S2"]}
],"operationTypes":["MULTIPLY","SUBTRACT","EXPAND","SIMPLIFY"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":3,"intermediateQuantityTypes":["common denominator","combined numerator"],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q9_INFO_EXPR","informationType":"expression","normalisedContent":"subtract 3/x from 7/(x+5)","value":"7/(x+5)-3/x","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q9_MAIN"]},{"id":"Q9_INFO_DOMAIN","informationType":"domain","normalisedContent":"x is not -5 or 0","value":"x≠-5, x≠0","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"DOMAIN","visualElementId":null,"usedByPartIds":["Q9_MAIN"]}
],reasoning:{"reasoningTypes":["DIRECT_PROCEDURE","MULTI_STAGE"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"VERY_LOW","arithmeticLoad":"LOW","algebraicLoad":"MEDIUM","representationLoad":"VERY_LOW","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"MEDIUM","dependencyCount":0,"difficultyDrivers":["constructing a common algebraic denominator","sign handling when subtracting expanded numerators","retaining domain restrictions"]}
},numbers:{"numberTypes":["INTEGER","ALGEBRAIC","NEGATIVE"],"nonCalculatorFriendly":true,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["two non-equivalent linear denominator factors","domain restrictions match denominator zeros","combined numerator remains simplifiable but non-trivial"],"safeVariationAxes":["numerator constants","linear denominator shift"],"invariantRelationships":["two algebraic fractions combine over product common denominator"],"degeneracyConditionsToAvoid":["identical denominators","numerator cancellation to zero unless intended","common factor cancelling a stated excluded value without retaining original restriction"]},constraints:{"mathematicalDomainConstraints":["Denominators are non-zero: x≠0 and x≠-5."],"contextValidityConstraints":[],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":["Final response is a single fraction in simplest form."]},answerSpecification:{"answerForm":"SYMBOLIC","simplestFormRequired":true,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":null,"unitSymbol":null,"conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":1,"domainRestriction":"x≠0, x≠-5","contextualWordsRequired":false,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":false,"contextDomain":null,"contextRole":"NONE","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":false,"realismConstrainsAnswer":false,"contextObjects":[],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"LOW","scaffoldingLevel":"MEDIUM","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":false,"promptSummary":"Combine two algebraic fractions with different linear denominators into one simplified fraction, with excluded denominator values supplied.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:catalogValue({"expansionRequired":true,"factorisationRequired":false,"completingSquareRequired":false,"rationalExpressionPresent":true,"changeOfSubjectRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"ALG_ALGEBRAIC_FRACTIONS_SUBTRACT_LINEAR_DENOMINATORS","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["two rational terms","different linear denominators","common denominator","single simplified fraction","domain restrictions"],"surfaceStyleIds":["INLINE_ALGEBRAIC_FRACTIONS_WITH_RESTRICTIONS"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"ABSTRACT","proseAmount":"LOW","visualAmount":"NONE","layoutComplexity":"LOW","informationOrderCanVarySafely":true,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["ALG_ALGEBRAIC_FRACTIONS_SUBTRACT_LINEAR_DENOMINATORS"],"invariantMathematics":["two rational terms combine to one fraction","original denominator exclusions remain valid"],"variableParameters":["numerator constants","linear denominator shifts","operation sign"],"parameterConstraints":["denominators distinct and non-zero on allowed domain"],"safeContextVariations":[],"safeRepresentationVariations":[],"unsafeVariations":["cancel original domain restriction after algebraic simplification"],"difficultyControls":["amount of numerator expansion","factor cancellation"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
