import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("8",27,"QUESTION","P2",11);
export const N5_MATHS_2014_P2_Q8={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q8",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"8",answerCatalogId:"N5_MATH_2014_P2_Q8_MS"},sourceLayout:{sourcePages:[27],printedPageLabels:["Page 11"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":9,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Working space separates Q8 from Q9 on the same page."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:3,parts:[{"id":"Q8_MAIN","label":"","marks":3,"primarySkillId":"num-n2-indices","secondarySkillIds":[],"conceptIds":["num-n2-1"],"topic":"NUM","commandTypes":["SIMPLIFY"],"responseTypes":["EXPRESSION"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":[]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"NUM","primarySkillId":"num-n2-indices","secondarySkillIds":[],"primaryConceptId":"num-n2-1","conceptIds":["num-n2-1"],"paperSuitability":"P2","standardProfile":"C","thinkingProfile":"OPERATIONAL","crossSkillQuestion":false,"skillMarkDistribution":{"num-n2-indices":3},"conceptMarkDistribution":{"num-n2-1":3}
},task:{"commandTypes":["SIMPLIFY"],"responseTypes":["EXPRESSION"],"responseCount":1,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Simplify a monomial fraction by reducing numerical coefficients and applying index laws across multiplication and division.","subgoals":[{"id":"Q8_S1","summary":"Simplify the numerical coefficient 10/2.","dependsOnSubgoalIds":[]},{"id":"Q8_S2","summary":"Combine powers of n in the numerator. ","dependsOnSubgoalIds":[]},{"id":"Q8_S3","summary":"Subtract denominator exponent to obtain the final power.","dependsOnSubgoalIds":["Q8_S2"]}
],"operationTypes":["MULTIPLY","DIVIDE","SIMPLIFY"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":3,"intermediateQuantityTypes":["combined numerator power"],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q8_INFO_EXPR","informationType":"expression","normalisedContent":"monomial fraction is (n^5 × 10n)/(2n^2)","value":"(n^5*10n)/(2n^2)","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q8_MAIN"]}
],reasoning:{"reasoningTypes":["DIRECT_PROCEDURE","STRUCTURE_RECOGNITION"],"difficulty":{"overallDifficulty":"LOW","methodSelectionLoad":"VERY_LOW","arithmeticLoad":"LOW","algebraicLoad":"LOW","representationLoad":"VERY_LOW","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"LOW","dependencyCount":0,"difficultyDrivers":["applying multiplication and division index laws in one expression","simplifying coefficient and power independently"]}
},numbers:{"numberTypes":["INTEGER","POWER","ALGEBRAIC"],"nonCalculatorFriendly":true,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["base variable is common across powers","final exponent remains a positive integer","numerical coefficient simplifies exactly"],"safeVariationAxes":["coefficient pair","numerator exponents","denominator exponent"],"invariantRelationships":["same-base powers multiply then divide"],"degeneracyConditionsToAvoid":["exponents cancelling to zero unless intended","coefficient not reducible when coefficient simplification is part of demand"]},constraints:{"mathematicalDomainConstraints":[],"contextValidityConstraints":[],"calculatorModeConstraints":["Although Paper 2 permits a calculator, the structural index-law reasoning is calculator-independent."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"SYMBOLIC","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":null,"unitSymbol":null,"conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":1,"domainRestriction":null,"contextualWordsRequired":false,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":false,"contextDomain":null,"contextRole":"NONE","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":false,"realismConstrainsAnswer":false,"contextObjects":[],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"LOW","scaffoldingLevel":"MEDIUM","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":false,"promptSummary":"Simplify a single algebraic fraction containing a product of powers of the same base and numerical coefficients.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:catalogValue({"powersPresent":true,"surdsPresent":false,"scientificNotationPresent":false,"rationalisationRequired":false,"exactSimplificationRequired":true},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),algebra:catalogValue({"expansionRequired":false,"factorisationRequired":false,"completingSquareRequired":false,"rationalExpressionPresent":true,"changeOfSubjectRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"NUM_INDICES_MONOMIAL_FRACTION_MULTIPLY_DIVIDE","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["same-base index multiplication","same-base division","coefficient simplification"],"surfaceStyleIds":["INLINE_INDEX_FRACTION"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"ABSTRACT","proseAmount":"LOW","visualAmount":"NONE","layoutComplexity":"LOW","informationOrderCanVarySafely":true,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["NUM_INDICES_MONOMIAL_FRACTION_MULTIPLY_DIVIDE"],"invariantMathematics":["same-base index laws","exact monomial result"],"variableParameters":["coefficients","numerator exponents","denominator exponent"],"parameterConstraints":["final exponent and coefficient remain simple"],"safeContextVariations":[],"safeRepresentationVariations":[],"unsafeVariations":[],"difficultyControls":["number of index-law steps","coefficient cancellation"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
