import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("12",29,"QUESTION","P2",13);
export const N5_MATHS_2014_P2_Q12={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q12",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"12",answerCatalogId:"N5_MATH_2014_P2_Q12_MS"},sourceLayout:{sourcePages:[29],printedPageLabels:["Page 13"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":12,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Large lower-page working area follows the trigonometric equation."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:3,parts:[{"id":"Q12_MAIN","label":"","marks":3,"primarySkillId":"trig-t02-equations","secondarySkillIds":[],"conceptIds":["trig-t2-2"],"topic":"TRIG","commandTypes":["SOLVE"],"responseTypes":["NUMBER"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":[]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"TRIG","primarySkillId":"trig-t02-equations","secondarySkillIds":[],"primaryConceptId":"trig-t2-2","conceptIds":["trig-t2-2"],"paperSuitability":"P2","standardProfile":"A","thinkingProfile":"REASONING","crossSkillQuestion":false,"skillMarkDistribution":{"trig-t02-equations":3},"conceptMarkDistribution":{"trig-t2-2":3}
},task:{"commandTypes":["SOLVE"],"responseTypes":["NUMBER"],"responseCount":2,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Rearrange a cosine equation, find a reference/principal angle and determine all solutions in a full 0-to-360-degree domain.","subgoals":[{"id":"Q12_S1","summary":"Rearrange to isolate cos x.","dependsOnSubgoalIds":[]},{"id":"Q12_S2","summary":"Use inverse cosine to obtain one angle.","dependsOnSubgoalIds":["Q12_S1"]},{"id":"Q12_S3","summary":"Use cosine symmetry/quadrant reasoning to obtain the second solution in the domain.","dependsOnSubgoalIds":["Q12_S2"]}
],"operationTypes":["REARRANGE","DIVIDE","SOLVE","FILTER_SOLUTIONS"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":3,"intermediateQuantityTypes":["isolated cosine value","principal angle"],"methodSelectionRequired":false,"solutionCountExpected":2,"validitySelectionRequired":true,"representationTransitions":[]},information:[{"id":"Q12_INFO_EQ","informationType":"equation","normalisedContent":"trigonometric equation is 11 cos x° - 2 = 3","value":"11cos(x)-2=3","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q12_MAIN"]},{"id":"Q12_INFO_DOMAIN","informationType":"domain","normalisedContent":"0 ≤ x ≤ 360 degrees","value":"0<=x<=360","unit":"degrees","source":"TEXT","explicitness":"EXPLICIT","role":"DOMAIN","visualElementId":null,"usedByPartIds":["Q12_MAIN"]}
],reasoning:{"reasoningTypes":["MULTI_STAGE","SOLUTION_FILTERING","STRUCTURE_RECOGNITION"],"difficulty":{"overallDifficulty":"HIGH","methodSelectionLoad":"LOW","arithmeticLoad":"LOW","algebraicLoad":"LOW","representationLoad":"MEDIUM","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"HIGH","dependencyCount":0,"difficultyDrivers":["isolating the trig function","using calculator inverse cosine","finding both cosine solutions in the stated domain"]}
},numbers:{"numberTypes":["INTEGER","DECIMAL"],"nonCalculatorFriendly":false,"exactAndApproximateMixed":true,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":false,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":2,"parameterConstraints":["isolated cosine value lies strictly between -1 and 1","avoid special boundary values unless intentionally assessing them","domain includes two distinct cosine solutions"],"safeVariationAxes":["linear coefficient","constant terms","isolated cosine value"],"invariantRelationships":["equation rearranges to cos x = k","two valid solutions in full-degree domain"],"degeneracyConditionsToAvoid":["k=±1 giving one distinct solution","|k|>1 giving no real solution","k=0 if special-angle triviality is not intended"]},constraints:{"mathematicalDomainConstraints":["0≤x≤360 degrees"],"contextValidityConstraints":[],"calculatorModeConstraints":["Calculator should be in degree mode."],"methodConstraints":[],"presentationConstraints":["All valid solutions in the stated domain are required."]},answerSpecification:{"answerForm":"APPROXIMATE","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":"angle","unitSymbol":"degrees","conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":2,"domainRestriction":"0≤x≤360","contextualWordsRequired":false,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":false,"contextDomain":null,"contextRole":"NONE","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":false,"realismConstrainsAnswer":false,"contextObjects":[],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"LOW","scaffoldingLevel":"MEDIUM","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":false,"promptSummary":"Solve a linear cosine equation over the full 0-to-360-degree domain, giving both valid solutions.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:notApplicable(),equationsInequalities:catalogValue({"equationFamily":"TRIGONOMETRIC_COSINE","inequalityPresent":false,"algebraicMethodRequired":false,"repeatedSubstitutionInvalid":true,"expectedSolutionCount":2,"rejectedSolutionReason":"Solutions outside the stated angular domain are invalid."},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:catalogValue({"trigFunctions":["COS"],"trigContext":"EQUATION","angleUnit":"DEGREES","domainStart":0,"domainEnd":360,"domainEndInclusive":true,"quadrantReasoningRequired":true,"inverseTrigRequired":true,"multipleSolutionsRequired":true,"exactTrigValuesRequired":false,"sineRuleUsed":false,"cosineRuleUsed":false,"areaFormulaUsed":false,"calculatorModeSensitive":true},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"TRIG_COSINE_EQUATION_TWO_SOLUTIONS_FULL_TURN","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["linear cosine equation","isolate cos x","inverse trig","two solutions","0-to-360 domain"],"surfaceStyleIds":["INLINE_TRIG_EQUATION_WITH_DOMAIN"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"ABSTRACT","proseAmount":"LOW","visualAmount":"NONE","layoutComplexity":"LOW","informationOrderCanVarySafely":true,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["TRIG_COSINE_EQUATION_TWO_SOLUTIONS_FULL_TURN"],"invariantMathematics":["isolated cosine value admits two distinct full-turn solutions"],"variableParameters":["equation coefficients","target cosine value","rounding profile"],"parameterConstraints":["|cos value|<1 and not a degeneracy","two solutions lie in domain"],"safeContextVariations":[],"safeRepresentationVariations":[],"unsafeVariations":["values with no real solution","single-solution boundary value"],"difficultyControls":["sign of cosine value","whether solutions lie in QI/QIV or QII/QIII","arithmetic needed to isolate trig function"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
