import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("5",24,"QUESTION","P2",8);
const visualEvidence=qpEvidence("5",24,"VISUAL","P2",8);
export const N5_MATHS_2014_P2_Q5={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q5",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"5",answerCatalogId:"N5_MATH_2014_P2_Q5_MS"},sourceLayout:{sourcePages:[24],printedPageLabels:["Page 8"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":15,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Large response space follows a paired-jar contextual diagram."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:3,parts:[{"id":"Q5_MAIN","label":"","marks":3,"primarySkillId":"geo-g06-similarity","secondarySkillIds":[],"conceptIds":["geo-g6-1"],"topic":"GEO","commandTypes":["CALCULATE"],"responseTypes":["NUMBER"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":["VIS_Q5"]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"GEO","primarySkillId":"geo-g06-similarity","secondarySkillIds":[],"primaryConceptId":"geo-g6-1","conceptIds":["geo-g6-1"],"paperSuitability":"P2","standardProfile":"C+A","thinkingProfile":"OPERATIONAL","crossSkillQuestion":false,"skillMarkDistribution":{"geo-g06-similarity":3},"conceptMarkDistribution":{"geo-g6-1":3}
},task:{"commandTypes":["CALCULATE"],"responseTypes":["NUMBER"],"responseCount":1,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Use the linear scale factor between mathematically similar solids to determine the corresponding volume scale factor and larger volume.","subgoals":[{"id":"Q5_S1","summary":"Find the linear scale factor from the two heights.","dependsOnSubgoalIds":[]},{"id":"Q5_S2","summary":"Cube the linear scale factor to obtain the volume factor.","dependsOnSubgoalIds":["Q5_S1"]},{"id":"Q5_S3","summary":"Apply the volume factor to the smaller volume.","dependsOnSubgoalIds":["Q5_S2"]}
],"operationTypes":["DIVIDE","MULTIPLY","EVALUATE"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":3,"intermediateQuantityTypes":["linear scale factor","volume scale factor"],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q5_INFO_SIM","informationType":"relationship","normalisedContent":"the two cylindrical jars are mathematically similar","value":null,"unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"RELATIONSHIP","visualElementId":"VIS_Q5","usedByPartIds":["Q5_MAIN"]},{"id":"Q5_INFO_HSMALL","informationType":"height","normalisedContent":"smaller jar height is 15 cm","value":15,"unit":"cm","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":"VIS_Q5","usedByPartIds":["Q5_MAIN"]},{"id":"Q5_INFO_VSMALL","informationType":"volume","normalisedContent":"smaller jar volume is 750 cubic centimetres","value":750,"unit":"cm^3","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q5_MAIN"]},{"id":"Q5_INFO_HLARGE","informationType":"height","normalisedContent":"larger jar height is 24 cm","value":24,"unit":"cm","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":"VIS_Q5","usedByPartIds":["Q5_MAIN"]}
],reasoning:{"reasoningTypes":["MULTI_STAGE","STRUCTURE_RECOGNITION"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"MEDIUM","arithmeticLoad":"MEDIUM","algebraicLoad":"VERY_LOW","representationLoad":"VERY_LOW","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"MEDIUM","dependencyCount":0,"difficultyDrivers":["recognising volume scales with the cube of linear scale factor","keeping linear and volume ratios distinct"]}
},numbers:{"numberTypes":["INTEGER","DECIMAL","POWER"],"nonCalculatorFriendly":false,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":true,"validSolutionCountDesigned":null,"parameterConstraints":["two positive corresponding lengths define a non-unit scale factor","smaller volume and cubed scale factor produce a manageable result"],"safeVariationAxes":["small height","large height","small volume","context solid"],"invariantRelationships":["solids mathematically similar","volume factor equals cube of linear factor"],"degeneracyConditionsToAvoid":["equal heights","scale factor 1","values that produce unrealistic or excessively awkward volume"]},constraints:{"mathematicalDomainConstraints":[],"contextValidityConstraints":["Larger height should correspond to larger volume in this family."],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"EXACT","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":"volume","unitSymbol":"cm^3","conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":1,"domainRestriction":null,"contextualWordsRequired":false,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":true,"contextDomain":"food containers","contextRole":"MATHEMATICALLY_RELEVANT","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":true,"realismConstrainsAnswer":false,"contextObjects":["cylindrical jars"],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"MEDIUM","scaffoldingLevel":"MEDIUM","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":true,"promptSummary":"Two mathematically similar cylindrical containers have known heights and one known volume; calculate the larger volume.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:catalogValue({elements:[{id:"VIS_Q5",sourceOrder:1,visualType:"CONTEXT_SCHEMATIC",roles:["CONTEXTUAL","STRUCTURAL_MODEL","SUPPORTIVE"],dependency:"REDUNDANT_WITH_TEXT",candidateInteraction:"READ_ONLY",textRelationship:"FULLY_DUPLICATED",scale:{"mode":"SCHEMATIC","measurementFromDrawingPermitted":false,"proportionalAppearanceDesirable":true,"exactGeometryRequiredForRenderer":false,"notes":null},orientation:{"verticalDirectionMeaningful":false,"horizontalDirectionMeaningful":false,"northReferenceMeaningful":false,"groundReferenceMeaningful":false,"startPositionMeaningful":false,"rotationDirectionMeaningful":false,"viewpointMeaningful":false,"mirroringSafe":true,"rotationSafe":true},labels:[],semanticModel:{entities:[{"id":"Q5_SMALL","entityType":"SOLID","semanticName":"smaller cylindrical jar","printedLabel":null,"numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":false,"candidateEditable":false,"attributes":{"height":15,"volume":750}
},{"id":"Q5_LARGE","entityType":"SOLID","semanticName":"larger mathematically similar cylindrical jar","printedLabel":null,"numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":false,"candidateEditable":false,"attributes":{"height":24}
}
],relations:[{"id":"Q5_R1","relationType":"SIMILAR_TO","fromEntityIds":["Q5_SMALL"],"toEntityIds":["Q5_LARGE"],"normalisedMeaning":"The two cylindrical jars are mathematically similar.","essentialToSolution":true,"sourceEvidence":[visualEvidence]}
],facts:[{"id":"Q5_F1","factType":"HEIGHT","normalisedFact":"small jar height 15 cm and large jar height 24 cm","relatedEntityIds":["Q5_SMALL","Q5_LARGE"],"explicitness":"EXPLICIT_LABEL","essentialToSolution":true,"sourceEvidence":[visualEvidence]}
]},layout:{sourcePageNumber:24,sourcePagePosition:"MIDDLE",sourceRelativeWidth:"LARGE",preferredGeneratedAspectRatio:"16:9",minimumReadableWidthMm:null,minimumReadableHeightMm:null,allowInlinePlacement:false,allowFullWidthPlacement:true,labelCollisionSensitive:true},specialisedProfiles:{geometry:notApplicable(),circle:notApplicable(),graph:notApplicable(),scatter:notApplicable(),table:notApplicable(),vector:notApplicable(),bearing:notApplicable(),solid3D:catalogValue({"solidFamilies":["CYLINDER"],"compositeSolid":false,"visibleEdgeEntityIds":[],"hiddenEdgeEntityIds":[],"transparencyUsed":false,"cutawayUsed":false,"coordinateAxesPresent":false,"perspectiveProjectionRequired":true,"faceRelationshipsRelevant":false},[visualEvidence],"CATALOGUE_CLASSIFICATION","HIGH",null),mechanism:notApplicable(),contextImage:notApplicable(),responseSurface:notApplicable()},generation:{readiness:"PARTIAL",strategy:"PROCEDURAL_SVG",rendererFamilyId:"SIMILAR_SOLIDS_CONTEXT",allowedMediaAssetIds:[],requiredAssetTags:[],semanticInvariants:["two visually similar cylinders with one clearly larger","height labels correspond to generated scale factor"],safeVariationAxes:["jar styling","relative on-page size","labels","context object skin"],unsafeVariations:["draw cylinders with visibly different aspect ratios inconsistent with similarity","swap height labels"],permittedOrientationChanges:["mirror or rotate only where semantic orientation remains valid"],permittedStyleChanges:["line weight","label spacing","overall size","non-semantic proportions"],requiredRendererCapabilities:["cylinder silhouettes","dimension labels","paired similar-object layout"],requiredValidationChecks:["all semantic entities and relations resolve","labels agree with generated Question parameters","no clipping or label collision","print remains readable"],provenance:"GENERATION_ANALYSIS"},originality:visualOriginality(),validation:visualValidation(false,true),sourceEvidence:[visualEvidence],confidence:"HIGH",}],visualCount:1,relationships:[],containsEssentialVisualData:false,containsContextImage:false,containsProcedurallyReproducibleDiagram:true,containsResponseSurface:false,generationRequiresMultipleVisuals:false,},[visualEvidence]),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:notApplicable(),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:catalogValue({"geometryFamilies":["SIMILAR_SOLIDS","CYLINDER"],"dimensions":["3D"],"compoundShapeOrSolid":false,"similarityUsed":true,"circleGeometryUsed":false,"pythagorasUsed":false,"areaRequired":false,"volumeRequired":true,"surfaceAreaRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"GEO_SIMILAR_SOLIDS_VOLUME_FROM_LINEAR_SCALE","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["mathematically similar solids","two corresponding lengths","one known volume","cubed scale factor"],"surfaceStyleIds":["CONTEXTUAL_PAIRED_SOLIDS"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"CONTEXTUAL","proseAmount":"MEDIUM","visualAmount":"HIGH","layoutComplexity":"MEDIUM","informationOrderCanVarySafely":true,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["GEO_SIMILAR_SOLIDS_VOLUME_FROM_LINEAR_SCALE"],"invariantMathematics":["volume scale factor is cube of linear scale factor"],"variableParameters":["corresponding lengths","known volume","solid context"],"parameterConstraints":["scale factor positive and non-unit","result remains sensible"],"safeContextVariations":["jars","bottles","models","storage containers","geometric solids"],"safeRepresentationVariations":["procedural paired-solid diagram or context illustration"],"unsafeVariations":["non-similar visual proportions"],"difficultyControls":["scale-factor ratio","whether cubing produces decimal/fractional factor"],"requiredVisualCapabilities":["similar-solid paired renderer"],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(true,"P2"),} satisfies QuestionCatalogEntry;
