import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("2",20,"QUESTION","P2",4);
const visualEvidence=qpEvidence("2",20,"VISUAL","P2",4);
export const N5_MATHS_2014_P2_Q2={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q2",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"2",answerCatalogId:"N5_MATH_2014_P2_Q2_MS"},sourceLayout:{sourcePages:[20],printedPageLabels:["Page 4"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":15,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Large working area follows the 3D coordinate diagram."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:2,parts:[{"id":"Q2_MAIN","label":"","marks":2,"primarySkillId":"geo-g08-3d-coordinates","secondarySkillIds":[],"conceptIds":["geo-g8-1"],"topic":"GEO","commandTypes":["WRITE_DOWN"],"responseTypes":["COORDINATES"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":["VIS_Q2"]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"GEO","primarySkillId":"geo-g08-3d-coordinates","secondarySkillIds":[],"primaryConceptId":"geo-g8-1","conceptIds":["geo-g8-1"],"paperSuitability":"P2","standardProfile":"C","thinkingProfile":"OPERATIONAL","crossSkillQuestion":false,"skillMarkDistribution":{"geo-g08-3d-coordinates":2},"conceptMarkDistribution":{"geo-g8-1":2}
},task:{"commandTypes":["WRITE_DOWN"],"responseTypes":["COORDINATES"],"responseCount":2,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Read the geometry of stacked axis-aligned solids in 3D coordinates to identify two vertex coordinates.","subgoals":[{"id":"Q2_S1","summary":"Use axis alignment and point A to infer coordinate changes to B.","dependsOnSubgoalIds":[]},{"id":"Q2_S2","summary":"Use cube/cuboid geometry and axes to infer the coordinates of C.","dependsOnSubgoalIds":[]}
],"operationTypes":["INTERPRET"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":2,"intermediateQuantityTypes":[],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q2_INFO_A","informationType":"coordinate","normalisedContent":"point A has coordinates (8,4,6)","value":"(8,4,6)","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":"VIS_Q2","usedByPartIds":["Q2_MAIN"]},{"id":"Q2_INFO_STRUCT","informationType":"spatial structure","normalisedContent":"a cube sits on top of an axis-aligned cuboid relative to x,y,z axes","value":null,"unit":null,"source":"DIAGRAM","explicitness":"IMPLIED","role":"RELATIONSHIP","visualElementId":"VIS_Q2","usedByPartIds":["Q2_MAIN"]}
],reasoning:{"reasoningTypes":["VISUAL_INTERPRETATION","REPRESENTATION_TRANSLATION","STRUCTURE_RECOGNITION"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"VERY_LOW","arithmeticLoad":"LOW","algebraicLoad":"VERY_LOW","representationLoad":"HIGH","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"MEDIUM","dependencyCount":0,"difficultyDrivers":["reading a perspective 3D diagram","holding two coordinates constant along an axis-parallel edge","inferring the cube side placement from the stacked solid"]}
},numbers:{"numberTypes":["INTEGER"],"nonCalculatorFriendly":true,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["solid edges remain axis-aligned","labelled known vertex must expose enough dimensions to infer target vertices","cube placement must be unambiguous"],"safeVariationAxes":["cuboid dimensions","cube side length","known vertex","perspective rendering"],"invariantRelationships":["B directly above A","C is a specified cube vertex","axes remain orthogonal and consistently oriented"],"degeneracyConditionsToAvoid":["ambiguous vertex labels","cube hidden by perspective","target coordinates not uniquely determined"]},constraints:{"mathematicalDomainConstraints":[],"contextValidityConstraints":[],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"EXACT","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":null,"unitSymbol":null,"conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":2,"domainRestriction":null,"contextualWordsRequired":false,"coordinateOrderRelevant":true,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":false,"contextDomain":"3D solid geometry","contextRole":"NONE","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":false,"realismConstrainsAnswer":false,"contextObjects":["cube","cuboid"],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"MEDIUM","scaffoldingLevel":"LOW","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":false,"promptSummary":"Use a cube-on-cuboid diagram positioned relative to coordinate axes and one known vertex to write down two other vertex coordinates.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:catalogValue({elements:[{id:"VIS_Q2",sourceOrder:1,visualType:"SOLID_3D",roles:["ESSENTIAL_DATA","STRUCTURAL_MODEL","ORIENTATION_REFERENCE"],dependency:"REQUIRED_TO_SOLVE",candidateInteraction:"READ_ONLY",textRelationship:"PARTLY_DUPLICATED",scale:{"mode":"SCHEMATIC","measurementFromDrawingPermitted":false,"proportionalAppearanceDesirable":true,"exactGeometryRequiredForRenderer":true,"notes":"Coordinate relationships and axis alignment matter; page proportions are schematic."},orientation:{"verticalDirectionMeaningful":true,"horizontalDirectionMeaningful":true,"northReferenceMeaningful":false,"groundReferenceMeaningful":false,"startPositionMeaningful":false,"rotationDirectionMeaningful":false,"viewpointMeaningful":true,"mirroringSafe":false,"rotationSafe":false},labels:[{"entityId":"Q2_X","role":"AXIS","normalisedValue":"x","placementMathematicallyConstrained":true,"collisionPriority":"HIGH"},{"entityId":"Q2_Y","role":"AXIS","normalisedValue":"y","placementMathematicallyConstrained":true,"collisionPriority":"HIGH"},{"entityId":"Q2_Z","role":"AXIS","normalisedValue":"z","placementMathematicallyConstrained":true,"collisionPriority":"HIGH"},{"entityId":"Q2_A","role":"POINT_NAME","normalisedValue":"A (8,4,6)","placementMathematicallyConstrained":false,"collisionPriority":"HIGH"},{"entityId":"Q2_B","role":"POINT_NAME","normalisedValue":"B","placementMathematicallyConstrained":false,"collisionPriority":"HIGH"},{"entityId":"Q2_C","role":"POINT_NAME","normalisedValue":"C","placementMathematicallyConstrained":false,"collisionPriority":"HIGH"}
],semanticModel:{entities:[{"id":"Q2_ORIGIN","entityType":"POINT","semanticName":"coordinate origin","printedLabel":"0","numericValue":null,"symbolicValue":"O","unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{"x":0,"y":0,"z":0}
},{"id":"Q2_X","entityType":"AXIS","semanticName":"x-axis","printedLabel":"x","numericValue":null,"symbolicValue":"x","unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_Y","entityType":"AXIS","semanticName":"y-axis","printedLabel":"y","numericValue":null,"symbolicValue":"y","unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_Z","entityType":"AXIS","semanticName":"z-axis","printedLabel":"z","numericValue":null,"symbolicValue":"z","unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_CUBOID","entityType":"SOLID","semanticName":"axis-aligned cuboid","printedLabel":null,"numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_CUBE","entityType":"SOLID","semanticName":"cube placed on top of cuboid","printedLabel":null,"numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_A","entityType":"VERTEX","semanticName":"labelled vertex A","printedLabel":"A (8,4,6)","numericValue":null,"symbolicValue":"(8,4,6)","unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{"x":8,"y":4,"z":6}
},{"id":"Q2_B","entityType":"VERTEX","semanticName":"target vertex B directly above A","printedLabel":"B","numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
},{"id":"Q2_C","entityType":"VERTEX","semanticName":"target upper cube vertex C","printedLabel":"C","numericValue":null,"symbolicValue":null,"unit":null,"mathematicallyEssential":true,"orientationMeaningful":true,"candidateEditable":false,"attributes":{}
}
],relations:[{"id":"Q2_R1","relationType":"ATTACHED_TO","fromEntityIds":["Q2_CUBE"],"toEntityIds":["Q2_CUBOID"],"normalisedMeaning":"The cube sits on the top face of the cuboid.","essentialToSolution":true,"sourceEvidence":[visualEvidence]},{"id":"Q2_R2","relationType":"DIRECTLY_ABOVE","fromEntityIds":["Q2_B"],"toEntityIds":["Q2_A"],"normalisedMeaning":"B is vertically above A, so x and y coordinates are unchanged.","essentialToSolution":true,"sourceEvidence":[visualEvidence]},{"id":"Q2_R3","relationType":"PART_OF","fromEntityIds":["Q2_A","Q2_B","Q2_C"],"toEntityIds":["Q2_CUBE","Q2_CUBOID"],"normalisedMeaning":"A, B and C are vertices of the stacked axis-aligned solids.","essentialToSolution":true,"sourceEvidence":[visualEvidence]}
],facts:[{"id":"Q2_F1","factType":"COORDINATE","normalisedFact":"A has coordinates (8,4,6).","relatedEntityIds":["Q2_A"],"explicitness":"EXPLICIT_LABEL","essentialToSolution":true,"sourceEvidence":[visualEvidence]},{"id":"Q2_F2","factType":"AXIS_ALIGNMENT","normalisedFact":"Solid edges are aligned with the x, y and z coordinate directions.","relatedEntityIds":["Q2_X","Q2_Y","Q2_Z","Q2_CUBOID","Q2_CUBE"],"explicitness":"VISUALLY_IMPLIED","essentialToSolution":true,"sourceEvidence":[visualEvidence]}
]},layout:{sourcePageNumber:20,sourcePagePosition:"MIDDLE",sourceRelativeWidth:"LARGE",preferredGeneratedAspectRatio:"1:1",minimumReadableWidthMm:null,minimumReadableHeightMm:null,allowInlinePlacement:false,allowFullWidthPlacement:true,labelCollisionSensitive:true},specialisedProfiles:{geometry:notApplicable(),circle:notApplicable(),graph:notApplicable(),scatter:notApplicable(),table:notApplicable(),vector:notApplicable(),bearing:notApplicable(),solid3D:catalogValue({"solidFamilies":["CUBOID","CUBE"],"compositeSolid":true,"visibleEdgeEntityIds":[],"hiddenEdgeEntityIds":[],"transparencyUsed":false,"cutawayUsed":false,"coordinateAxesPresent":true,"perspectiveProjectionRequired":true,"faceRelationshipsRelevant":true},[visualEvidence],"CATALOGUE_CLASSIFICATION","HIGH",null),mechanism:notApplicable(),contextImage:notApplicable(),responseSurface:notApplicable()},generation:{readiness:"PARTIAL",strategy:"PROCEDURAL_SVG",rendererFamilyId:"COORDINATE_3D_SOLIDS",allowedMediaAssetIds:[],requiredAssetTags:[],semanticInvariants:["axis-aligned cuboid and cube","A is fixed at a labelled cuboid/cube junction vertex","B is directly above A","C occupies the corresponding upper cube position shown by the semantic topology"],safeVariationAxes:["perspective angle","non-semantic edge lengths on page","label placement"],unsafeVariations:["swap axis directions","move B away from the vertical through A","draw solids with edges not aligned to axes"],permittedOrientationChanges:[],permittedStyleChanges:["line weight","label spacing","overall size","non-semantic proportions"],requiredRendererCapabilities:["3D axes","cuboid and cube wireframes","vertex labels","perspective projection"],requiredValidationChecks:["all semantic entities and relations resolve","labels agree with generated Question parameters","no clipping or label collision","print remains readable"],provenance:"GENERATION_ANALYSIS"},originality:visualOriginality(),validation:visualValidation(true,true),sourceEvidence:[visualEvidence],confidence:"HIGH",}],visualCount:1,relationships:[],containsEssentialVisualData:true,containsContextImage:false,containsProcedurallyReproducibleDiagram:true,containsResponseSurface:false,generationRequiresMultipleVisuals:false,},[visualEvidence]),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:notApplicable(),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:catalogValue({"geometryFamilies":["CUBOID","CUBE"],"dimensions":["3D"],"compoundShapeOrSolid":true,"similarityUsed":false,"circleGeometryUsed":false,"pythagorasUsed":false,"areaRequired":false,"volumeRequired":false,"surfaceAreaRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:catalogValue({"coordinateDimension":"3D","midpointRequired":false,"gradientRequired":false,"distanceRequired":false,"lineEquationRequired":false,"perpendicularGradientRequired":false,"coordinateVectorReasoningRequired":false},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"COORDINATE_3D_STACKED_SOLIDS_VERTEX_READOFF","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["3D coordinate axes","axis-aligned stacked solids","one known vertex","target vertex coordinates"],"surfaceStyleIds":["PERSPECTIVE_3D_WIREFRAME","LABELLED_COORDINATE_VERTEX"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"ABSTRACT","proseAmount":"MEDIUM","visualAmount":"HIGH","layoutComplexity":"HIGH","informationOrderCanVarySafely":false,"visualPlacementCanVarySafely":false},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["COORDINATE_3D_STACKED_SOLIDS_VERTEX_READOFF"],"invariantMathematics":["axis-aligned 3D solid topology","target vertices uniquely inferable from known coordinate"],"variableParameters":["cuboid dimensions","cube dimension","known/target vertices","perspective"],"parameterConstraints":["diagram and coordinate values remain topologically consistent"],"safeContextVariations":[],"safeRepresentationVariations":["change perspective while preserving axes and visibility"],"unsafeVariations":["perspective or labels that make target vertex ambiguous"],"difficultyControls":["number of coordinates that change","visibility of target vertices"],"requiredVisualCapabilities":["3D coordinate axes renderer","cube/cuboid wireframe","semantic vertex mapping"],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(true,"P2"),} satisfies QuestionCatalogEntry;
