import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import {
  catalogValue,
  notApplicable,
  qpEvidence,
  questionReviewInProgress,
  sourceIsolation,
  visualOriginality,
  visualValidation,
} from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("13", 30, "QUESTION", "P2", 14);
const visualEvidence = qpEvidence("13", 30, "VISUAL", "P2", 14);

export const N5_MATHS_2014_P2_Q13 = {
  identity: {
    id: "N5_MATH_2014_P2_Q13",
    schemaVersion: "N5_CATALOG_V2",
    courseId: "N5_MATH",
    paperContextId: "N5_MATH_2014_P2_CONTEXT",
    year: 2014,
    paper: "P2",
    questionNumber: "13",
    answerCatalogId: "N5_MATH_2014_P2_Q13_MS",
  },

  sourceLayout: {
    sourcePages: [30],
    printedPageLabels: ["Page 14"],
    continuesAcrossPages: false,
    answerSpace: {
      category: "LARGE",
      estimatedWritingLines: 8,
      responseSurfaceVisualIds: [],
      separateFinalAnswerAreaPresent: false,
      measurementMethod: "PDF_RENDER",
      sourceMeasurements: [{
        id: "Q13_SPACE_MAIN",
        regionType: "WRITTEN_WORKING",
        questionPartIds: ["Q13_MAIN"],
        pdfPageNumber: 30,
        printedPageLabel: "Page 14",
        measurementMethod: "PDF_RENDER",
        renderDpi: 300,
        pageWidthPx: 2481,
        pageHeightPx: 3508,
        topPx: 1733,
        bottomPx: 3125,
        leftPx: null,
        rightPx: null,
        heightPx: 1392,
        widthPx: null,
        topPt: 415.95,
        bottomPt: 749.98,
        leftPt: null,
        rightPt: null,
        heightPt: 334.03,
        widthPt: null,
        heightMm: 117.84,
        widthMm: null,
        boundaryConvention: "Bottom of the cross-section area instruction to the top of the [END OF QUESTION PAPER] marker.",
        notes: null,
      }],
      notes: "A context picture and separate mathematical cross-section precede the calculation area.",
    },
    sourceEvidence: [evidence],
  },

  structure: {
    structureType: "SINGLE",
    totalMarks: 5,
    parts: [{
      id: "Q13_MAIN",
      label: "",
      marks: 5,
      primarySkillId: "geo-g02-arc-or-sector",
      secondarySkillIds: ["trig-t03-area"],
      conceptIds: ["geo-g2-1", "trig-t3-1"],
      topic: "GEO",
      commandTypes: ["CALCULATE"],
      responseTypes: ["NUMBER"],
      dependsOnPartIds: [],
      sharedInformationIds: [],
      visualElementIds: ["VIS_Q13_CONTEXT", "VIS_Q13_DIAGRAM"],
      standardProfile: "A",
      thinkingProfile: "REASONING",
      calculatorBurden: "CALCULATOR_STRONGLY_EXPECTED",
    }],
    dependencyType: "INDEPENDENT",
    sharedStimulus: false,
    sharedVisuals: true,
    sharedGivenData: false,
    requiredResultProvided: false,
  },

  curriculum: {
    primaryTopic: "GEO",
    primarySkillId: "geo-g02-arc-or-sector",
    secondarySkillIds: ["trig-t03-area"],
    primaryConceptId: "geo-g2-1",
    conceptIds: ["geo-g2-1", "trig-t3-1"],
    paperSuitability: "P2",
    standardProfile: "A",
    thinkingProfile: "REASONING",
    crossSkillQuestion: true,
    skillMarkDistribution: { "geo-g02-arc-or-sector": 3, "trig-t03-area": 2 },
    conceptMarkDistribution: { "geo-g2-1": 3, "trig-t3-1": 2 },
  },

  task: {
    commandTypes: ["CALCULATE"],
    responseTypes: ["NUMBER"],
    responseCount: 1,
    explicitMethodCue: false,
    methodRestricted: false,
    workingRequestedInPrompt: false,
    justificationRequested: false,
    contextualConclusionRequested: false,
    visualResponseRequired: false,
  },

  mathematics: {
    primaryGoal: "Calculate the major circular-segment area representing the tunnel cross-section.",
    subgoals: [
      { id: "Q13_S1", summary: "Find the full circle area.", dependsOnSubgoalIds: [] },
      { id: "Q13_S2", summary: "Find the 50-degree minor sector area.", dependsOnSubgoalIds: [] },
      { id: "Q13_S3", summary: "Find triangle MON area from two radii and included angle.", dependsOnSubgoalIds: [] },
      { id: "Q13_S4", summary: "Find the minor segment, then subtract it from the circle.", dependsOnSubgoalIds: ["Q13_S1", "Q13_S2", "Q13_S3"] },
    ],
    operationTypes: ["MULTIPLY", "DIVIDE", "SUBTRACT", "EVALUATE"],
    requiredFormulaIds: ["AREA_CIRCLE", "AREA_SECTOR", "AREA_TRIANGLE_TRIG"],
    requiredTheoremIds: [],
    stageCount: 4,
    intermediateQuantityTypes: ["circle area", "minor sector area", "triangle area", "minor segment area"],
    methodSelectionRequired: true,
    solutionCountExpected: 1,
    validitySelectionRequired: false,
    representationTransitions: [{ from: "tunnel image", to: "circle/chord model", purpose: "abstract the opening into geometry" }],
  },

  information: [
    { id: "Q13_INFO_CENTER", informationType: "circle structure", normalisedContent: "O is the circle centre", value: null, unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: "VIS_Q13_DIAGRAM", usedByPartIds: ["Q13_MAIN"] },
    { id: "Q13_INFO_CHORD", informationType: "circle structure", normalisedContent: "MN is a chord", value: null, unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: "VIS_Q13_DIAGRAM", usedByPartIds: ["Q13_MAIN"] },
    { id: "Q13_INFO_ANGLE", informationType: "angle", normalisedContent: "central angle MON is 50 degrees", value: 50, unit: "degrees", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q13_DIAGRAM", usedByPartIds: ["Q13_MAIN"] },
    { id: "Q13_INFO_RADIUS", informationType: "length", normalisedContent: "circle radius is 7 m", value: 7, unit: "m", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q13_DIAGRAM", usedByPartIds: ["Q13_MAIN"] },
    { id: "Q13_INFO_TARGET", informationType: "region", normalisedContent: "target is the major segment above chord MN", value: null, unit: null, source: "DIAGRAM", explicitness: "IMPLIED", role: "TARGET", visualElementId: "VIS_Q13_DIAGRAM", usedByPartIds: ["Q13_MAIN"] },
  ],

  reasoning: {
    reasoningTypes: ["MULTI_STAGE", "VISUAL_INTERPRETATION", "REPRESENTATION_TRANSLATION", "METHOD_SELECTION", "STRUCTURE_RECOGNITION"],
    difficulty: {
      overallDifficulty: "VERY_HIGH",
      methodSelectionLoad: "HIGH",
      arithmeticLoad: "HIGH",
      algebraicLoad: "VERY_LOW",
      representationLoad: "HIGH",
      languageLoad: "MEDIUM",
      contextInterpretationLoad: "MEDIUM",
      reasoningDepth: "VERY_HIGH",
      dependencyCount: 3,
      difficultyDrivers: ["identify major segment", "sector-minus-triangle decomposition", "correct subtraction order"],
    },
  },

  numbers: {
    numberTypes: ["INTEGER", "DECIMAL", "PI"],
    nonCalculatorFriendly: false,
    exactAndApproximateMixed: true,
    simplificationVisibility: "NOT_APPLICABLE",
    expectedFinalValueForm: "DECIMAL",
    intermediateValueSize: "MEDIUM",
    finalValueSize: "MEDIUM",
    dominantInputFormat: "INTEGER",
    dominantOutputFormat: "DECIMAL",
    magnitudeNotes: null,
  },

  calculator: {
    status: "CALCULATOR_REQUIRED",
    burden: "CALCULATOR_STRONGLY_EXPECTED",
    requiredFunctions: ["sine", "pi"],
    modeSensitive: true,
    modeRequirements: ["degree mode"],
    notes: "The triangle-area component requires sin(50 degrees).",
  },

  parameterDesign: {
    deliberatelyConstructedValues: true,
    exactResultDesigned: false,
    roundingDesigned: false,
    factorisableDesigned: false,
    perfectSquareDesigned: false,
    pythagoreanTripleUsed: false,
    niceRatioUsed: false,
    validSolutionCountDesigned: null,
    parameterConstraints: ["radius > 0", "0 < central angle < 180", "target is the major segment"],
    safeVariationAxes: ["radius", "central angle", "context", "labels"],
    invariantRelationships: ["target = circle - (minor sector - triangle)", "OM=ON=radius"],
    degeneracyConditionsToAvoid: ["0 or 180 degree angle", "minor segment accidentally targeted"],
  },

  constraints: {
    mathematicalDomainConstraints: ["0 < central angle < 180 degrees"],
    contextValidityConstraints: ["Context must plausibly map to a curved/circular-profile opening."],
    calculatorModeConstraints: ["Degree mode is required."],
    methodConstraints: [],
    presentationConstraints: [],
  },

  answerSpecification: {
    answerForm: "APPROXIMATE",
    simplestFormRequired: false,
    rationalDenominatorRequired: false,
    positivePowersRequired: false,
    scientificNotationRequired: false,
    precisionType: "NONE",
    precisionValue: null,
    units: { dimension: "area", unitSymbol: "m^2", conversionRequired: false, unitsExplicitlyRequested: false },
    multipleAnswersRequired: 1,
    domainRestriction: null,
    contextualWordsRequired: false,
    coordinateOrderRelevant: false,
    bracketsRelevant: false,
    visualAnswerRequired: false,
  },

  context: {
    contextualised: true,
    contextDomain: "tunnel cross-section",
    contextRole: "MODEL_DEFINING",
    namedPeoplePresent: false,
    currencyPresent: false,
    realWorldUnitsPresent: true,
    realismConstrainsAnswer: true,
    contextObjects: ["tunnel entrance", "circle", "chord"],
    contextCanBeSafelyReplaced: true,
  },

  language: {
    informationDensity: "HIGH",
    scaffoldingLevel: "MEDIUM",
    bulletStructureUsed: true,
    naturalLanguageInterpretationRequired: true,
    promptSummary: "A tunnel entrance is abstracted to a circle/chord model; calculate the major circular-segment area.",
    promptStructure: {
      sentenceCount: 7,
      promptWordCount: 63,
      introductionStyle: "CONTEXT_IMAGE_THEN_SEPARATE_MATHEMATICAL_MODEL",
      relationshipStatementStyle: "BULLETS_DEFINE_CENTRE_CHORD_CENTRAL_ANGLE_AND_RADIUS",
      commandStyle: "DIRECT_CROSS_SECTION_AREA_COMMAND",
      temporalStructure: "NONE",
      informationOrder: ["CONTEXT_IMAGE", "CROSS_SECTION_MODEL", "CENTRE", "CHORD", "ANGLE", "RADIUS", "AREA_TARGET"],
      normalisedPromptStructure: ["Introduce a real tunnel entrance.", "Provide a separate circle/chord cross-section.", "List the geometric facts.", "Ask for cross-sectional area."],
      usesPronounReference: false,
      lexicalFeatureTags: ["context image plus schematic", "circle geometry", "bullet givens", "major segment"],
      generatorVariationNotes: "Vary context, radius and angle while preserving the major-segment model and using original visuals.",
    },
    styleNotes: null,
  },

  visuals: catalogValue({
    elements: [
      {
        id: "VIS_Q13_CONTEXT",
        sourceOrder: 1,
        visualType: "CONTEXT_IMAGE",
        roles: ["CONTEXTUAL"],
        dependency: "NOT_REQUIRED",
        candidateInteraction: "READ_ONLY",
        textRelationship: "CONTEXT_ONLY",
        scale: { mode: "NOT_RELEVANT", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: false, exactGeometryRequiredForRenderer: false, notes: "Context only." },
        orientation: { verticalDirectionMeaningful: false, horizontalDirectionMeaningful: false, northReferenceMeaningful: false, groundReferenceMeaningful: true, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: true, rotationSafe: false },
        labels: [],
        semanticModel: {
          entities: [{ id: "Q13_TUNNEL", entityType: "IMAGE", semanticName: "tunnel entrance with curved opening", printedLabel: null, numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: false, orientationMeaningful: false, candidateEditable: false, attributes: {} }],
          relations: [],
          facts: [{ id: "Q13_CF", factType: "CONTEXT", normalisedFact: "The image establishes a tunnel-opening context for the separate model.", relatedEntityIds: ["Q13_TUNNEL"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: false, sourceEvidence: [visualEvidence] }],
        },
        layout: { sourcePageNumber: 30, sourcePagePosition: "TOP", sourceRelativeWidth: "SMALL", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: null, minimumReadableHeightMm: null, allowInlinePlacement: true, allowFullWidthPlacement: false, labelCollisionSensitive: false },
        specialisedProfiles: {
          geometry: notApplicable(), circle: notApplicable(), graph: notApplicable(), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(),
          contextImage: catalogValue({ subjectTags: ["tunnel", "arched entrance"], sceneTags: ["infrastructure"], primaryObject: "tunnel entrance", viewpointRequirement: "front or near-front", recognisableFeaturesRequired: ["curved opening"], orientationRelevant: false, relativePositionRelevant: false, overlaysRequired: false, replaceability: "GENERIC_CONTEXT_ASSET_ACCEPTABLE", assetSearchTags: ["tunnel entrance", "arched tunnel"] }, [visualEvidence]),
          responseSurface: notApplicable(),
        },
        generation: {
          readiness: "PARTIAL",
          strategy: "LICENSED_MEDIA_ASSET",
          rendererFamilyId: null,
          allowedMediaAssetIds: [],
          requiredAssetTags: ["tunnel entrance", "curved opening"],
          semanticInvariants: ["recognisable tunnel entrance"],
          safeVariationAxes: ["location", "materials", "lighting"],
          unsafeVariations: ["context incompatible with a curved opening"],
          permittedOrientationChanges: ["horizontal mirror"],
          permittedStyleChanges: ["photo", "original illustration", "crop"],
          requiredRendererCapabilities: [],
          requiredValidationChecks: ["approved licence", "no mathematical measurements inferred from context image"],
          provenance: "GENERATION_ANALYSIS",
        },
        originality: visualOriginality(),
        validation: visualValidation(),
        sourceEvidence: [visualEvidence],
        confidence: "HIGH",
      },
      {
        id: "VIS_Q13_DIAGRAM",
        sourceOrder: 2,
        visualType: "CIRCLE_DIAGRAM",
        roles: ["ESSENTIAL_DATA", "STRUCTURAL_MODEL"],
        dependency: "REQUIRED_TO_SOLVE",
        candidateInteraction: "READ_ONLY",
        textRelationship: "PARTLY_DUPLICATED",
        scale: { mode: "SCHEMATIC", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: true, notes: "Circle/chord/angle topology is essential." },
        orientation: { verticalDirectionMeaningful: true, horizontalDirectionMeaningful: false, northReferenceMeaningful: false, groundReferenceMeaningful: true, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: true, rotationSafe: false },
        labels: [],
        semanticModel: {
          entities: [
            { id: "Q13_CIRCLE", entityType: "CIRCLE", semanticName: "cross-section circle", printedLabel: null, numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: { radius: 7 } },
            { id: "Q13_O", entityType: "POINT", semanticName: "centre O", printedLabel: "O", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
            { id: "Q13_MN", entityType: "SEGMENT", semanticName: "chord MN", printedLabel: "MN", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: {} },
            { id: "Q13_MAJOR", entityType: "REGION", semanticName: "target major segment", printedLabel: null, numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: {} },
          ],
          relations: [
            { id: "Q13_R1", relationType: "CENTRE_OF", fromEntityIds: ["Q13_O"], toEntityIds: ["Q13_CIRCLE"], normalisedMeaning: "O is the centre.", essentialToSolution: true, sourceEvidence: [visualEvidence] },
            { id: "Q13_R2", relationType: "CHORD_OF", fromEntityIds: ["Q13_MN"], toEntityIds: ["Q13_CIRCLE"], normalisedMeaning: "MN is a chord subtending 50 degrees at O.", essentialToSolution: true, sourceEvidence: [visualEvidence] },
            { id: "Q13_R3", relationType: "PART_OF", fromEntityIds: ["Q13_MAJOR"], toEntityIds: ["Q13_CIRCLE"], normalisedMeaning: "The tunnel cross-section is the major segment.", essentialToSolution: true, sourceEvidence: [visualEvidence] },
          ],
          facts: [
            { id: "Q13_F1", factType: "RADIUS_AND_ANGLE", normalisedFact: "Radius is 7 m and central angle MON is 50 degrees.", relatedEntityIds: ["Q13_CIRCLE", "Q13_O", "Q13_MN"], explicitness: "EXPLICIT_LABEL", essentialToSolution: true, sourceEvidence: [visualEvidence] },
            { id: "Q13_F2", factType: "TARGET_REGION", normalisedFact: "Target is the major segment, not the minor segment.", relatedEntityIds: ["Q13_MAJOR", "Q13_MN"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: true, sourceEvidence: [visualEvidence] },
          ],
        },
        layout: { sourcePageNumber: 30, sourcePagePosition: "MIDDLE", sourceRelativeWidth: "LARGE", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: null, minimumReadableHeightMm: null, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
        specialisedProfiles: {
          geometry: catalogValue({ dimension: "2D", shapeFamilies: ["CIRCLE", "TRIANGLE", "CIRCULAR_SEGMENT"], labelledPointIds: ["Q13_O"], rightAnglesPresent: false, parallelRelationshipsPresent: false, equalLengthRelationshipsPresent: true, similarityPresent: false, congruencePresent: false, shadedRegionsPresent: false, auxiliaryLinesPresent: true, algebraicDimensionsPresent: false, compoundShapePresent: true }, [visualEvidence]),
          circle: catalogValue({ circleCount: 1, centresExplicitlyShown: true, radiiPresent: true, diametersPresent: false, chordsPresent: true, tangentsPresent: false, secantsPresent: false, sectorsPresent: true, segmentsPresent: true, majorMinorArcDistinctionRelevant: true, intersectingCirclesPresent: false, commonChordPresent: false }, [visualEvidence]),
          graph: notApplicable(), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable(),
        },
        generation: {
          readiness: "PARTIAL",
          strategy: "PROCEDURAL_SVG",
          rendererFamilyId: "CIRCLE_CHORD_SEGMENT",
          allowedMediaAssetIds: [],
          requiredAssetTags: [],
          semanticInvariants: ["circle centre O", "chord MN", "radius 7 m", "central angle 50 degrees", "target major segment"],
          safeVariationAxes: ["chord orientation", "label placement", "styling"],
          unsafeVariations: ["target minor segment", "diameter replacing chord", "wrong angle"],
          permittedOrientationChanges: ["horizontal mirror"],
          permittedStyleChanges: ["line weight", "spacing", "overall size"],
          requiredRendererCapabilities: ["circle", "chord", "radii", "central angle", "target region"],
          requiredValidationChecks: ["geometry matches parameters", "target region unambiguous", "print readable"],
          provenance: "GENERATION_ANALYSIS",
        },
        originality: visualOriginality(),
        validation: visualValidation(true, true),
        sourceEvidence: [visualEvidence],
        confidence: "HIGH",
      },
    ],
    visualCount: 2,
    relationships: [{
      id: "Q13_VREL",
      relationshipType: "CONTEXT_TO_MATHEMATICAL_MODEL",
      fromVisualIds: ["VIS_Q13_CONTEXT"],
      toVisualIds: ["VIS_Q13_DIAGRAM"],
      semanticMeaning: "The context image establishes the real object; the separate circle/chord schematic carries the mathematics.",
      essentialToQuestionInterpretation: true,
    }],
    containsEssentialVisualData: true,
    containsContextImage: true,
    containsProcedurallyReproducibleDiagram: true,
    containsResponseSurface: false,
    generationRequiresMultipleVisuals: true,
  }, [visualEvidence]),

  mathematicalModel: notApplicable(),
  specialisedProfiles: {
    arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: notApplicable(), statistics: notApplicable(),
    geometryMeasureCircleSimilarity: catalogValue({ geometryFamilies: ["CIRCLE", "TRIANGLE", "CIRCULAR_SEGMENT"], dimensions: ["2D"], compoundShapeOrSolid: true, similarityUsed: false, circleGeometryUsed: true, pythagorasUsed: false, areaRequired: true, volumeRequired: false, surfaceAreaRequired: false }, [evidence]),
    trigonometry: catalogValue({ trigFunctions: ["SIN"], trigContext: "NON_RIGHT_TRIANGLE", angleUnit: "DEGREES", domainStart: null, domainEnd: null, domainEndInclusive: null, quadrantReasoningRequired: false, inverseTrigRequired: false, multipleSolutionsRequired: false, exactTrigValuesRequired: false, sineRuleUsed: false, cosineRuleUsed: false, areaFormulaUsed: true, calculatorModeSensitive: true }, [evidence]),
    bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable(),
  },

  family: { familyId: "GEO_MAJOR_CIRCULAR_SEGMENT_FROM_CHORD_ANGLE_RADIUS", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["circle", "chord", "central angle", "radius", "sector minus triangle", "major segment"], surfaceStyleIds: ["CONTEXT_IMAGE_PLUS_ABSTRACT_DIAGRAM", "CIRCULAR_TUNNEL_CROSS_SECTION"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "MIXED", proseAmount: "HIGH", visualAmount: "HIGH", layoutComplexity: "HIGH", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: false },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["GEO_MAJOR_CIRCULAR_SEGMENT_FROM_CHORD_ANGLE_RADIUS"], invariantMathematics: ["major segment = circle - (minor sector - isosceles triangle)"], variableParameters: ["radius", "central angle", "context"], parameterConstraints: ["positive radius", "central angle between 0 and 180 degrees"], safeContextVariations: ["tunnel", "arched opening", "curved panel", "circular-profile structure"], safeRepresentationVariations: ["new licensed context image plus original procedural schematic"], unsafeVariations: ["minor segment becomes target", "source artwork reuse"], difficultyControls: ["central angle", "numeric radius", "decomposition visibility"], requiredVisualCapabilities: ["context asset selection", "circle/chord segment renderer"], requiredValidationChecks: ["mark structure valid", "geometry and values consistent", "major target unambiguous", "original/licensed visuals"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(true, "P2"),
} satisfies QuestionCatalogEntry;
