import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("4",22,"QUESTION","P2",6);
export const N5_MATHS_2014_P2_Q4={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q4",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"4",answerCatalogId:"N5_MATH_2014_P2_Q4_MS"},sourceLayout:{sourcePages:[22,23],printedPageLabels:["Page 6","Page 7"],continuesAcrossPages:true,answerSpace:{"category":"LARGE","estimatedWritingLines":18,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Question spans two pages: calculations on Page 6 and comparison/interpretation on Page 7."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"MULTIPART",totalMarks:5,parts:[{"id":"Q4_a_i","label":"a_i","marks":1,"primarySkillId":"stat-s01-mean-sd","secondarySkillIds":[],"conceptIds":["stat-s1-2"],"topic":"STAT","commandTypes":["CALCULATE"],"responseTypes":["NUMBER"],"dependsOnPartIds":[],"sharedInformationIds":["Q4_INFO_DATA"],"visualElementIds":[]},{"id":"Q4_a_ii","label":"a_ii","marks":3,"primarySkillId":"stat-s01-mean-sd","secondarySkillIds":[],"conceptIds":["stat-s1-2"],"topic":"STAT","commandTypes":["CALCULATE"],"responseTypes":["NUMBER"],"dependsOnPartIds":[],"sharedInformationIds":["Q4_INFO_DATA"],"visualElementIds":[]},{"id":"Q4_b","label":"b","marks":1,"primarySkillId":"stat-s01-mean-sd","secondarySkillIds":[],"conceptIds":["stat-s1-2"],"topic":"STAT","commandTypes":["DETERMINE","JUSTIFY"],"responseTypes":["CONCLUSION"],"dependsOnPartIds":["Q4_a_ii"],"sharedInformationIds":["Q4_INFO_NEWSD"],"visualElementIds":[]}
],dependencyType:"FOLLOW_ON",sharedStimulus:true,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"STAT","primarySkillId":"stat-s01-mean-sd","secondarySkillIds":[],"primaryConceptId":"stat-s1-2","conceptIds":["stat-s1-2"],"paperSuitability":"P2","standardProfile":"C+A","thinkingProfile":"MIXED","crossSkillQuestion":false,"skillMarkDistribution":{"stat-s01-mean-sd":5},"conceptMarkDistribution":{"stat-s1-2":5}
},task:{"commandTypes":["CALCULATE","DETERMINE","JUSTIFY"],"responseTypes":["NUMBER","CONCLUSION"],"responseCount":3,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":true,"justificationRequested":true,"contextualConclusionRequested":true,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Calculate mean and sample standard deviation for one data set, then use standard deviation to judge whether a second set is more consistent.","subgoals":[{"id":"Q4_S1","summary":"Calculate the mean of the first six lap times.","dependsOnSubgoalIds":[]},{"id":"Q4_S2","summary":"Calculate the sample standard deviation of the first six lap times.","dependsOnSubgoalIds":[]},{"id":"Q4_S3","summary":"Compare the original and new standard deviations to judge consistency.","dependsOnSubgoalIds":["Q4_S2"]}
],"operationTypes":["ADD","DIVIDE","EVALUATE","COMPARE","INTERPRET"],"requiredFormulaIds":["STANDARD_DEVIATION"],"requiredTheoremIds":[],"stageCount":3,"intermediateQuantityTypes":["mean","sample standard deviation"],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q4_INFO_DATA","informationType":"dataset","normalisedContent":"first lap times are 53, 57, 58, 60, 55, 56 seconds","value":"53,57,58,60,55,56","unit":"s","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q4_a_i","Q4_a_ii"]},{"id":"Q4_INFO_NEWMEAN","informationType":"summary statistic","normalisedContent":"after training change the mean is 55 seconds","value":55,"unit":"s","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q4_b"]},{"id":"Q4_INFO_NEWSD","informationType":"summary statistic","normalisedContent":"after training change the standard deviation is 3.2 seconds","value":3.2,"unit":"s","source":"TEXT","explicitness":"EXPLICIT","role":"GIVEN_VALUE","visualElementId":null,"usedByPartIds":["Q4_b"]},{"id":"Q4_INFO_CONS","informationType":"interpretation target","normalisedContent":"question asks whether consistency improved","value":null,"unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"TARGET","visualElementId":null,"usedByPartIds":["Q4_b"]}
],reasoning:{"reasoningTypes":["DIRECT_PROCEDURE","COMPARISON_INTERPRETATION","JUSTIFICATION"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"VERY_LOW","arithmeticLoad":"HIGH","algebraicLoad":"VERY_LOW","representationLoad":"LOW","languageLoad":"MEDIUM","contextInterpretationLoad":"LOW","reasoningDepth":"MEDIUM","dependencyCount":1,"difficultyDrivers":["multi-step standard deviation arithmetic","knowing lower standard deviation means greater consistency","distinguishing consistency from average speed"]}
},numbers:{"numberTypes":["INTEGER","DECIMAL"],"nonCalculatorFriendly":false,"exactAndApproximateMixed":true,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":false,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["first data set has at least two distinct values","computed standard deviation is meaningfully different from comparison standard deviation","new mean may be distractor but must not determine consistency"],"safeVariationAxes":["raw data values","new summary statistics","context measured variable"],"invariantRelationships":["consistency conclusion is determined by comparing spread/standard deviation"],"degeneracyConditionsToAvoid":["equal standard deviations","all identical data","comparison value so close that rounding changes conclusion"]},constraints:{"mathematicalDomainConstraints":[],"contextValidityConstraints":["Consistency is judged from spread, not from whether the mean is smaller."],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"MIXED","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":"time","unitSymbol":"s","conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":3,"domainRestriction":null,"contextualWordsRequired":true,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":true,"contextDomain":"running performance","contextRole":"MATHEMATICALLY_RELEVANT","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":true,"realismConstrainsAnswer":false,"contextObjects":["runner","lap times","training routine"],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"MEDIUM","scaffoldingLevel":"HIGH","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":true,"promptSummary":"Calculate mean and sample standard deviation for six lap times, then compare the standard deviation with a second training set to judge consistency.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:notApplicable(),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:catalogValue({"rawDataProvided":true,"summaryStatisticsProvided":true,"sampleSize":6,"statisticsRequired":["MEAN","SAMPLE_STANDARD_DEVIATION"],"comparisonRequired":true,"interpretationRequired":true},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"STAT_MEAN_SD_THEN_CONSISTENCY_COMPARISON","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["raw data set","calculate mean","calculate sample standard deviation","compare with second standard deviation","justify consistency conclusion"],"surfaceStyleIds":["MULTIPART_CALCULATE_THEN_INTERPRET"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"CONTEXTUAL","proseAmount":"HIGH","visualAmount":"NONE","layoutComplexity":"MEDIUM","informationOrderCanVarySafely":false,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["STAT_MEAN_SD_THEN_CONSISTENCY_COMPARISON"],"invariantMathematics":["sample standard deviation calculation","lower spread means greater consistency"],"variableParameters":["first data set","second mean","second standard deviation","measurement context"],"parameterConstraints":["standard deviations are distinct enough for unambiguous comparison"],"safeContextVariations":["sports times","manufacturing measurements","test scores","repeated measurements"],"safeRepresentationVariations":[],"unsafeVariations":["mean used as the only basis for consistency"],"difficultyControls":["data spread","arithmetic complexity of deviations","presence of distractor mean"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
