import type{QuestionCatalogEntry} from"../../QuestionCatalogTypes";
import{catalogValue,notApplicable,qpEvidence,questionReviewInProgress,sourceIsolation,visualOriginality,visualValidation} from"../../QuestionCatalogHelpers";
const evidence=qpEvidence("11",29,"QUESTION","P2",13);
export const N5_MATHS_2014_P2_Q11={
// ============================================================================
// SECTION 1 — IDENTITY / SOURCE
// ============================================================================
identity:{id:"N5_MATH_2014_P2_Q11",schemaVersion:"N5_CATALOG_V2",courseId:"N5_MATH",paperContextId:"N5_MATH_2014_P2_CONTEXT",year:2014,paper:"P2",questionNumber:"11",answerCatalogId:"N5_MATH_2014_P2_Q11_MS"},sourceLayout:{sourcePages:[29],printedPageLabels:["Page 13"],continuesAcrossPages:false,answerSpace:{"category":"LARGE","estimatedWritingLines":11,"responseSurfaceVisualIds":[],"separateFinalAnswerAreaPresent":false,"notes":"Large upper-page working space is supplied before Q12."},sourceEvidence:[evidence]},
// ============================================================================
// SECTION 3 — STRUCTURE / CURRICULUM / TASK
// ============================================================================
structure:{structureType:"SINGLE",totalMarks:3,parts:[{"id":"Q11_MAIN","label":"","marks":3,"primarySkillId":"alg-a09-change-subject","secondarySkillIds":[],"conceptIds":["alg-a9-1"],"topic":"ALG","commandTypes":["CHANGE_SUBJECT"],"responseTypes":["EQUATION"],"dependsOnPartIds":[],"sharedInformationIds":[],"visualElementIds":[]}
],dependencyType:"INDEPENDENT",sharedStimulus:false,sharedVisuals:false,sharedGivenData:false,requiredResultProvided:false},curriculum:{"primaryTopic":"ALG","primarySkillId":"alg-a09-change-subject","secondarySkillIds":[],"primaryConceptId":"alg-a9-1","conceptIds":["alg-a9-1"],"paperSuitability":"P2","standardProfile":"C+A","thinkingProfile":"OPERATIONAL","crossSkillQuestion":false,"skillMarkDistribution":{"alg-a09-change-subject":3},"conceptMarkDistribution":{"alg-a9-1":3}
},task:{"commandTypes":["CHANGE_SUBJECT"],"responseTypes":["EQUATION"],"responseCount":1,"explicitMethodCue":false,"methodRestricted":false,"workingRequestedInPrompt":false,"justificationRequested":false,"contextualConclusionRequested":false,"visualResponseRequired":false},
// ============================================================================
// SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
// ============================================================================
mathematics:{"primaryGoal":"Rearrange a multi-term formula to isolate a variable that is multiplied by a squared parameter and a fractional coefficient.","subgoals":[{"id":"Q11_S1","summary":"Subtract the ut term from both sides.","dependsOnSubgoalIds":[]},{"id":"Q11_S2","summary":"Remove the factor one-half and divide by t squared to isolate a.","dependsOnSubgoalIds":["Q11_S1"]}
],"operationTypes":["SUBTRACT","MULTIPLY","DIVIDE","REARRANGE"],"requiredFormulaIds":[],"requiredTheoremIds":[],"stageCount":2,"intermediateQuantityTypes":["s-ut"],"methodSelectionRequired":false,"solutionCountExpected":1,"validitySelectionRequired":false,"representationTransitions":[]},information:[{"id":"Q11_INFO_FORMULA","informationType":"formula","normalisedContent":"formula has structure s=ut+(1/2)at^2","value":"s=ut+0.5at^2","unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"FORMULA","visualElementId":null,"usedByPartIds":["Q11_MAIN"]},{"id":"Q11_INFO_TARGET","informationType":"target","normalisedContent":"a is to become the subject","value":null,"unit":null,"source":"TEXT","explicitness":"EXPLICIT","role":"TARGET","visualElementId":null,"usedByPartIds":["Q11_MAIN"]}
],reasoning:{"reasoningTypes":["DIRECT_PROCEDURE","STRUCTURE_RECOGNITION"],"difficulty":{"overallDifficulty":"MEDIUM","methodSelectionLoad":"VERY_LOW","arithmeticLoad":"LOW","algebraicLoad":"MEDIUM","representationLoad":"VERY_LOW","languageLoad":"LOW","contextInterpretationLoad":"VERY_LOW","reasoningDepth":"MEDIUM","dependencyCount":0,"difficultyDrivers":["isolating a term inside a sum","handling fractional coefficient and squared variable"]}
},numbers:{"numberTypes":["FRACTION","POWER","ALGEBRAIC"],"nonCalculatorFriendly":true,"exactAndApproximateMixed":false,"magnitudeNotes":null},parameterDesign:{"deliberatelyConstructedValues":true,"exactResultDesigned":true,"roundingDesigned":false,"factorisableDesigned":false,"perfectSquareDesigned":false,"pythagoreanTripleUsed":false,"niceRatioUsed":false,"validSolutionCountDesigned":null,"parameterConstraints":["target variable appears linearly in one term","other symbols remain non-zero where division is required"],"safeVariationAxes":["symbol names","integer/fractional coefficient","power on non-target factor"],"invariantRelationships":["target variable isolated by inverse operations"],"degeneracyConditionsToAvoid":["target variable appears in multiple terms","division by a symbol that can be zero without domain qualification"]},constraints:{"mathematicalDomainConstraints":["t must be non-zero in the rearranged form because division by t^2 is required."],"contextValidityConstraints":[],"calculatorModeConstraints":["Calculator use is permitted on Paper 2."],"methodConstraints":[],"presentationConstraints":[]},answerSpecification:{"answerForm":"SYMBOLIC","simplestFormRequired":false,"rationalDenominatorRequired":false,"positivePowersRequired":false,"scientificNotationRequired":false,"precisionType":"NONE","precisionValue":null,"units":{"dimension":null,"unitSymbol":null,"conversionRequired":false,"unitsExplicitlyRequested":false},"multipleAnswersRequired":1,"domainRestriction":null,"contextualWordsRequired":false,"coordinateOrderRelevant":false,"bracketsRelevant":false,"visualAnswerRequired":false},context:{"contextualised":false,"contextDomain":null,"contextRole":"NONE","namedPeoplePresent":false,"currencyPresent":false,"realWorldUnitsPresent":false,"realismConstrainsAnswer":false,"contextObjects":[],"contextCanBeSafelyReplaced":true},language:{"informationDensity":"LOW","scaffoldingLevel":"MEDIUM","bulletStructureUsed":false,"naturalLanguageInterpretationRequired":false,"promptSummary":"Rearrange a supplied formula containing a sum and a half-times-squared term so that a specified variable is the subject.","styleNotes":null},
// ============================================================================
// SECTION 12 — VISUAL EVIDENCE
// ============================================================================
visuals:notApplicable("No supplied visual material is used in this Question."),
// ============================================================================
// SECTION 13 — MODEL / SPECIALISED PROFILES
// ============================================================================
mathematicalModel:notApplicable(),specialisedProfiles:{arithmetic:notApplicable(),percentage:notApplicable(),powersSurdsScientific:notApplicable(),algebra:catalogValue({"expansionRequired":false,"factorisationRequired":false,"completingSquareRequired":false,"rationalExpressionPresent":false,"changeOfSubjectRequired":true},[evidence],"CATALOGUE_CLASSIFICATION","HIGH",null),equationsInequalities:notApplicable(),functionsGraphs:notApplicable(),statistics:notApplicable(),geometryMeasureCircleSimilarity:notApplicable(),trigonometry:notApplicable(),bearings:notApplicable(),coordinateGeometry:notApplicable(),vectors:notApplicable()},
// ============================================================================
// SECTION 15 — FAMILY / SURFACE / GENERATION
// ============================================================================
family:{"familyId":"ALG_CHANGE_SUBJECT_LINEAR_TARGET_WITH_POWERED_FACTOR","subFamilyId":null,"familyConfidence":"HIGH","structuralSignature":["target variable in one additive term","fractional coefficient","powered non-target factor"],"surfaceStyleIds":["INLINE_FORMULA_REARRANGEMENT"],"relatedFamilyIds":[]},surface:{"abstractOrContextual":"ABSTRACT","proseAmount":"LOW","visualAmount":"NONE","layoutComplexity":"LOW","informationOrderCanVarySafely":true,"visualPlacementCanVarySafely":true},generation:{"readiness":"PARTIAL","linkedGeneratorFamilyIds":["ALG_CHANGE_SUBJECT_LINEAR_TARGET_WITH_POWERED_FACTOR"],"invariantMathematics":["target appears linearly once","inverse operations isolate target"],"variableParameters":["symbol names","coefficient","power/factor structure"],"parameterConstraints":["algebraic division remains valid under stated assumptions"],"safeContextVariations":[],"safeRepresentationVariations":[],"unsafeVariations":[],"difficultyControls":["number of inverse-operation stages","fractional coefficient complexity"],"requiredVisualCapabilities":[],"requiredValidationChecks":["mark total and part structure remain valid","generated values satisfy all parameter constraints","required answer form remains attainable","generated instance is mathematically non-degenerate"],"provenance":"GENERATION_ANALYSIS"},
// ============================================================================
// SECTION 16 — SOURCE ISOLATION / REVIEW
// ============================================================================
sourceIsolation:sourceIsolation(),review:questionReviewInProgress(false,"P2"),} satisfies QuestionCatalogEntry;
