import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q12 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q12";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("12", 8);
const M1 = "N5_MATH_2014_P1_Q12_M1";
const M2 = "N5_MATH_2014_P1_Q12_M2";
const M3 = "N5_MATH_2014_P1_Q12_M3";
const M4 = "N5_MATH_2014_P1_Q12_M4";
const D1 = "N5_MATH_2014_P1_Q12_D_ANSWER_ONLY";
const P1 = "N5_MATH_2014_P1_Q12_METHOD_CHORD_PYTHAGORAS";

export const N5_MATHS_2014_P1_Q12_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "12", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 4, sourcePages: [8], printedPageLabels: ["Page eight"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: { responseTypes: ["NUMBER"], canonicalAnswers: [{ id: "N5_MATH_2014_P1_Q12_A1", normalisedAnswer: "18 cm", numericValue: 18, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: ["Valid mathematical working is required for credit; the correct answer alone earns 0/4."], sourceEvidence: [evidence], notes: null }], acceptedEquivalentForms: [], precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile("length", "cm"), requiredContextStatement: false, answerCountRequired: 1, invalidRelatedValues: [], extraAnswerTreatment: "QUESTION_SPECIFIC" },
  sourceDirectives: [{ id: D1, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "BLOCK", normalisedSummary: "The correct chord length without valid working receives no marks.", appliesToPartIds: ["Q12_MAIN"], appliesToMarkIds: [M1, M2, M3, M4], appliesToMethodIds: [P1], marksAwarded: 0, maximumMarks: 0, sourceEvidence: [evidence] }],
  markNodes: [
    markNode(M1, 1, "Q12_MAIN", "INTERPRETATION", "Marshal the circle facts and recognise the right-angle structure needed for the solution.", "Extract the centre-to-chord distance/right-triangle structure from the source diagram and givens.", ["geo-g04-pythagoras-chord"], ["geo-g4-2"], ["Q12_S1", "Q12_S2"], [evidence], { illustrativeEvidence: [{ id: "Q12_M1_E1", normalisedEvidence: "Obtain the centre-to-midpoint distance 12; the source uses this as the illustrative evidence for the first mark.", acceptedLocations: ["WORKING", "DIAGRAM"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: ["VIS_Q12"], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M2, 2, "Q12_MAIN", "PROCESS", "Use Pythagoras on the derived right triangle.", "Set up the half-chord calculation from radius and centre-to-chord distance.", ["geo-g04-pythagoras-chord"], ["geo-g4-2"], ["Q12_S2"], [evidence], { illustrativeEvidence: [{ id: "Q12_M2_E1", normalisedEvidence: "Set the half-chord square equal to 15^2 - 12^2 or equivalent.", acceptedLocations: ["WORKING", "DIAGRAM"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: ["VIS_Q12"], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M3, 3, "Q12_MAIN", "ACCURACY", "Calculate the square of the half-chord correctly.", "Carry out the Pythagorean arithmetic.", ["geo-g04-pythagoras-chord"], ["geo-g4-2"], ["Q12_S2"], [evidence], { illustrativeEvidence: [{ id: "Q12_M3_E1", normalisedEvidence: "Obtain PA^2 = 81 (or the equivalent half-chord squared value).", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M4, 4, "Q12_MAIN", "ACCURACY", "Find the full chord length PQ.", "Convert the half-chord result to the required complete chord.", ["geo-g04-pythagoras-chord"], ["geo-g4-2"], ["Q12_S3"], [evidence], { illustrativeEvidence: [{ id: "Q12_M4_E1", normalisedEvidence: "State PQ = 18.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
  ],
  methodPathways: [{ id: P1, variantId: null, evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q12_P1_S1", order: 1, normalisedStep: "Use AB=27 and radius CB=15 to obtain AC=12 and recognise the perpendicular midpoint geometry.", linkedQuestionSubgoalIds: ["Q12_S1", "Q12_S2"], linkedMarkIds: [M1], dependsOnStepIds: [], requiredOperations: ["SUBTRACT", "INTERPRET_GEOMETRY"], resultingStateSummary: "AC=12 and triangle APC is right-angled at A.", sourceEvidence: [evidence] }, { id: "Q12_P1_S2", order: 2, normalisedStep: "Apply Pythagoras to radius 15 and perpendicular distance 12.", linkedQuestionSubgoalIds: ["Q12_S2"], linkedMarkIds: [M2, M3], dependsOnStepIds: ["Q12_P1_S1"], requiredOperations: ["PYTHAGORAS", "CALCULATE"], resultingStateSummary: "PA^2=81, hence PA=9.", sourceEvidence: [evidence] }, { id: "Q12_P1_S3", order: 3, normalisedStep: "Use A as the chord midpoint to double the half-chord.", linkedQuestionSubgoalIds: ["Q12_S3"], linkedMarkIds: [M4], dependsOnStepIds: ["Q12_P1_S2"], requiredOperations: ["MULTIPLY"], resultingStateSummary: "PQ=18.", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] }],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: { ...workingPolicy(answerOnly("NO_CREDIT", 0, [], [evidence], [D1]), [M1, M2, M3], []), diagramWorkCanScore: true, workingMayBeImpliedForMarkIds: [M1, M2] },
  presentationPolicy: presentationPolicy([evidence], { units: "NOT_STATED" }),
  visualMarking: { ...emptyVisualMarking(), candidateVisualWorkCanEarnMarks: true, visualWorkMayProvideWorkingEvidence: true },
  commonResponses: [{ id: "Q12_CR_ANSWER_ONLY", sourceStatus: "EXPLICITLY_LISTED", category: "ANSWER_ONLY", errorFamily: null, normalisedResponse: "State 18 with no valid supporting work.", affectedMarkIds: [M1, M2, M3, M4], marksAwarded: 0, maximumMarks: 0, followThroughAvailable: false, sourceDirectiveIds: [D1], sourceEvidence: [evidence] }],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D1] },
  relationship: { partMarkMap: [{ questionPartId: "Q12_MAIN", markIds: [M1, M2, M3, M4] }], subgoalMarkMap: [{ questionSubgoalId: "Q12_S1", markIds: [M1] }, { questionSubgoalId: "Q12_S2", markIds: [M1, M2, M3] }, { questionSubgoalId: "Q12_S3", markIds: [M4] }], promptInstructionConsequences: [], informationEvidenceMap: [{ questionInformationId: "Q12_INFO_RADIUS", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }, { questionInformationId: "Q12_INFO_MID", usedByMethodIds: [P1], supportsMarkIds: [M1, M4] }, { questionInformationId: "Q12_INFO_AB", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }, { questionInformationId: "Q12_INFO_COL", usedByMethodIds: [P1], supportsMarkIds: [M1] }], representationEvidenceMap: [{ visualElementId: "VIS_Q12", normalisedEvidence: "Circle topology/collinearity supports the centre-to-chord distance and right-triangle interpretation; annotations on the diagram may form part of valid working evidence.", supportsMarkIds: [M1, M2] }], crossPartDependencies: [], errorPropagationGraph: [] },
  sourcePresentation: sourcePresentation([8], "TABLE_ROW", 1, 1, 1),
  consistency: notReviewedConsistency(comparisonKey("Q12_MARKING_COMPARISON", question.family.familyId, ["geo-g04-pythagoras-chord"], 4, ["NUMBER"], ["answer-only credit", "diagram evidence", "geometry interpretation mark", "half-to-full length step"]), [consistencyFeature("answer_only_treatment", "NO_CREDIT", "Correct chord length without valid working explicitly earns 0/4.", [evidence]), consistencyFeature("visual_or_diagram_work_can_support_process_marks", true, "The first two marks concern geometric structure that may be evidenced through valid diagram/working annotations.", [evidence]), consistencyFeature("geometry_interpretation_is_separate_mark", true, "Marshalling facts/right-angle recognition is explicitly the first mark before Pythagoras.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("12"),
} satisfies AnswerCatalogEntry;
