import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q11 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q11";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("11", 8);
const A1 = "N5_MATH_2014_P1_Q11_A_M1";
const A2 = "N5_MATH_2014_P1_Q11_A_M2";
const B1 = "N5_MATH_2014_P1_Q11_B_M1";
const B2 = "N5_MATH_2014_P1_Q11_B_M2";
const PA = "N5_MATH_2014_P1_Q11_METHOD_GRADIENT";
const PB = "N5_MATH_2014_P1_Q11_METHOD_X_INTERCEPT";
const D_A_FULL = "N5_MATH_2014_P1_Q11_D_A_ANSWER_ONLY";
const D_A_COMMON = "N5_MATH_2014_P1_Q11_D_A_COMMON_FORMS";
const D_B_FULL = "N5_MATH_2014_P1_Q11_D_B_ANSWER_ONLY";
const D_B_X_ONLY = "N5_MATH_2014_P1_Q11_D_B_X_ONLY";
const D_B_WRONG_INTERCEPT = "N5_MATH_2014_P1_Q11_D_B_WRONG_INTERCEPT";

export const N5_MATHS_2014_P1_Q11_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "11", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 4, sourcePages: [8], printedPageLabels: ["Page eight"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: {
    responseTypes: ["MIXED"],
    canonicalAnswers: [
      { id: "N5_MATH_2014_P1_Q11_A1", normalisedAnswer: "gradient = -4/3", numericValue: null, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: ["N5_MATH_2014_P1_Q11_A2"], conditionsForAcceptance: [], sourceEvidence: [evidence], notes: "Part (a)." },
      { id: "N5_MATH_2014_P1_Q11_B1", normalisedAnswer: "(3,0)", numericValue: null, answerForm: "COORDINATES", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: ["Coordinate brackets are required for the second mark."], sourceEvidence: [evidence], notes: "Part (b)." },
    ],
    acceptedEquivalentForms: [{ id: "N5_MATH_2014_P1_Q11_A2", normalisedAnswer: "exact recurring decimal equivalent of -4/3", numericValue: null, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: ["N5_MATH_2014_P1_Q11_A1"], conditionsForAcceptance: ["The recurring notation must express the exact value, not a finite truncation."], sourceEvidence: [evidence], notes: "The source explicitly awards full credit to exact recurring-decimal forms." }],
    precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile(null, null), requiredContextStatement: false, answerCountRequired: 2, invalidRelatedValues: [], extraAnswerTreatment: "QUESTION_SPECIFIC",
  },
  sourceDirectives: [
    { id: D_A_FULL, layer: "QUESTION_NOTE", scope: "PART", effect: "AWARD", normalisedSummary: "The correct gradient without working receives both part (a) marks.", appliesToPartIds: ["Q11_a"], appliesToMarkIds: [A1, A2], appliesToMethodIds: [PA], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidence] },
    { id: D_A_COMMON, layer: "QUESTION_NOTE", scope: "PART", effect: "OTHER", normalisedSummary: "The source explicitly assigns totals to several common gradient representations: exact recurring-decimal equivalents receive 2/2; a finite -1.3 approximation, -4x/3, and +4/3 each receive 1/2; +4x/3 receives 0/2.", appliesToPartIds: ["Q11_a"], appliesToMarkIds: [A1, A2], appliesToMethodIds: [], marksAwarded: null, maximumMarks: null, sourceEvidence: [evidence] },
    { id: D_B_FULL, layer: "QUESTION_NOTE", scope: "PART", effect: "AWARD", normalisedSummary: "The correct coordinate (3,0) without working receives both part (b) marks.", appliesToPartIds: ["Q11_b"], appliesToMarkIds: [B1, B2], appliesToMethodIds: [PB], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidence] },
    { id: D_B_X_ONLY, layer: "QUESTION_NOTE", scope: "PART", effect: "LIMIT", normalisedSummary: "Stating x=3 with or without working receives one mark.", appliesToPartIds: ["Q11_b"], appliesToMarkIds: [B1, B2], appliesToMethodIds: [PB], marksAwarded: 1, maximumMarks: 1, sourceEvidence: [evidence] },
    { id: D_B_WRONG_INTERCEPT, layer: "QUESTION_NOTE", scope: "PART", effect: "LIMIT", normalisedSummary: "The coordinate (0,4), with or without working, receives one mark according to the explicit source note.", appliesToPartIds: ["Q11_b"], appliesToMarkIds: [B1, B2], appliesToMethodIds: [], marksAwarded: 1, maximumMarks: 1, sourceEvidence: [evidence] },
  ],
  markNodes: [
    markNode(A1, 1, "Q11_a", "PROCESS", "Begin rearranging the line equation into a form from which the gradient can be identified.", "Expose the y coefficient relationship needed for the gradient.", ["alg-a06-gradient-from-equation"], ["alg-a6-3"], ["Q11_S1"], [evidence], { illustrativeEvidence: [{ id: "Q11_A_M1_E1", normalisedEvidence: "For example, rearrange to 3y = -4x + 12.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [PA], sourceDirectiveIds: [D_A_FULL, D_A_COMMON] }),
    markNode(A2, 2, "Q11_a", "ACCURACY", "State the gradient.", "Identify the exact slope of the line.", ["alg-a06-gradient-from-equation"], ["alg-a6-3"], ["Q11_S1"], [evidence], { illustrativeEvidence: [{ id: "Q11_A_M2_E1", normalisedEvidence: "State -4/3 or an explicitly accepted exact equivalent.", acceptedLocations: ["FINAL_ANSWER", "WORKING"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [PA], sourceDirectiveIds: [D_A_FULL, D_A_COMMON] }),
    markNode(B1, 1, "Q11_b", "PROCESS", "Demonstrate how to find the x-coordinate of the x-axis intercept.", "Use y=0 and solve the line equation for x.", ["alg-a06-gradient-from-equation"], ["alg-a6-3"], ["Q11_S2"], [evidence], { illustrativeEvidence: [{ id: "Q11_B_M1_E1", normalisedEvidence: "Set y=0 in 4x+3y=12 and obtain x=3.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [PB], sourceDirectiveIds: [D_B_FULL, D_B_X_ONLY, D_B_WRONG_INTERCEPT] }),
    markNode(B2, 2, "Q11_b", "REPRESENTATION", "State the intercept as coordinates using brackets.", "Express the x-axis intercept as the ordered pair (3,0).", ["alg-a06-gradient-from-equation"], ["alg-a6-3"], ["Q11_S2"], [evidence], { illustrativeEvidence: [{ id: "Q11_B_M2_E1", normalisedEvidence: "State (3,0).", acceptedLocations: ["FINAL_ANSWER", "WORKING"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], presentationConditions: ["Coordinate brackets are explicitly required for this mark."], methodPathwayIds: [PB], sourceDirectiveIds: [D_B_FULL, D_B_X_ONLY, D_B_WRONG_INTERCEPT] }),
  ],
  methodPathways: [
    { id: PA, variantId: "REARRANGE_TO_SLOPE_FORM", evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q11_PA_S1", order: 1, normalisedStep: "Rearrange 4x+3y=12 to isolate the y term.", linkedQuestionSubgoalIds: ["Q11_S1"], linkedMarkIds: [A1], dependsOnStepIds: [], requiredOperations: ["REARRANGE"], resultingStateSummary: "3y=-4x+12 or equivalent.", sourceEvidence: [evidence] }, { id: "Q11_PA_S2", order: 2, normalisedStep: "Identify the coefficient of x after division by 3.", linkedQuestionSubgoalIds: ["Q11_S1"], linkedMarkIds: [A2], dependsOnStepIds: ["Q11_PA_S1"], requiredOperations: ["DIVIDE", "INTERPRET"], resultingStateSummary: "gradient=-4/3", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] },
    { id: PB, variantId: "SET_Y_ZERO", evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q11_PB_S1", order: 1, normalisedStep: "Set y=0 and solve for x.", linkedQuestionSubgoalIds: ["Q11_S2"], linkedMarkIds: [B1], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE", "SOLVE"], resultingStateSummary: "x=3", sourceEvidence: [evidence] }, { id: "Q11_PB_S2", order: 2, normalisedStep: "State the x-axis intercept as an ordered pair.", linkedQuestionSubgoalIds: ["Q11_S2"], linkedMarkIds: [B2], dependsOnStepIds: ["Q11_PB_S1"], requiredOperations: ["REPRESENT"], resultingStateSummary: "(3,0)", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] },
  ],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: {
    ...workingPolicy(answerOnly("NOT_STATED", null, [], [evidence], [], [], "Part-specific source rules apply."), [], [A1, A2, B1, B2]),
    partSpecificAnswerOnly: [
      { questionPartId: "Q11_a", profile: answerOnly("FULL_CREDIT", 2, [A1, A2], [evidence], [D_A_FULL]) },
      { questionPartId: "Q11_b", profile: answerOnly("FULL_CREDIT", 2, [B1, B2], [evidence], [D_B_FULL]) },
    ],
  },
  presentationPolicy: presentationPolicy([evidence], { coordinateBrackets: "REQUIRED_FOR_MARK", significantNotationRequirements: ["Exact recurring-decimal notation for -4/3 is accepted for full credit; a finite -1.3 approximation is explicitly only 1/2."] }),
  visualMarking: emptyVisualMarking(),
  commonResponses: [
    { id: "Q11_CR_RECURRING", sourceStatus: "EXPLICITLY_LISTED", category: "VALID_ALTERNATIVE", errorFamily: null, normalisedResponse: "Exact recurring-decimal representation of -4/3.", affectedMarkIds: [], marksAwarded: 2, maximumMarks: 2, followThroughAvailable: false, sourceDirectiveIds: [D_A_COMMON], sourceEvidence: [evidence] },
    { id: "Q11_CR_APPROX_DECIMAL", sourceStatus: "EXPLICITLY_LISTED", category: "ROUNDING_ERROR", errorFamily: "INEXACT_GRADIENT", normalisedResponse: "Finite decimal -1.3 for the gradient.", affectedMarkIds: [A2], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_A_COMMON], sourceEvidence: [evidence] },
    { id: "Q11_CR_GRADIENT_WITH_X", sourceStatus: "EXPLICITLY_LISTED", category: "NOTATION_ERROR", errorFamily: "COEFFICIENT_NOT_EXTRACTED", normalisedResponse: "Write -4x/3 instead of stating the gradient value.", affectedMarkIds: [A2], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_A_COMMON], sourceEvidence: [evidence] },
    { id: "Q11_CR_POSITIVE_MAGNITUDE", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "SIGN_ERROR", normalisedResponse: "State +4/3 as the gradient.", affectedMarkIds: [A2], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_A_COMMON], sourceEvidence: [evidence] },
    { id: "Q11_CR_POSITIVE_WITH_X", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "SIGN_AND_NOTATION_ERROR", normalisedResponse: "Write +4x/3 instead of the gradient.", affectedMarkIds: [A1, A2], marksAwarded: 0, maximumMarks: 0, followThroughAvailable: false, sourceDirectiveIds: [D_A_COMMON], sourceEvidence: [evidence] },
    { id: "Q11_CR_X_ONLY", sourceStatus: "EXPLICITLY_LISTED", category: "PARTIAL_METHOD", errorFamily: "COORDINATE_NOT_COMPLETED", normalisedResponse: "State x=3 rather than the ordered pair.", affectedMarkIds: [B2], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_B_X_ONLY], sourceEvidence: [evidence] },
    { id: "Q11_CR_Y_INTERCEPT", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "WRONG_AXIS_INTERCEPT", normalisedResponse: "State (0,4) instead of the x-axis intercept.", affectedMarkIds: [B1, B2], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_B_WRONG_INTERCEPT], sourceEvidence: [evidence] },
  ],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D_A_FULL, D_A_COMMON, D_B_FULL, D_B_X_ONLY, D_B_WRONG_INTERCEPT] },
  relationship: { partMarkMap: [{ questionPartId: "Q11_a", markIds: [A1, A2] }, { questionPartId: "Q11_b", markIds: [B1, B2] }], subgoalMarkMap: [{ questionSubgoalId: "Q11_S1", markIds: [A1, A2] }, { questionSubgoalId: "Q11_S2", markIds: [B1, B2] }], promptInstructionConsequences: [{ instructionType: "COORDINATES", markingConsequence: "Coordinate brackets are explicitly required for the second part (b) mark.", affectedMarkIds: [B2], sourceEvidence: [evidence] }], informationEvidenceMap: [{ questionInformationId: "Q11_INFO_LINE", usedByMethodIds: [PA, PB], supportsMarkIds: [A1, A2, B1, B2] }], representationEvidenceMap: [], crossPartDependencies: [], errorPropagationGraph: [] },
  sourcePresentation: sourcePresentation([8], "MULTIPART_TABLE_ROW", 2, 5, 7),
  consistency: notReviewedConsistency(comparisonKey("Q11_MARKING_COMPARISON", question.family.familyId, ["alg-a06-gradient-from-equation"], 4, ["MIXED"], ["answer-only credit", "exact vs approximate gradient", "notation", "coordinate brackets", "wrong-axis response"]), [consistencyFeature("part_a_answer_only_treatment", "FULL_CREDIT", "Correct gradient without working explicitly earns 2/2.", [evidence]), consistencyFeature("part_b_answer_only_treatment", "FULL_CREDIT", "Correct coordinate without working explicitly earns 2/2.", [evidence]), consistencyFeature("exact_recurring_decimal_full_credit", true, "Exact recurring-decimal forms of -4/3 are explicitly full-credit.", [evidence]), consistencyFeature("finite_decimal_truncation_partial_credit", true, "A finite -1.3 form is explicitly only 1/2.", [evidence]), consistencyFeature("coordinate_brackets_mark_bearing", true, "The second part (b) mark explicitly requires brackets.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("11"),
} satisfies AnswerCatalogEntry;
