import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q8 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q8";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("8", 6);
const M1 = "N5_MATH_2014_P1_Q8_M1";
const M2 = "N5_MATH_2014_P1_Q8_M2";
const M3 = "N5_MATH_2014_P1_Q8_M3";
const D1 = "N5_MATH_2014_P1_Q8_D_ANSWER_ONLY";
const D2 = "N5_MATH_2014_P1_Q8_D_LATER_INVALID";
const P1 = "N5_MATH_2014_P1_Q8_METHOD_SIMPLIFY_COLLECT_SURDS";

export const N5_MATHS_2014_P1_Q8_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "8", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 3, sourcePages: [6], printedPageLabels: ["Page six"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: { responseTypes: ["EXPRESSION"], canonicalAnswers: [{ id: "N5_MATH_2014_P1_Q8_A1", normalisedAnswer: "9√10", numericValue: null, answerForm: "EXPRESSION", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: ["Final answer must be in simplest surd form for the third mark."], sourceEvidence: [evidence], notes: null }], acceptedEquivalentForms: [], precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile(null, null), requiredContextStatement: false, answerCountRequired: 1, invalidRelatedValues: [], extraAnswerTreatment: "QUESTION_SPECIFIC" },
  sourceDirectives: [
    { id: D1, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "BLOCK", normalisedSummary: "The correct final surd without working receives no marks.", appliesToPartIds: ["Q8_MAIN"], appliesToMarkIds: [M1, M2, M3], appliesToMethodIds: [P1], marksAwarded: 0, maximumMarks: 0, sourceEvidence: [evidence] },
    { id: D2, layer: "QUESTION_NOTE", scope: "MARK", effect: "BLOCK", normalisedSummary: "Incorrect work after a correct result makes the final mark unavailable.", appliesToPartIds: ["Q8_MAIN"], appliesToMarkIds: [M3], appliesToMethodIds: [P1], marksAwarded: null, maximumMarks: null, sourceEvidence: [evidence] },
  ],
  markNodes: [
    markNode(M1, 1, "Q8_MAIN", "PROCESS", "Simplify √40.", "Extract the square factor from the first reducible surd.", ["num-n1-surds"], ["num-n1-1"], ["Q8_S1"], [evidence], { illustrativeEvidence: [{ id: "Q8_M1_E1", normalisedEvidence: "Obtain 2√10 from √40.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M2, 2, "Q8_MAIN", "PROCESS", "Simplify √90.", "Extract the square factor from the second reducible surd.", ["num-n1-surds"], ["num-n1-1"], ["Q8_S1"], [evidence], { illustrativeEvidence: [{ id: "Q8_M2_E1", normalisedEvidence: "Obtain 3√10 from √90.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M3, 3, "Q8_MAIN", "ACCURACY", "State the combined answer in simplest surd form.", "Collect the like surds to the exact final expression.", ["num-n1-surds"], ["num-n1-1"], ["Q8_S2"], [evidence], { illustrativeEvidence: [{ id: "Q8_M3_E1", normalisedEvidence: "State 9√10.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], blockingConditions: ["Subsequent incorrect work blocks this final mark."], methodPathwayIds: [P1], presentationConditions: ["Simplest surd form is required."], sourceDirectiveIds: [D1, D2] }),
  ],
  methodPathways: [{ id: P1, variantId: null, evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q8_P1_S1", order: 1, normalisedStep: "Simplify √40 to 2√10.", linkedQuestionSubgoalIds: ["Q8_S1"], linkedMarkIds: [M1], dependsOnStepIds: [], requiredOperations: ["SIMPLIFY_SURD"], resultingStateSummary: "2√10", sourceEvidence: [evidence] }, { id: "Q8_P1_S2", order: 2, normalisedStep: "Simplify √90 to 3√10.", linkedQuestionSubgoalIds: ["Q8_S1"], linkedMarkIds: [M2], dependsOnStepIds: [], requiredOperations: ["SIMPLIFY_SURD"], resultingStateSummary: "3√10", sourceEvidence: [evidence] }, { id: "Q8_P1_S3", order: 3, normalisedStep: "Combine all like √10 terms.", linkedQuestionSubgoalIds: ["Q8_S2"], linkedMarkIds: [M3], dependsOnStepIds: ["Q8_P1_S1", "Q8_P1_S2"], requiredOperations: ["COLLECT_LIKE_TERMS"], resultingStateSummary: "9√10", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] }],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: workingPolicy(answerOnly("NO_CREDIT", 0, [], [evidence], [D1]), [M1, M2], []),
  presentationPolicy: presentationPolicy([evidence], { simplification: "REQUIRED_FOR_MARK", exactValue: "REQUIRED_FOR_FULL_CREDIT" }),
  visualMarking: emptyVisualMarking(),
  commonResponses: [{ id: "Q8_CR_ANSWER_ONLY", sourceStatus: "EXPLICITLY_LISTED", category: "ANSWER_ONLY", errorFamily: null, normalisedResponse: "State 9√10 with no valid working.", affectedMarkIds: [M1, M2, M3], marksAwarded: 0, maximumMarks: 0, followThroughAvailable: false, sourceDirectiveIds: [D1], sourceEvidence: [evidence] }],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D1, D2] },
  relationship: { partMarkMap: [{ questionPartId: "Q8_MAIN", markIds: [M1, M2, M3] }], subgoalMarkMap: [{ questionSubgoalId: "Q8_S1", markIds: [M1, M2] }, { questionSubgoalId: "Q8_S2", markIds: [M3] }], promptInstructionConsequences: [{ instructionType: "SIMPLEST_FORM", markingConsequence: "The final collection/simplest-form requirement is the third mark and cannot be inferred from an answer-only response.", affectedMarkIds: [M3], sourceEvidence: [evidence] }], informationEvidenceMap: [{ questionInformationId: "Q8_INFO_EXPR", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }], representationEvidenceMap: [], crossPartDependencies: [], errorPropagationGraph: [] },
  sourcePresentation: sourcePresentation([6], "TABLE_ROW", 1, 2, 1),
  consistency: notReviewedConsistency(comparisonKey("Q8_MARKING_COMPARISON", question.family.familyId, ["num-n1-surds"], 3, ["EXPRESSION"], ["answer-only credit", "independent simplification marks", "simplest form", "later invalid work"]), [consistencyFeature("answer_only_treatment", "NO_CREDIT", "Correct final surd without working explicitly earns 0/3.", [evidence]), consistencyFeature("independent_component_process_marks", 2, "Separate marks are awarded for simplifying the two reducible surds.", [evidence]), consistencyFeature("later_invalid_work_can_remove_final_mark", true, "A question-specific note blocks the final mark after subsequent incorrect work.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("8"),
} satisfies AnswerCatalogEntry;
