import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q9 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q9";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("9", 6);
const M1 = "N5_MATH_2014_P1_Q9_M1";
const M2 = "N5_MATH_2014_P1_Q9_M2";
const M3 = "N5_MATH_2014_P1_Q9_M3";
const D1 = "N5_MATH_2014_P1_Q9_D_ANSWER_ONLY";
const D2 = "N5_MATH_2014_P1_Q9_D_DIRECT_PERCENT_ERRORS";
const P1 = "N5_MATH_2014_P1_Q9_METHOD_UNITARY";

export const N5_MATHS_2014_P1_Q9_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "9", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 3, sourcePages: [6], printedPageLabels: ["Page six"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: { responseTypes: ["NUMBER"], canonicalAnswers: [{ id: "N5_MATH_2014_P1_Q9_A1", normalisedAnswer: "600000", numericValue: 600000, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: [], sourceEvidence: [evidence], notes: null }], acceptedEquivalentForms: [], precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile("count", "tickets"), requiredContextStatement: false, answerCountRequired: 1, invalidRelatedValues: ["384000", "576000"], extraAnswerTreatment: "QUESTION_SPECIFIC" },
  sourceDirectives: [
    { id: D1, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "AWARD", normalisedSummary: "The correct whole of 600000 receives all three marks with or without working.", appliesToPartIds: ["Q9_MAIN"], appliesToMarkIds: [M1, M2, M3], appliesToMethodIds: [P1], marksAwarded: 3, maximumMarks: 3, sourceEvidence: [evidence] },
    { id: D2, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "LIMIT", normalisedSummary: "Calculating 80% or 120% of the known 480000 is capped at one mark only when the response also evidences that 80% corresponds to 480000; otherwise it receives zero.", appliesToPartIds: ["Q9_MAIN"], appliesToMarkIds: [M1, M2, M3], appliesToMethodIds: [], marksAwarded: null, maximumMarks: 1, sourceEvidence: [evidence] },
  ],
  markNodes: [
    markNode(M1, 1, "Q9_MAIN", "INTERPRETATION", "Recognise that the known 480000 represents 80% of the whole.", "Interpret the part-to-whole percentage relationship correctly.", ["num-n4-reverse-percentage"], ["num-n4-1"], ["Q9_S1"], [evidence], { illustrativeEvidence: [{ id: "Q9_M1_E1", normalisedEvidence: "State or use 80% = 480000.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1, D2] }),
    markNode(M2, 2, "Q9_MAIN", "PROCESS", "Begin a valid strategy for reversing from 80% to 100%.", "Apply a valid reverse-percentage scaling step.", ["num-n4-reverse-percentage"], ["num-n4-1"], ["Q9_S2"], [evidence], { illustrativeEvidence: [{ id: "Q9_M2_E1", normalisedEvidence: "For example, derive 10% = 60000 or an equivalent valid scaling relation.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1, D2] }),
    markNode(M3, 3, "Q9_MAIN", "ACCURACY", "State the recovered whole.", "Complete the reverse-percentage strategy to 600000.", ["num-n4-reverse-percentage"], ["num-n4-1"], ["Q9_S2"], [evidence], { illustrativeEvidence: [{ id: "Q9_M3_E1", normalisedEvidence: "State 600000.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1, D2] }),
  ],
  methodPathways: [{ id: P1, variantId: "VIA_10_PERCENT", evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q9_P1_S1", order: 1, normalisedStep: "Identify 480000 as 80%.", linkedQuestionSubgoalIds: ["Q9_S1"], linkedMarkIds: [M1], dependsOnStepIds: [], requiredOperations: ["INTERPRET"], resultingStateSummary: "80%=480000", sourceEvidence: [evidence] }, { id: "Q9_P1_S2", order: 2, normalisedStep: "Scale to a convenient percentage such as 10%.", linkedQuestionSubgoalIds: ["Q9_S2"], linkedMarkIds: [M2], dependsOnStepIds: ["Q9_P1_S1"], requiredOperations: ["DIVIDE"], resultingStateSummary: "10%=60000", sourceEvidence: [evidence] }, { id: "Q9_P1_S3", order: 3, normalisedStep: "Scale to 100%.", linkedQuestionSubgoalIds: ["Q9_S2"], linkedMarkIds: [M3], dependsOnStepIds: ["Q9_P1_S2"], requiredOperations: ["MULTIPLY"], resultingStateSummary: "100%=600000", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] }],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: workingPolicy(answerOnly("FULL_CREDIT", 3, [M1, M2, M3], [evidence], [D1]), [], [M1, M2, M3]),
  presentationPolicy: presentationPolicy([evidence]),
  visualMarking: emptyVisualMarking(),
  commonResponses: [
    { id: "Q9_CR_80_OF_KNOWN", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "FORWARD_PERCENT_INSTEAD_OF_REVERSE", normalisedResponse: "Calculate 80% of the known 480000, giving 384000.", affectedMarkIds: [M2, M3], marksAwarded: null, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D2], sourceEvidence: [evidence] },
    { id: "Q9_CR_120_OF_KNOWN", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "ADD_PERCENT_INSTEAD_OF_REVERSE", normalisedResponse: "Calculate 120% of the known 480000, giving 576000.", affectedMarkIds: [M2, M3], marksAwarded: null, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D2], sourceEvidence: [evidence] },
  ],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D1, D2] },
  relationship: { partMarkMap: [{ questionPartId: "Q9_MAIN", markIds: [M1, M2, M3] }], subgoalMarkMap: [{ questionSubgoalId: "Q9_S1", markIds: [M1] }, { questionSubgoalId: "Q9_S2", markIds: [M2, M3] }], promptInstructionConsequences: [], informationEvidenceMap: [{ questionInformationId: "Q9_INFO_PART", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }, { questionInformationId: "Q9_INFO_PCT", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }], representationEvidenceMap: [], crossPartDependencies: [], errorPropagationGraph: [{ sourceMarkIds: [M1], sourceQuestionPartIds: ["Q9_MAIN"], affectedMarkIds: [M2, M3], survivingMarkIds: [M1], conditionSummary: "For the explicitly listed forward-percentage errors, only the relationship mark can survive and only if 80%=480000 is evidenced.", sourceEvidence: [evidence] }] },
  sourcePresentation: sourcePresentation([6], "TABLE_ROW", 1, 2, 2, [{ id: "Q9_MS_CORE", blockRole: "EXPECTED_ANSWER", measurementMethod: "PDF_RENDER", pdfPageNumber: 6, printedPageLabel: "Page six", renderDpi: 300, pageWidthPx: 2481, pageHeightPx: 3508, topPx: 2134, bottomPx: 2570, leftPx: null, rightPx: null, heightPx: 436, widthPx: null, topPt: 512.16, bottomPt: 616.8, leftPt: null, rightPt: null, heightPt: 104.64, widthPt: null, heightMm: 36.91, widthMm: null, notes: "Legacy pilot measurement of the core Q9 marking block; retained as source-layout evidence only." }, { id: "Q9_MS_FULL", blockRole: "FULL_QUESTION_BLOCK", measurementMethod: "PDF_RENDER", pdfPageNumber: 6, printedPageLabel: "Page six", renderDpi: 300, pageWidthPx: 2481, pageHeightPx: 3508, topPx: 2134, bottomPx: 2945, leftPx: null, rightPx: null, heightPx: 811, widthPx: null, topPt: 512.16, bottomPt: 706.8, leftPt: null, rightPt: null, heightPt: 194.64, widthPt: null, heightMm: 68.66, widthMm: null, notes: "Legacy pilot measurement including Q9 notes/common responses; not reusable by a generator." }]),
  consistency: notReviewedConsistency(comparisonKey("Q9_MARKING_COMPARISON", question.family.familyId, ["num-n4-reverse-percentage"], 3, ["NUMBER"], ["answer-only credit", "interpretation mark", "wrong-direction percentage errors", "partial-credit cap"]), [consistencyFeature("answer_only_treatment", "FULL_CREDIT", "600000 with or without working explicitly earns 3/3.", [evidence]), consistencyFeature("relationship_statement_can_survive_wrong_strategy", true, "The explicit wrong-strategy cases can retain one mark when 80%=480000 is evidenced.", [evidence]), consistencyFeature("wrong_forward_percent_strategy_max_marks", 1, "Two specified forward-percentage errors are capped at one mark conditional on relationship evidence.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("9"),
} satisfies AnswerCatalogEntry;
