import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q7 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q7";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, noFollowThrough, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("7", 6);
const M1 = "N5_MATH_2014_P1_Q7_M1";
const M2 = "N5_MATH_2014_P1_Q7_M2";
const D1 = "N5_MATH_2014_P1_Q7_D_ANSWER_ONLY";
const D2 = "N5_MATH_2014_P1_Q7_D_UNSQUARED_NEGATIVE";
const P1 = "N5_MATH_2014_P1_Q7_METHOD_POINT_SUBSTITUTION";

export const N5_MATHS_2014_P1_Q7_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "7", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 2, sourcePages: [6], printedPageLabels: ["Page six"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: { responseTypes: ["NUMBER"], canonicalAnswers: [{ id: "N5_MATH_2014_P1_Q7_A1", normalisedAnswer: "a = 5", numericValue: 5, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: [], sourceEvidence: [evidence], notes: null }], acceptedEquivalentForms: [], precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile(null, null), requiredContextStatement: false, answerCountRequired: 1, invalidRelatedValues: ["a = -15 from treating (-3)^2 as -3 is explicitly 0/2"], extraAnswerTreatment: "QUESTION_SPECIFIC" },
  sourceDirectives: [
    { id: D1, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "AWARD", normalisedSummary: "The correct value of the parameter without working receives both marks.", appliesToPartIds: ["Q7_MAIN"], appliesToMarkIds: [M1, M2], appliesToMethodIds: [P1], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidence] },
    { id: D2, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "BLOCK", normalisedSummary: "Substituting the negative x-value without squaring it and concluding a=-15 receives no marks.", appliesToPartIds: ["Q7_MAIN"], appliesToMarkIds: [M1, M2], appliesToMethodIds: [P1], marksAwarded: 0, maximumMarks: 0, sourceEvidence: [evidence] },
  ],
  markNodes: [
    markNode(M1, 1, "Q7_MAIN", "PROCESS", "Substitute the labelled point (-3,45) into the quadratic family y=ax^2.", "Translate the point-on-graph relationship into an equation for a.", ["alg-a10-quadratic-from-graph"], ["alg-a10-1"], ["Q7_S1"], [evidence], { illustrativeEvidence: [{ id: "Q7_M1_E1", normalisedEvidence: "Form 45 = a(-3)^2 or equivalent.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: ["VIS_Q7"], sourceEvidence: [evidence] }], blockingConditions: ["Treating the square on -3 as absent invalidates this source-specified route."], methodPathwayIds: [P1], sourceDirectiveIds: [D1, D2] }),
    markNode(M2, 2, "Q7_MAIN", "ACCURACY", "Solve the resulting equation for a.", "Obtain the coefficient a=5.", ["alg-a10-quadratic-from-graph"], ["alg-a10-1"], ["Q7_S2"], [evidence], { illustrativeEvidence: [{ id: "Q7_M2_E1", normalisedEvidence: "State a=5.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: true, visualElementIds: [], sourceEvidence: [evidence] }], followThrough: noFollowThrough([evidence], "The explicitly illustrated unsquared-negative route receives 0/2 rather than follow-through."), methodPathwayIds: [P1], sourceDirectiveIds: [D1, D2] }),
  ],
  methodPathways: [{ id: P1, variantId: null, evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q7_P1_S1", order: 1, normalisedStep: "Substitute the graph point into y=ax^2, retaining the square on -3.", linkedQuestionSubgoalIds: ["Q7_S1"], linkedMarkIds: [M1], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE"], resultingStateSummary: "45 = 9a.", sourceEvidence: [evidence] }, { id: "Q7_P1_S2", order: 2, normalisedStep: "Solve the linear equation for a.", linkedQuestionSubgoalIds: ["Q7_S2"], linkedMarkIds: [M2], dependsOnStepIds: ["Q7_P1_S1"], requiredOperations: ["DIVIDE"], resultingStateSummary: "a=5", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] }],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: workingPolicy(answerOnly("FULL_CREDIT", 2, [M1, M2], [evidence], [D1]), [], [M1, M2]),
  presentationPolicy: presentationPolicy([evidence]),
  visualMarking: emptyVisualMarking(),
  commonResponses: [{ id: "Q7_CR_UNSQUARED_NEGATIVE", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "POWER_PRECEDENCE", normalisedResponse: "Use 45=a(-3) and conclude a=-15, omitting the square from the graph equation substitution.", affectedMarkIds: [M1, M2], marksAwarded: 0, maximumMarks: 0, followThroughAvailable: false, sourceDirectiveIds: [D2], sourceEvidence: [evidence] }],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D1, D2] },
  relationship: { partMarkMap: [{ questionPartId: "Q7_MAIN", markIds: [M1, M2] }], subgoalMarkMap: [{ questionSubgoalId: "Q7_S1", markIds: [M1] }, { questionSubgoalId: "Q7_S2", markIds: [M2] }], promptInstructionConsequences: [], informationEvidenceMap: [{ questionInformationId: "Q7_INFO_FUNC", usedByMethodIds: [P1], supportsMarkIds: [M1, M2] }, { questionInformationId: "Q7_INFO_POINT", usedByMethodIds: [P1], supportsMarkIds: [M1, M2] }], representationEvidenceMap: [{ visualElementId: "VIS_Q7", normalisedEvidence: "The labelled point on the supplied parabola supplies the substitution data.", supportsMarkIds: [M1] }], crossPartDependencies: [], errorPropagationGraph: [{ sourceMarkIds: [M1], sourceQuestionPartIds: ["Q7_MAIN"], affectedMarkIds: [M2], survivingMarkIds: [], conditionSummary: "The source explicitly awards 0/2 when the substitution drops the square and leads to -15.", sourceEvidence: [evidence] }] },
  sourcePresentation: sourcePresentation([6], "TABLE_ROW", 1, 2, 1),
  consistency: notReviewedConsistency(comparisonKey("Q7_MARKING_COMPARISON", question.family.familyId, ["alg-a10-quadratic-from-graph"], 2, ["NUMBER"], ["answer-only credit", "follow-through after structural substitution error", "graph-to-equation evidence"]), [consistencyFeature("answer_only_treatment", "FULL_CREDIT", "Correct final coefficient without working explicitly earns 2/2.", [evidence]), consistencyFeature("specified_structural_error_blocks_follow_through", true, "The unsquared-negative error is explicitly awarded 0/2.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("7"),
} satisfies AnswerCatalogEntry;
