import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q13 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q13";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidenceA = msEvidence("13", 9);
const evidenceB = msEvidence("13", 10);
const evidence = [evidenceA, evidenceB];

const A1 = "N5_MATH_2014_P1_Q13_A_M1";
const A2 = "N5_MATH_2014_P1_Q13_A_M2";
const A3 = "N5_MATH_2014_P1_Q13_A_M3";
const A4 = "N5_MATH_2014_P1_Q13_A_M4";
const B1 = "N5_MATH_2014_P1_Q13_B_M1";
const B2 = "N5_MATH_2014_P1_Q13_B_M2";
const B3 = "N5_MATH_2014_P1_Q13_B_M3";

const PA = "N5_MATH_2014_P1_Q13_METHOD_A_ALGEBRA";
const PAT = "N5_MATH_2014_P1_Q13_METHOD_A_TRIAL_SUBSTITUTION";
const PB1 = "N5_MATH_2014_P1_Q13_METHOD_B_TURNING_POINT";
const PB2 = "N5_MATH_2014_P1_Q13_METHOD_B_EVALUATE_AND_VERIFY_MAX";
const PB3 = "N5_MATH_2014_P1_Q13_METHOD_B_DISCRIMINANT";

const D_A_ZERO_REQUIRED = "N5_MATH_2014_P1_Q13_D_A_ZERO_REQUIRED";
const D_A_ZERO_AND_NO_SIX = "N5_MATH_2014_P1_Q13_D_A_ZERO_AND_NO_SIX";
const D_A_ANSWER_ONLY = "N5_MATH_2014_P1_Q13_D_A_ANSWER_ONLY";
const D_A_TRIAL_FULL = "N5_MATH_2014_P1_Q13_D_A_TRIAL_FULL";
const D_A_TRIAL_SIX_SELECTED = "N5_MATH_2014_P1_Q13_D_A_TRIAL_SIX_SELECTED";
const D_A_TRIAL_SIX_ONLY = "N5_MATH_2014_P1_Q13_D_A_TRIAL_SIX_ONLY";
const D_A_TRIAL_TEN = "N5_MATH_2014_P1_Q13_D_A_TRIAL_TEN";
const D_B_COMPARISON = "N5_MATH_2014_P1_Q13_D_B_COMPARISON";
const D_B_64_NO_COMPARE = "N5_MATH_2014_P1_Q13_D_B_64_NO_COMPARE";
const D_B_64_COMPARE = "N5_MATH_2014_P1_Q13_D_B_64_COMPARE";
const D_B_TRIALS_ACROSS_PARTS = "N5_MATH_2014_P1_Q13_D_B_TRIALS_ACROSS_PARTS";
const D_B_SCORED_OUT_TRIALS = "N5_MATH_2014_P1_Q13_D_B_SCORED_OUT_TRIALS";

export const N5_MATHS_2014_P1_Q13_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "13", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 7, sourcePages: [9, 10], printedPageLabels: ["Page nine", "Page ten"], sourceEvidence: evidence, generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: {
    responseTypes: ["MIXED"],
    canonicalAnswers: [
      { id: "N5_MATH_2014_P1_Q13_A1", normalisedAnswer: "6 seconds", numericValue: 6, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: ["The earlier of the two target-height times must be selected."], sourceEvidence: [evidenceA], notes: "Part (a)." },
      { id: "N5_MATH_2014_P1_Q13_B1", normalisedAnswer: "No; the maximum height is 64 metres, below 70 metres.", numericValue: null, answerForm: "PROSE", mathematicallyEquivalentToVariantIds: ["N5_MATH_2014_P1_Q13_B2"], conditionsForAcceptance: ["For the final communication mark in methods 1 and 2, the conclusion must contain an explicit or clearly implied comparison with 70 metres."], sourceEvidence: [evidenceB], notes: "Part (b), maximum-height route." },
    ],
    acceptedEquivalentForms: [{ id: "N5_MATH_2014_P1_Q13_B2", normalisedAnswer: "No; the equation h(t)=70 has no real roots.", numericValue: null, answerForm: "PROSE", mathematicallyEquivalentToVariantIds: ["N5_MATH_2014_P1_Q13_B1"], conditionsForAcceptance: ["Must be supported by valid discriminant evidence under the source's method 3."], sourceEvidence: [evidenceB], notes: "Part (b), discriminant route." }],
    precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile(null, null), requiredContextStatement: true, answerCountRequired: 2, invalidRelatedValues: ["10 seconds is the later solution and does not answer the first-time requirement."], extraAnswerTreatment: "QUESTION_SPECIFIC",
  },
  sourceDirectives: [
    { id: D_A_ZERO_REQUIRED, layer: "QUESTION_NOTE", scope: "PART", effect: "REQUIRE", normalisedSummary: "For the algebraic route, an explicit equation equal to zero must appear before the solving/factorisation stage; omitting that zero-equation step limits an otherwise successful route to three marks.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A2], appliesToMethodIds: [PA], marksAwarded: 3, maximumMarks: 3, sourceEvidence: [evidenceA] },
    { id: D_A_ZERO_AND_NO_SIX, layer: "QUESTION_NOTE", scope: "PART", effect: "LIMIT", normalisedSummary: "If the zero-equation step is omitted and the required first time 6 is also not explicitly stated, the source awards only one mark.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A2, A3, A4], appliesToMethodIds: [PA], marksAwarded: 1, maximumMarks: 1, sourceEvidence: [evidenceA] },
    { id: D_A_ANSWER_ONLY, layer: "QUESTION_NOTE", scope: "PART", effect: "BLOCK", normalisedSummary: "The answer 6 without working receives no marks.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A1, A2, A3, A4], appliesToMethodIds: [], marksAwarded: 0, maximumMarks: 0, sourceEvidence: [evidenceA] },
    { id: D_A_TRIAL_FULL, layer: "ALTERNATIVE_METHOD", scope: "PART", effect: "AWARD", normalisedSummary: "Under the substitution/trial route, verifying both t=6 and t=10 as height-60 times and selecting 6 receives all four marks.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A1, A2, A3, A4], appliesToMethodIds: [PAT], marksAwarded: 4, maximumMarks: 4, sourceEvidence: [evidenceA] },
    { id: D_A_TRIAL_SIX_SELECTED, layer: "ALTERNATIVE_METHOD", scope: "PART", effect: "AWARD", normalisedSummary: "Verifying h(6)=60 and then selecting 6, without also establishing the second solution, receives two marks.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A1, A4], appliesToMethodIds: [PAT], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidenceA] },
    { id: D_A_TRIAL_SIX_ONLY, layer: "ALTERNATIVE_METHOD", scope: "PART", effect: "AWARD", normalisedSummary: "Verifying h(6)=60 without explicitly selecting it as the requested answer receives one mark.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A1], appliesToMethodIds: [PAT], marksAwarded: 1, maximumMarks: 1, sourceEvidence: [evidenceA] },
    { id: D_A_TRIAL_TEN, layer: "ALTERNATIVE_METHOD", scope: "PART", effect: "AWARD", normalisedSummary: "Verifying h(10)=60 and selecting 10 receives one mark because it identifies a valid target-height time but not the requested first time.", appliesToPartIds: ["Q13_a"], appliesToMarkIds: [A1], appliesToMethodIds: [PAT], marksAwarded: 1, maximumMarks: 1, sourceEvidence: [evidenceA] },
    { id: D_B_COMPARISON, layer: "QUESTION_NOTE", scope: "MARK", effect: "REQUIRE", normalisedSummary: "For part (b) methods 1 and 2, the final communication mark requires a valid comparison with 70 metres, either explicit or clearly implied by wording such as an upper-limit statement.", appliesToPartIds: ["Q13_b"], appliesToMarkIds: [B3], appliesToMethodIds: [PB1, PB2], marksAwarded: null, maximumMarks: null, sourceEvidence: [evidenceB] },
    { id: D_B_64_NO_COMPARE, layer: "QUESTION_NOTE", scope: "PART", effect: "LIMIT", normalisedSummary: "A negative conclusion stating that the rocket reaches 64 metres but not making the required comparison receives two marks.", appliesToPartIds: ["Q13_b"], appliesToMarkIds: [B3], appliesToMethodIds: [PB1, PB2], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidenceB] },
    { id: D_B_64_COMPARE, layer: "QUESTION_NOTE", scope: "PART", effect: "AWARD", normalisedSummary: "A negative conclusion supported by 64 metres together with a valid 64<70 comparison receives all three marks.", appliesToPartIds: ["Q13_b"], appliesToMarkIds: [B1, B2, B3], appliesToMethodIds: [PB1, PB2], marksAwarded: 3, maximumMarks: 3, sourceEvidence: [evidenceB] },
    { id: D_B_TRIALS_ACROSS_PARTS, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "ACCEPT", normalisedSummary: "For a trial-and-improvement approach, relevant trials appearing in either part (a) or part (b) may be used as evidence.", appliesToPartIds: ["Q13_a", "Q13_b"], appliesToMarkIds: [B1, B2], appliesToMethodIds: [PB2], marksAwarded: null, maximumMarks: null, sourceEvidence: [evidenceB] },
    { id: D_B_SCORED_OUT_TRIALS, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "ACCEPT", normalisedSummary: "Scored-out trial values can count as evidence of rejected trials in a trial-and-improvement approach.", appliesToPartIds: ["Q13_a", "Q13_b"], appliesToMarkIds: [B2], appliesToMethodIds: [PB2], marksAwarded: null, maximumMarks: null, sourceEvidence: [evidenceB] },
  ],
  markNodes: [
    markNode(A1, 1, "Q13_a", "PROCESS", "Construct an equation for the first target height.", "Translate h=60 into an equation in t.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1"], ["Q13_S1"], [evidenceA], { illustrativeEvidence: [{ id: "Q13_A_M1_E1", normalisedEvidence: "Set 16t - t^2 equal to 60.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidenceA] }], methodPathwayIds: [PA, PAT], sourceDirectiveIds: [D_A_ANSWER_ONLY, D_A_TRIAL_FULL, D_A_TRIAL_SIX_SELECTED, D_A_TRIAL_SIX_ONLY, D_A_TRIAL_TEN] }),
    markNode(A2, 2, "Q13_a", "PROCESS", "Rearrange the target-height equation and explicitly equate it to zero.", "Create the zero-form quadratic required for the factorisation route.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1"], ["Q13_S1"], [evidenceA], { illustrativeEvidence: [{ id: "Q13_A_M2_E1", normalisedEvidence: "For example, write t^2 - 16t + 60 = 0.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidenceA] }], pathwaySpecificRequirements: [{ methodPathwayId: PA, normalisedRequirement: "The zero-equation stage must be explicit before solving.", sourceEvidence: [evidenceA] }], methodPathwayIds: [PA], sourceDirectiveIds: [D_A_ZERO_REQUIRED, D_A_ZERO_AND_NO_SIX, D_A_ANSWER_ONLY] }),
    markNode(A3, 3, "Q13_a", "PROCESS", "Factorise the quadratic correctly.", "Expose the two target-height times through exact factorisation.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1"], ["Q13_S2"], [evidenceA], { illustrativeEvidence: [{ id: "Q13_A_M3_E1", normalisedEvidence: "Obtain factors (t-6)(t-10).", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidenceA] }], methodPathwayIds: [PA], sourceDirectiveIds: [D_A_ZERO_REQUIRED, D_A_ZERO_AND_NO_SIX, D_A_ANSWER_ONLY] }),
    markNode(A4, 4, "Q13_a", "SELECTION", "Solve the equation and select the required first value.", "Choose 6 seconds rather than the later 10-second solution.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1"], ["Q13_S2"], [evidenceA], { secondaryTypes: ["ACCURACY", "INTERPRETATION"], illustrativeEvidence: [{ id: "Q13_A_M4_E1", normalisedEvidence: "State t=6 as the first time.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidenceA] }], eligibilityConditions: ["The selected value must satisfy the first-occurrence requirement."], methodPathwayIds: [PA, PAT], sourceDirectiveIds: [D_A_ANSWER_ONLY, D_A_TRIAL_FULL, D_A_TRIAL_SIX_SELECTED, D_A_TRIAL_TEN] }),
    markNode(B1, 1, "Q13_b", "PROCESS", "Establish the first-stage evidence for a valid method of deciding whether 70 metres is attainable.", "Begin a valid maximum-height or discriminant argument.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1", "alg-a3-1", "alg-a14-1"], ["Q13_S3"], [evidenceB], { pathwaySpecificRequirements: [
      { methodPathwayId: PB1, normalisedRequirement: "Identify the turning-point time t=8, stated or implied.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB2, normalisedRequirement: "Calculate h(8)=64.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB3, normalisedRequirement: "Show evidence of applying the discriminant to the equation formed by setting the model equal to 70.", sourceEvidence: [evidenceB] },
    ], methodPathwayIds: [PB1, PB2, PB3], sourceDirectiveIds: [D_B_TRIALS_ACROSS_PARTS] }),
    markNode(B2, 2, "Q13_b", "JUSTIFICATION", "Establish decisive mathematical evidence under the chosen valid method.", "Show that 64 is the maximum or that the height-70 equation has no real roots.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1", "alg-a3-1", "alg-a14-1"], ["Q13_S3"], [evidenceB], { pathwaySpecificRequirements: [
      { methodPathwayId: PB1, normalisedRequirement: "Calculate the maximum height as 64.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB2, normalisedRequirement: "Demonstrate that h(8)=64 is a maximum, for example using neighbouring values.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB3, normalisedRequirement: "Demonstrate that the discriminant is negative.", sourceEvidence: [evidenceB] },
    ], methodPathwayIds: [PB1, PB2, PB3], sourceDirectiveIds: [D_B_TRIALS_ACROSS_PARTS, D_B_SCORED_OUT_TRIALS] }),
    markNode(B3, 3, "Q13_b", "CONCLUSION", "Communicate the supported conclusion.", "Translate the mathematical evidence into a justified statement that 70 metres is not attained.", ["alg-a13-quadratic-equations-factorise"], ["alg-a13-1", "alg-a14-1"], ["Q13_S4"], [evidenceB], { pathwaySpecificRequirements: [
      { methodPathwayId: PB1, normalisedRequirement: "State a negative conclusion with a valid explicit or implied comparison between the 64-metre maximum and 70 metres.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB2, normalisedRequirement: "State a negative conclusion with a valid explicit or implied comparison between the 64-metre maximum and 70 metres.", sourceEvidence: [evidenceB] },
      { methodPathwayId: PB3, normalisedRequirement: "State a negative conclusion justified by the absence of real roots for height 70.", sourceEvidence: [evidenceB] },
    ], presentationConditions: ["Methods 1 and 2 require a valid comparison, explicit or implied, for this final mark."], methodPathwayIds: [PB1, PB2, PB3], sourceDirectiveIds: [D_B_COMPARISON, D_B_64_NO_COMPARE, D_B_64_COMPARE] }),
  ],
  methodPathways: [
    { id: PA, variantId: "FACTORISE_TARGET_EQUATION", evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q13_PA_S1", order: 1, normalisedStep: "Set the height model equal to 60.", linkedQuestionSubgoalIds: ["Q13_S1"], linkedMarkIds: [A1], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE"], resultingStateSummary: "16t-t^2=60", sourceEvidence: [evidenceA] }, { id: "Q13_PA_S2", order: 2, normalisedStep: "Rearrange explicitly to zero form.", linkedQuestionSubgoalIds: ["Q13_S1"], linkedMarkIds: [A2], dependsOnStepIds: ["Q13_PA_S1"], requiredOperations: ["REARRANGE"], resultingStateSummary: "t^2-16t+60=0", sourceEvidence: [evidenceA] }, { id: "Q13_PA_S3", order: 3, normalisedStep: "Factorise into roots 6 and 10.", linkedQuestionSubgoalIds: ["Q13_S2"], linkedMarkIds: [A3], dependsOnStepIds: ["Q13_PA_S2"], requiredOperations: ["FACTORISE"], resultingStateSummary: "(t-6)(t-10)=0", sourceEvidence: [evidenceA] }, { id: "Q13_PA_S4", order: 4, normalisedStep: "Select the earlier solution t=6.", linkedQuestionSubgoalIds: ["Q13_S2"], linkedMarkIds: [A4], dependsOnStepIds: ["Q13_PA_S3"], requiredOperations: ["SOLVE", "SELECT"], resultingStateSummary: "6 seconds", sourceEvidence: [evidenceA] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [PAT], materiallyDistinctFromMethodIds: [PAT], excludedMethodReasons: [], sourceEvidence: [evidenceA] },
    { id: PAT, variantId: "DIRECT_SUBSTITUTION_TRIALS", evidenceRole: "FULL_CREDIT_ALTERNATIVE", supportsFullCredit: true, applicabilityConditions: ["Use direct evaluation/trial evidence rather than forming and factorising the zero-form quadratic."], steps: [{ id: "Q13_PAT_S1", order: 1, normalisedStep: "Verify one or both target-height times by substitution into h(t).", linkedQuestionSubgoalIds: ["Q13_S1", "Q13_S2"], linkedMarkIds: [A1, A4], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE", "EVALUATE"], resultingStateSummary: "Source-defined totals depend on which trial values are established and whether 6 is selected.", sourceEvidence: [evidenceA] }], markMappingComplete: false, sourceTotalAwardRules: [D_A_TRIAL_FULL, D_A_TRIAL_SIX_SELECTED, D_A_TRIAL_SIX_ONLY, D_A_TRIAL_TEN], mathematicallyEquivalentMethodIds: [PA], materiallyDistinctFromMethodIds: [PA], excludedMethodReasons: [], sourceEvidence: [evidenceA] },
    { id: PB1, variantId: "TURNING_POINT", evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q13_PB1_S1", order: 1, normalisedStep: "Determine that the turning point occurs at t=8.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B1], dependsOnStepIds: [], requiredOperations: ["FIND_TURNING_POINT"], resultingStateSummary: "t=8", sourceEvidence: [evidenceB] }, { id: "Q13_PB1_S2", order: 2, normalisedStep: "Evaluate the height at t=8.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B2], dependsOnStepIds: ["Q13_PB1_S1"], requiredOperations: ["SUBSTITUTE", "CALCULATE"], resultingStateSummary: "maximum height=64", sourceEvidence: [evidenceB] }, { id: "Q13_PB1_S3", order: 3, normalisedStep: "Compare the maximum with 70 and communicate the negative conclusion.", linkedQuestionSubgoalIds: ["Q13_S4"], linkedMarkIds: [B3], dependsOnStepIds: ["Q13_PB1_S2"], requiredOperations: ["COMPARE", "CONCLUDE"], resultingStateSummary: "No; 64<70.", sourceEvidence: [evidenceB] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [PB2, PB3], materiallyDistinctFromMethodIds: [PB2, PB3], excludedMethodReasons: [], sourceEvidence: [evidenceB] },
    { id: PB2, variantId: "EVALUATE_AND_VERIFY_MAXIMUM", evidenceRole: "ILLUSTRATIVE_ALTERNATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q13_PB2_S1", order: 1, normalisedStep: "Calculate h(8)=64.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B1], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE", "CALCULATE"], resultingStateSummary: "64", sourceEvidence: [evidenceB] }, { id: "Q13_PB2_S2", order: 2, normalisedStep: "Demonstrate that 64 is the maximum, for example using values on both sides of t=8.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B2], dependsOnStepIds: ["Q13_PB2_S1"], requiredOperations: ["VERIFY_MAXIMUM"], resultingStateSummary: "Neighbouring heights are lower than 64.", sourceEvidence: [evidenceB] }, { id: "Q13_PB2_S3", order: 3, normalisedStep: "Compare 64 with 70 and communicate the negative conclusion.", linkedQuestionSubgoalIds: ["Q13_S4"], linkedMarkIds: [B3], dependsOnStepIds: ["Q13_PB2_S2"], requiredOperations: ["COMPARE", "CONCLUDE"], resultingStateSummary: "No; 64<70.", sourceEvidence: [evidenceB] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [PB1, PB3], materiallyDistinctFromMethodIds: [PB1, PB3], excludedMethodReasons: [], sourceEvidence: [evidenceB] },
    { id: PB3, variantId: "DISCRIMINANT", evidenceRole: "ILLUSTRATIVE_ALTERNATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q13_PB3_S1", order: 1, normalisedStep: "Set the model equal to 70 and use discriminant evidence.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B1], dependsOnStepIds: [], requiredOperations: ["FORM_EQUATION", "DISCRIMINANT"], resultingStateSummary: "Discriminant expression for the height-70 quadratic.", sourceEvidence: [evidenceB] }, { id: "Q13_PB3_S2", order: 2, normalisedStep: "Show the discriminant is negative.", linkedQuestionSubgoalIds: ["Q13_S3"], linkedMarkIds: [B2], dependsOnStepIds: ["Q13_PB3_S1"], requiredOperations: ["CALCULATE", "COMPARE_ZERO"], resultingStateSummary: "No real roots.", sourceEvidence: [evidenceB] }, { id: "Q13_PB3_S3", order: 3, normalisedStep: "Conclude that the target height is unattainable because the equation has no real solutions.", linkedQuestionSubgoalIds: ["Q13_S4"], linkedMarkIds: [B3], dependsOnStepIds: ["Q13_PB3_S2"], requiredOperations: ["CONCLUDE"], resultingStateSummary: "No real time reaches 70 metres.", sourceEvidence: [evidenceB] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [PB1, PB2], materiallyDistinctFromMethodIds: [PB1, PB2], excludedMethodReasons: [], sourceEvidence: [evidenceB] },
  ],
  methodEquivalence: {
    equivalentMethodGroups: [
      { id: "Q13_A_EQUIV", methodIds: [PA, PAT], equivalenceReason: "Both routes are explicitly source-supported ways to answer the first-time target-height task, although the trial route uses source-defined total-award rules rather than the printed algebraic bullet mapping.", sourceEvidence: [evidenceA] },
      { id: "Q13_B_EQUIV", methodIds: [PB1, PB2, PB3], equivalenceReason: "The source explicitly lists all three as full-credit methods for proving that 70 metres is unattainable.", sourceEvidence: [evidenceB] },
    ],
    methodEligibilityRules: [],
  },
  workingPolicy: {
    ...workingPolicy(answerOnly("NOT_STATED", null, [], evidence, [], [], "Part-specific answer-only treatment differs; use the explicit part profiles."), [A1, A2, A3, B1, B2], []),
    partSpecificAnswerOnly: [
      { questionPartId: "Q13_a", profile: answerOnly("NO_CREDIT", 0, [], [evidenceA], [D_A_ANSWER_ONLY]) },
      { questionPartId: "Q13_b", profile: answerOnly("NOT_STATED", null, [], [evidenceB], [], [], "The source gives explicit conclusion examples and method requirements but does not label a general correct-answer-without-working rule for part (b).") },
    ],
    laterPartCanSupplyEvidence: true,
    earlierPartCanSupplyEvidence: true,
  },
  presentationPolicy: presentationPolicy(evidence, { contextualWording: "REQUIRED_FOR_MARK", otherConditions: ["Part (a) algebraic route requires an explicit zero-equation stage for full credit.", "Part (b) methods 1 and 2 require an explicit or implied comparison with 70 for the conclusion mark."] }),
  visualMarking: emptyVisualMarking(),
  commonResponses: [
    { id: "Q13_CR_A_NO_ZERO", sourceStatus: "EXPLICITLY_LISTED", category: "PARTIAL_METHOD", errorFamily: "ZERO_EQUATION_OMITTED", normalisedResponse: "Proceed from a non-zero-form quadratic expression directly to factors/solution without explicitly equating to zero, while still stating 6.", affectedMarkIds: [A2], marksAwarded: 3, maximumMarks: 3, followThroughAvailable: false, sourceDirectiveIds: [D_A_ZERO_REQUIRED], sourceEvidence: [evidenceA] },
    { id: "Q13_CR_A_ANSWER_ONLY", sourceStatus: "EXPLICITLY_LISTED", category: "ANSWER_ONLY", errorFamily: null, normalisedResponse: "State 6 with no working.", affectedMarkIds: [A1, A2, A3, A4], marksAwarded: 0, maximumMarks: 0, followThroughAvailable: false, sourceDirectiveIds: [D_A_ANSWER_ONLY], sourceEvidence: [evidenceA] },
    { id: "Q13_CR_A_TRIAL_BOTH", sourceStatus: "EXPLICITLY_LISTED", category: "VALID_ALTERNATIVE", errorFamily: null, normalisedResponse: "Verify h(6)=60 and h(10)=60, then select 6.", affectedMarkIds: [], marksAwarded: 4, maximumMarks: 4, followThroughAvailable: false, sourceDirectiveIds: [D_A_TRIAL_FULL], sourceEvidence: [evidenceA] },
    { id: "Q13_CR_A_TRIAL_SIX", sourceStatus: "EXPLICITLY_LISTED", category: "PARTIAL_METHOD", errorFamily: null, normalisedResponse: "Verify h(6)=60 and state 6 without establishing the second solution.", affectedMarkIds: [], marksAwarded: 2, maximumMarks: 2, followThroughAvailable: false, sourceDirectiveIds: [D_A_TRIAL_SIX_SELECTED], sourceEvidence: [evidenceA] },
    { id: "Q13_CR_A_TRIAL_TEN", sourceStatus: "EXPLICITLY_LISTED", category: "PARTIAL_METHOD", errorFamily: "WRONG_SOLUTION_SELECTION", normalisedResponse: "Verify h(10)=60 and state 10.", affectedMarkIds: [A4], marksAwarded: 1, maximumMarks: 1, followThroughAvailable: false, sourceDirectiveIds: [D_A_TRIAL_TEN], sourceEvidence: [evidenceA] },
    { id: "Q13_CR_B_64_NO_COMPARE", sourceStatus: "EXPLICITLY_LISTED", category: "PARTIAL_METHOD", errorFamily: "CONCLUSION_COMPARISON_MISSING", normalisedResponse: "Conclude no and state that the rocket reaches 64 metres, without a valid explicit/implied comparison to 70.", affectedMarkIds: [B3], marksAwarded: 2, maximumMarks: 2, followThroughAvailable: false, sourceDirectiveIds: [D_B_64_NO_COMPARE], sourceEvidence: [evidenceB] },
    { id: "Q13_CR_B_64_WITH_COMPARE", sourceStatus: "EXPLICITLY_LISTED", category: "VALID_ALTERNATIVE", errorFamily: null, normalisedResponse: "Conclude no, state 64 metres and explicitly compare 64<70.", affectedMarkIds: [], marksAwarded: 3, maximumMarks: 3, followThroughAvailable: false, sourceDirectiveIds: [D_B_64_COMPARE], sourceEvidence: [evidenceB] },
  ],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D_A_ZERO_REQUIRED, D_A_ZERO_AND_NO_SIX, D_A_ANSWER_ONLY, D_A_TRIAL_FULL, D_A_TRIAL_SIX_SELECTED, D_A_TRIAL_SIX_ONLY, D_A_TRIAL_TEN, D_B_COMPARISON, D_B_64_NO_COMPARE, D_B_64_COMPARE, D_B_TRIALS_ACROSS_PARTS, D_B_SCORED_OUT_TRIALS] },
  relationship: {
    partMarkMap: [{ questionPartId: "Q13_a", markIds: [A1, A2, A3, A4] }, { questionPartId: "Q13_b", markIds: [B1, B2, B3] }],
    subgoalMarkMap: [{ questionSubgoalId: "Q13_S1", markIds: [A1, A2] }, { questionSubgoalId: "Q13_S2", markIds: [A3, A4] }, { questionSubgoalId: "Q13_S3", markIds: [B1, B2] }, { questionSubgoalId: "Q13_S4", markIds: [B3] }],
    promptInstructionConsequences: [
      { instructionType: "FIRST_TIME", markingConsequence: "Part (a) final selection must choose 6 rather than the later valid solution 10.", affectedMarkIds: [A4], sourceEvidence: [evidenceA] },
      { instructionType: "JUSTIFY", markingConsequence: "Part (b) reserves the final mark for a mathematically supported contextual conclusion; methods 1 and 2 require a valid comparison with 70.", affectedMarkIds: [B3], sourceEvidence: [evidenceB] },
    ],
    informationEvidenceMap: [{ questionInformationId: "Q13_INFO_MODEL", usedByMethodIds: [PA, PAT, PB1, PB2, PB3], supportsMarkIds: [A1, A2, A3, A4, B1, B2, B3] }, { questionInformationId: "Q13_INFO_TARGET60", usedByMethodIds: [PA, PAT], supportsMarkIds: [A1, A2, A3, A4] }, { questionInformationId: "Q13_INFO_FIRST", usedByMethodIds: [PA, PAT], supportsMarkIds: [A4] }, { questionInformationId: "Q13_INFO_TARGET70", usedByMethodIds: [PB1, PB2, PB3], supportsMarkIds: [B1, B2, B3] }],
    representationEvidenceMap: [],
    crossPartDependencies: ["Part (b) trial-and-improvement evidence may explicitly reuse trials appearing in part (a)."],
    errorPropagationGraph: [],
  },
  sourcePresentation: sourcePresentation([9, 10], "MULTI_PAGE", 5, 6, 7),
  consistency: notReviewedConsistency(comparisonKey("Q13_MARKING_COMPARISON", question.family.familyId, ["alg-a13-quadratic-equations-factorise", "alg-a03-complete-the-square", "alg-a14-discriminant"], 7, ["MIXED"], ["answer-only credit", "method-specific mark mapping", "alternative-method total awards", "solution selection", "conclusion comparison", "cross-part evidence", "scored-out evidence"]), [
    consistencyFeature("part_a_answer_only_treatment", "NO_CREDIT", "The correct first time without working explicitly earns 0/4.", [evidenceA]),
    consistencyFeature("part_a_zero_equation_explicitly_mark_bearing", true, "An explicit zero-equation stage is required for full credit in the algebraic route.", [evidenceA]),
    consistencyFeature("part_a_alternative_trial_route_uses_total_awards", true, "The source assigns explicit total marks to several trial/substitution response patterns rather than mapping them directly to the printed algebraic bullets.", [evidenceA]),
    consistencyFeature("part_b_explicit_full_credit_method_count", 3, "Three distinct full-credit methods are printed for the attainability decision.", [evidenceB]),
    consistencyFeature("part_b_conclusion_comparison_mark_bearing_methods_1_2", true, "Methods 1 and 2 require a valid explicit or implied comparison with 70 for the final mark.", [evidenceB]),
    consistencyFeature("cross_part_trial_evidence_allowed", true, "Trial-and-improvement evidence may be gathered across both parts.", [evidenceB]),
    consistencyFeature("scored_out_rejected_trials_can_count", true, "The source explicitly permits scored-out rejected trials as evidence in the trial-and-improvement context.", [evidenceB]),
  ]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("13"),
} satisfies AnswerCatalogEntry;
