import type { AnswerCatalogEntry } from "../../AnswerCatalogTypes";
import { N5_MATHS_2014_P1_Q5 as question } from "../../../01_QuestionCatalog/2014/Paper1/N5_Maths_2014_P1_Q5";
import { GENERAL_2014_RULE_IDS, answerIntegrity, answerOnly, answerReviewInProgress, comparisonKey, consistencyFeature, emptyMethodEquivalence, emptyVisualMarking, generationNotReviewed, markNode, msEvidence, notReviewedConsistency, presentationPolicy, sourcePresentation, unitProfile, workingPolicy } from "../../AnswerCatalogHelpers";

const evidence = msEvidence("5", 4);
const M1 = "N5_MATH_2014_P1_Q5_M1";
const M2 = "N5_MATH_2014_P1_Q5_M2";
const M3 = "N5_MATH_2014_P1_Q5_M3";
const D1 = "N5_MATH_2014_P1_Q5_D_SINE_OF_SUPPLIED_VALUES";
const P1 = "N5_MATH_2014_P1_Q5_METHOD_SINE_RULE";

export const N5_MATHS_2014_P1_Q5_MS = {
  identity: { id: question.identity.answerCatalogId, schemaVersion: "N5_CATALOG_V2", sourceQuestionId: question.identity.id, courseId: question.identity.courseId, paperContextId: question.identity.paperContextId, year: 2014, paper: "P1", questionNumber: "5", questionFamilyId: question.family.familyId },
  sourceContext: { sourceDocumentId: "N5_MATH_2014_MS", totalMarks: 3, sourcePages: [4], printedPageLabels: ["Page four"], sourceEvidence: [evidence], generalMarkingPolicyId: "N5_MATH_2014_GENERAL_MARKING_POLICY" },
  expectedResponse: {
    responseTypes: ["NUMBER"],
    canonicalAnswers: [{ id: "N5_MATH_2014_P1_Q5_A1", normalisedAnswer: "8 cm", numericValue: 8, answerForm: "NUMBER", mathematicallyEquivalentToVariantIds: [], conditionsForAcceptance: [], sourceEvidence: [evidence], notes: "The expected-answer column includes the centimetre unit; no separate source note states a unit penalty." }],
    acceptedEquivalentForms: [], precisionType: "NONE", precisionValue: null, acceptedRange: null, units: unitProfile("length", "cm"), requiredContextStatement: false, answerCountRequired: 1, invalidRelatedValues: [], extraAnswerTreatment: "QUESTION_SPECIFIC",
  },
  sourceDirectives: [
    { id: D1, layer: "QUESTION_NOTE", scope: "QUESTION", effect: "AWARD", normalisedSummary: "Two illustrated responses incorrectly apply sine again to the supplied sine values; despite losing the substitution mark, a valid rearrangement/calculation structure leading to 8 receives the final two marks.", appliesToPartIds: ["Q5_MAIN"], appliesToMarkIds: [M1, M2, M3], appliesToMethodIds: [P1], marksAwarded: 2, maximumMarks: 2, sourceEvidence: [evidence] },
  ],
  markNodes: [
    markNode(M1, 1, "Q5_MAIN", "PROCESS", "Substitute the supplied side and sine values correctly into the sine rule.", "Set up the correct opposite-side/sine-value proportion.", ["trig-t04-sine-rule"], ["trig-t4-1"], ["Q5_S1"], [evidence], { illustrativeEvidence: [{ id: "Q5_M1_E1", normalisedEvidence: "Set LM/0.4 equal to 18/0.9 or an equivalent correctly paired sine-rule relationship.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M2, 2, "Q5_MAIN", "PROCESS", "Demonstrate how to solve the proportion for the unknown side.", "Rearrange the sine-rule proportion appropriately.", ["trig-t04-sine-rule"], ["trig-t4-1"], ["Q5_S2"], [evidence], { illustrativeEvidence: [{ id: "Q5_M2_E1", normalisedEvidence: "Rearrange to multiply 18 by the numerator sine value and divide by the denominator sine value.", acceptedLocations: ["WORKING"], mayBeImpliedByLaterWork: true, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], dependencies: [{ type: "REQUIRES_VALID_METHOD", relatedMarkIds: [], relatedQuestionPartIds: ["Q5_MAIN"], conditionSummary: "The solving structure can receive credit even when the first substitution mark is lost in the explicit source-note cases.", sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
    markNode(M3, 3, "Q5_MAIN", "ACCURACY", "Carry out the calculation correctly.", "Obtain the side length 8 from the chosen valid/recoverable strategy.", ["trig-t04-sine-rule"], ["trig-t4-1"], ["Q5_S2"], [evidence], { illustrativeEvidence: [{ id: "Q5_M3_E1", normalisedEvidence: "Obtain LM = 8.", acceptedLocations: ["WORKING", "FINAL_ANSWER"], mayBeImpliedByLaterWork: false, mayBeImpliedByCorrectFinalAnswer: false, visualElementIds: [], sourceEvidence: [evidence] }], methodPathwayIds: [P1], sourceDirectiveIds: [D1] }),
  ],
  methodPathways: [{ id: P1, variantId: null, evidenceRole: "PRIMARY_ILLUSTRATIVE", supportsFullCredit: true, applicabilityConditions: [], steps: [{ id: "Q5_P1_S1", order: 1, normalisedStep: "Pair the unknown side with 0.4 and the known 18 cm side with 0.9 in the sine-rule proportion.", linkedQuestionSubgoalIds: ["Q5_S1"], linkedMarkIds: [M1], dependsOnStepIds: [], requiredOperations: ["SUBSTITUTE"], resultingStateSummary: "LM/0.4 = 18/0.9 or equivalent.", sourceEvidence: [evidence] }, { id: "Q5_P1_S2", order: 2, normalisedStep: "Rearrange the proportion for LM.", linkedQuestionSubgoalIds: ["Q5_S2"], linkedMarkIds: [M2], dependsOnStepIds: ["Q5_P1_S1"], requiredOperations: ["REARRANGE"], resultingStateSummary: "LM = 18×0.4/0.9.", sourceEvidence: [evidence] }, { id: "Q5_P1_S3", order: 3, normalisedStep: "Evaluate the non-calculator arithmetic.", linkedQuestionSubgoalIds: ["Q5_S2"], linkedMarkIds: [M3], dependsOnStepIds: ["Q5_P1_S2"], requiredOperations: ["CALCULATE"], resultingStateSummary: "LM = 8.", sourceEvidence: [evidence] }], markMappingComplete: true, sourceTotalAwardRules: [], mathematicallyEquivalentMethodIds: [], materiallyDistinctFromMethodIds: [], excludedMethodReasons: [], sourceEvidence: [evidence] }],
  methodEquivalence: emptyMethodEquivalence(),
  workingPolicy: workingPolicy(answerOnly("NOT_STATED", null, [], [evidence], [], [], "The detailed instructions do not give a special answer-only award for this Question."), [M1, M2], []),
  presentationPolicy: presentationPolicy([evidence], { units: "NOT_STATED" }),
  visualMarking: emptyVisualMarking(),
  commonResponses: [{ id: "Q5_CR_SINE_AGAIN", sourceStatus: "EXPLICITLY_LISTED", category: "COMMON_ERROR", errorFamily: "MISREAD_SUPPLIED_SINE_VALUES", normalisedResponse: "Treat the supplied 0.4 and 0.9 as angles and apply sine to them again before continuing the same proportion strategy.", affectedMarkIds: [M1], marksAwarded: 2, maximumMarks: 2, followThroughAvailable: true, sourceDirectiveIds: [D1], sourceEvidence: [evidence] }],
  generalPolicy: { policyId: "N5_MATH_2014_GENERAL_MARKING_POLICY", relevantRuleIds: [...GENERAL_2014_RULE_IDS], questionSpecificOverrides: [D1] },
  relationship: { partMarkMap: [{ questionPartId: "Q5_MAIN", markIds: [M1, M2, M3] }], subgoalMarkMap: [{ questionSubgoalId: "Q5_S1", markIds: [M1] }, { questionSubgoalId: "Q5_S2", markIds: [M2, M3] }], promptInstructionConsequences: [], informationEvidenceMap: [{ questionInformationId: "Q5_INFO_KM", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }, { questionInformationId: "Q5_INFO_SINK", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }, { questionInformationId: "Q5_INFO_SINL", usedByMethodIds: [P1], supportsMarkIds: [M1, M2, M3] }], representationEvidenceMap: [], crossPartDependencies: [], errorPropagationGraph: [{ sourceMarkIds: [M1], sourceQuestionPartIds: ["Q5_MAIN"], affectedMarkIds: [M2, M3], survivingMarkIds: [M2, M3], conditionSummary: "The explicit source examples show M2 and M3 surviving a specific invalid first-stage treatment of supplied sine values when the later solving/calculation structure remains valid.", sourceEvidence: [evidence] }] },
  sourcePresentation: sourcePresentation([4], "TABLE_ROW", 1, 2, 1),
  consistency: notReviewedConsistency(comparisonKey("Q5_MARKING_COMPARISON", question.family.familyId, ["trig-t04-sine-rule"], 3, ["NUMBER"], ["method mark independence", "follow-through", "answer-only treatment", "units"]), [consistencyFeature("answer_only_treatment", "NOT_STATED", "No question-specific correct-answer-without-working award is stated.", [evidence]), consistencyFeature("specific_wrong_substitution_still_allows_later_marks", true, "The source explicitly awards marks 2 and 3 after a specified first-stage substitution error.", [evidence]), consistencyFeature("unit_penalty_explicit", false, "The expected answer includes cm but no question-specific unit penalty is stated.", [evidence])]),
  integrity: answerIntegrity(), generation: generationNotReviewed(), review: answerReviewInProgress("5"),
} satisfies AnswerCatalogEntry;
