import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation, visualOriginality, visualValidation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("10", 10);
const visualEvidence = qpEvidence("10", 10, "VISUAL");

export const N5_MATHS_2014_P1_Q10 = {
  identity: { id: "N5_MATH_2014_P1_Q10", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "10", answerCatalogId: "N5_MATH_2014_P1_Q10_MS" },
  sourceLayout: { sourcePages: [10], printedPageLabels: ["Page 10"], continuesAcrossPages: false, answerSpace: { category: "MEDIUM", estimatedWritingLines: 6, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "The supplied trigonometric graph dominates the page; the response itself is short." }, sourceEvidence: [evidence] },
  structure: { structureType: "SINGLE", totalMarks: 2, parts: [{ id: "Q10_MAIN", label: "", marks: 2, primarySkillId: "trig-t01-graphs", secondarySkillIds: [], conceptIds: ["trig-t1-1"], topic: "TRIG", commandTypes: ["WRITE_DOWN"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: [], visualElementIds: ["VIS_Q10"] }], dependencyType: "INDEPENDENT", sharedStimulus: false, sharedVisuals: false, sharedGivenData: false, requiredResultProvided: false },
  curriculum: { primaryTopic: "TRIG", primarySkillId: "trig-t01-graphs", secondarySkillIds: [], primaryConceptId: "trig-t1-1", conceptIds: ["trig-t1-1"], paperSuitability: "P1", standardProfile: "A", thinkingProfile: "REASONING", crossSkillQuestion: false, skillMarkDistribution: { "trig-t01-graphs": 2 }, conceptMarkDistribution: { "trig-t1-1": 2 } },
  task: { commandTypes: ["WRITE_DOWN"], responseTypes: ["NUMBER"], responseCount: 2, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },
  mathematics: { primaryGoal: "Infer amplitude and horizontal phase parameter of a transformed sine graph.", subgoals: [{ id: "Q10_S1", summary: "Read the amplitude from the graph extrema.", dependsOnSubgoalIds: [] }, { id: "Q10_S2", summary: "Use the shifted sine landmarks to infer the horizontal phase parameter.", dependsOnSubgoalIds: [] }], operationTypes: ["INTERPRET"], requiredFormulaIds: [], requiredTheoremIds: ["SINE_GRAPH_FEATURES"], stageCount: 2, intermediateQuantityTypes: ["amplitude", "phase shift"], methodSelectionRequired: false, solutionCountExpected: 2, validitySelectionRequired: false, representationTransitions: [{ from: "trigonometric graph", to: "transformation parameters", purpose: "identify amplitude and phase" }] },
  information: [
    { id: "Q10_INFO_MODEL", informationType: "function form", normalisedContent: "y=a sin((x+b) degrees)", value: "y=a sin((x+b)°)", unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: "VIS_Q10", usedByPartIds: ["Q10_MAIN"] },
    { id: "Q10_INFO_DOMAIN", informationType: "domain", normalisedContent: "0≤x≤360 degrees", value: "0≤x≤360", unit: "degrees", source: "TEXT", explicitness: "EXPLICIT", role: "DOMAIN", visualElementId: "VIS_Q10", usedByPartIds: ["Q10_MAIN"] },
    { id: "Q10_INFO_EXTREMA", informationType: "graph feature", normalisedContent: "graph reaches approximately +3 and -3", value: "±3", unit: null, source: "GRAPH", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q10", usedByPartIds: ["Q10_MAIN"] },
    { id: "Q10_INFO_PHASE", informationType: "graph feature", normalisedContent: "shifted zero/max/min landmarks determine b", value: null, unit: "degrees", source: "GRAPH", explicitness: "MUST_INFER", role: "RELATIONSHIP", visualElementId: "VIS_Q10", usedByPartIds: ["Q10_MAIN"] },
  ],
  reasoning: { reasoningTypes: ["VISUAL_INTERPRETATION", "STRUCTURE_RECOGNITION", "REPRESENTATION_TRANSLATION"], difficulty: { overallDifficulty: "MEDIUM", methodSelectionLoad: "LOW", arithmeticLoad: "VERY_LOW", algebraicLoad: "LOW", representationLoad: "HIGH", languageLoad: "LOW", contextInterpretationLoad: "VERY_LOW", reasoningDepth: "MEDIUM", dependencyCount: 0, difficultyDrivers: ["reading amplitude from extrema", "interpreting horizontal shift with sign convention"] } },
  numbers: { numberTypes: ["INTEGER", "NEGATIVE"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: false, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["amplitude is clearly readable", "phase shift produces clear degree-grid landmarks", "one full cycle is visible"], safeVariationAxes: ["amplitude", "phase shift", "axis scale", "curve styling"], invariantRelationships: ["graph is y=a sin((x+b)°)", "visual extrema and zero crossings agree exactly with parameters"], degeneracyConditionsToAvoid: ["zero amplitude", "phase value indistinguishable from unshifted sine", "plot window that hides required landmarks"] },
  constraints: { mathematicalDomainConstraints: ["0≤x≤360"], contextValidityConstraints: [], calculatorModeConstraints: ["No calculator is needed; values are read from structural graph features."], methodConstraints: [], presentationConstraints: [] },
  answerSpecification: { answerForm: "EXACT", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: null, unitSymbol: null, conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 2, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: false, contextDomain: null, contextRole: "NONE", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: false, realismConstrainsAnswer: false, contextObjects: [], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "LOW", scaffoldingLevel: "LOW", bulletStructureUsed: false, naturalLanguageInterpretationRequired: false, promptSummary: "Read the amplitude and horizontal phase parameter from a supplied transformed sine graph over one full degree cycle.", styleNotes: null },
  visuals: catalogValue({ elements: [{
    id: "VIS_Q10", sourceOrder: 1, visualType: "GRAPH", roles: ["ESSENTIAL_DATA", "STRUCTURAL_MODEL"], dependency: "REQUIRED_TO_SOLVE", candidateInteraction: "READ_VALUES", textRelationship: "VISUAL_ONLY",
    scale: { mode: "TO_SCALE", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: true, notes: "Key extrema and phase landmarks must align with labelled axis values." },
    orientation: { verticalDirectionMeaningful: true, horizontalDirectionMeaningful: true, northReferenceMeaningful: false, groundReferenceMeaningful: false, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: false, rotationSafe: false },
    labels: [{ entityId: "Q10_X", role: "AXIS", normalisedValue: "x", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }, { entityId: "Q10_Y", role: "AXIS", normalisedValue: "y", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }],
    semanticModel: { entities: [
      { id: "Q10_X", entityType: "AXIS", semanticName: "degree x-axis", printedLabel: "x", numericValue: null, symbolicValue: "x", unit: "degrees", mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: { min: 0, max: 360, tick: 20 } },
      { id: "Q10_Y", entityType: "AXIS", semanticName: "y-axis", printedLabel: "y", numericValue: null, symbolicValue: "y", unit: null, mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: { min: -3, max: 3 } },
      { id: "Q10_CURVE", entityType: "CURVE", semanticName: "transformed sine curve", printedLabel: null, numericValue: null, symbolicValue: "y=a sin((x+b)°)", unit: null, mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: {} },
    ], relations: [], facts: [
      { id: "Q10_F1", factType: "AMPLITUDE", normalisedFact: "vertical extrema have magnitude 3", relatedEntityIds: ["Q10_CURVE", "Q10_Y"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q10_F2", factType: "PHASE_LANDMARKS", normalisedFact: "zero crossings and extrema are horizontally shifted from standard sine positions", relatedEntityIds: ["Q10_CURVE", "Q10_X"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: true, sourceEvidence: [visualEvidence] },
    ] },
    layout: { sourcePageNumber: 10, sourcePagePosition: "MIDDLE", sourceRelativeWidth: "LARGE", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: 100, minimumReadableHeightMm: 70, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
    specialisedProfiles: { geometry: notApplicable(), circle: notApplicable(), graph: catalogValue({ graphFamily: "SINE", xAxis: { variable: "x", label: "x", unit: "degrees", numericScaleShown: true, tickInterval: 20, minimumShown: 0, maximumShown: 360 }, yAxis: { variable: "y", label: "y", unit: null, numericScaleShown: true, tickInterval: 1, minimumShown: -3, maximumShown: 3 }, originShown: true, gridShown: false, rootsRelevant: true, turningPointsRelevant: true, asymptotesRelevant: false, symmetryRelevant: false, labelledPointIds: [], referenceLinesPresent: false, candidateMustReadValues: true, candidateMustProduceGraph: false, accuracyExpectation: "ACCURATE" }, [visualEvidence]), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable() },
    generation: { readiness: "PARTIAL", strategy: "PROCEDURAL_GRAPH", rendererFamilyId: "TRIG_FUNCTION_GRAPH", allowedMediaAssetIds: [], requiredAssetTags: [], semanticInvariants: ["sine curve parameters match generated a and b", "one full cycle and readable landmarks are visible"], safeVariationAxes: ["amplitude", "phase", "plot dimensions", "styling"], unsafeVariations: ["graph/parameter mismatch", "cropping required landmarks"], permittedOrientationChanges: [], permittedStyleChanges: ["line weight", "font spacing", "axis size"], requiredRendererCapabilities: ["degree trig plotting", "accurate axes/ticks", "parameter-driven curve"], requiredValidationChecks: ["curve extrema and zero crossings agree with parameters", "labels are readable", "no clipping"], provenance: "GENERATION_ANALYSIS" },
    originality: visualOriginality(), validation: visualValidation(true, true), sourceEvidence: [visualEvidence], confidence: "HIGH",
  }], visualCount: 1, relationships: [], containsEssentialVisualData: true, containsContextImage: false, containsProcedurallyReproducibleDiagram: true, containsResponseSurface: false, generationRequiresMultipleVisuals: false }, [visualEvidence]),
  mathematicalModel: notApplicable(),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: catalogValue({ functionFamily: "SINE", functionNotationUsed: false, transformationParametersPresent: true, rootsRelevant: true, turningPointsRelevant: true, graphInterpretationRequired: true }, [evidence]), statistics: notApplicable(), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: catalogValue({ trigFunctions: ["SIN"], trigContext: "GRAPH", angleUnit: "DEGREES", domainStart: 0, domainEnd: 360, domainEndInclusive: true, quadrantReasoningRequired: false, inverseTrigRequired: false, multipleSolutionsRequired: false, exactTrigValuesRequired: false, sineRuleUsed: false, cosineRuleUsed: false, areaFormulaUsed: false, calculatorModeSensitive: false }, [evidence]), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },
  family: { familyId: "TRIG_SINE_GRAPH_AMPLITUDE_PHASE", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["transformed sine graph", "amplitude parameter", "horizontal phase parameter", "one degree cycle"], surfaceStyleIds: ["SUPPLIED_TRIG_GRAPH", "READ_PARAMETERS"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "ABSTRACT", proseAmount: "LOW", visualAmount: "HIGH", layoutComplexity: "MEDIUM", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: true },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["TRIG_SINE_GRAPH_AMPLITUDE_PHASE"], invariantMathematics: ["parameter recovery from sine graph"], variableParameters: ["amplitude", "phase shift", "axis scale"], parameterConstraints: ["parameters produce clear exact graph landmarks"], safeContextVariations: [], safeRepresentationVariations: ["graph styling and dimensions"], unsafeVariations: ["graph does not match displayed function"], difficultyControls: ["phase landmark placement", "axis interval"], requiredVisualCapabilities: ["parameter-driven trigonometric graph renderer"], requiredValidationChecks: ["visual parameters equal question parameters", "required landmarks are visible", "instance remains Paper 1 readable"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: { ...questionReviewInProgress(true), unresolvedIssues: [...questionReviewInProgress(true).unresolvedIssues, "Historical 2014 Paper 1 uses the canonical trig-graphs Skill even though the current Skills Tree marks that Skill as P2; reconcile paper-suitability metadata before production generation."] },
} satisfies QuestionCatalogEntry;
