import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation, visualOriginality, visualValidation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("13", 13);
const visualEvidence = qpEvidence("13", 13, "VISUAL");

export const N5_MATHS_2014_P1_Q13 = {
  // ============================================================================
  // SECTION 1 — IDENTITY / SOURCE
  // ============================================================================
  identity: { id: "N5_MATH_2014_P1_Q13", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "13", answerCatalogId: "N5_MATH_2014_P1_Q13_MS" },
  sourceLayout: { sourcePages: [13], printedPageLabels: ["Page 13"], continuesAcrossPages: false, answerSpace: { category: "FULL_PAGE", estimatedWritingLines: 20, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Final Paper 1 Question combines a contextual quadratic model, schematic height-time graph, two parts and justification." }, sourceEvidence: [evidence] },

  // ============================================================================
  // SECTION 3 — STRUCTURE / CURRICULUM / TASK
  // ============================================================================
  structure: { structureType: "MULTIPART", totalMarks: 7, parts: [
    { id: "Q13_a", label: "a", marks: 4, primarySkillId: "alg-a13-quadratic-equations-factorise", secondarySkillIds: [], conceptIds: ["alg-a13-1"], topic: "ALG", commandTypes: ["FIND"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: ["Q13_INFO_MODEL"], visualElementIds: ["VIS_Q13"] },
    { id: "Q13_b", label: "b", marks: 3, primarySkillId: "alg-a13-quadratic-equations-factorise", secondarySkillIds: ["alg-a03-complete-the-square", "alg-a14-discriminant"], conceptIds: ["alg-a13-1", "alg-a3-1", "alg-a14-1"], topic: "ALG", commandTypes: ["DETERMINE", "JUSTIFY"], responseTypes: ["MIXED"], dependsOnPartIds: [], sharedInformationIds: ["Q13_INFO_MODEL"], visualElementIds: ["VIS_Q13"] },
  ], dependencyType: "SHARED_SETUP", sharedStimulus: true, sharedVisuals: true, sharedGivenData: true, requiredResultProvided: false },
  curriculum: { primaryTopic: "ALG", primarySkillId: "alg-a13-quadratic-equations-factorise", secondarySkillIds: ["alg-a03-complete-the-square", "alg-a14-discriminant"], primaryConceptId: "alg-a13-1", conceptIds: ["alg-a13-1", "alg-a3-1", "alg-a14-1"], paperSuitability: "P1", standardProfile: "A", thinkingProfile: "REASONING", crossSkillQuestion: true, skillMarkDistribution: { "alg-a13-quadratic-equations-factorise": 7 }, conceptMarkDistribution: { "alg-a13-1": 7 } },
  task: { commandTypes: ["FIND", "DETERMINE", "JUSTIFY"], responseTypes: ["MIXED"], responseCount: 2, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: true, contextualConclusionRequested: true, visualResponseRequired: false },

  // ============================================================================
  // SECTION 6 — MATHEMATICAL STRUCTURE / INFORMATION
  // ============================================================================
  mathematics: { primaryGoal: "Use and analyse a contextual quadratic height model to find a first target time and decide whether a larger target height is attainable.", subgoals: [
    { id: "Q13_S1", summary: "Set the height model equal to the first target and form a quadratic equation.", dependsOnSubgoalIds: [] },
    { id: "Q13_S2", summary: "Solve the quadratic and choose the earlier physically valid time.", dependsOnSubgoalIds: ["Q13_S1"] },
    { id: "Q13_S3", summary: "Analyse the same model to decide whether the second height is attainable.", dependsOnSubgoalIds: [] },
    { id: "Q13_S4", summary: "Give a mathematical justification consistent with the model.", dependsOnSubgoalIds: ["Q13_S3"] },
  ], operationTypes: ["SUBSTITUTE", "REARRANGE", "FACTORISE", "SOLVE", "FILTER_SOLUTIONS", "INTERPRET"], requiredFormulaIds: [], requiredTheoremIds: [], stageCount: 4, intermediateQuantityTypes: ["quadratic equation in time", "candidate times", "maximum or solution-existence evidence"], methodSelectionRequired: true, solutionCountExpected: null, validitySelectionRequired: true, representationTransitions: [{ from: "contextual height model", to: "quadratic equation", purpose: "solve for time at a target height" }, { from: "quadratic mathematics", to: "contextual conclusion", purpose: "decide physical attainability" }] },
  information: [
    { id: "Q13_INFO_MODEL", informationType: "formula", normalisedContent: "rocket height model is h(t)=16t-t^2", value: "h(t)=16t-t^2", unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "FORMULA", visualElementId: "VIS_Q13", usedByPartIds: ["Q13_a", "Q13_b"] },
    { id: "Q13_INFO_TARGET60", informationType: "target", normalisedContent: "first target height is 60 m", value: 60, unit: "m", source: "TEXT", explicitness: "EXPLICIT", role: "TARGET", visualElementId: null, usedByPartIds: ["Q13_a"] },
    { id: "Q13_INFO_FIRST", informationType: "selection", normalisedContent: "part a asks for the first time the target height is reached", value: null, unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "CONSTRAINT", visualElementId: null, usedByPartIds: ["Q13_a"] },
    { id: "Q13_INFO_TARGET70", informationType: "target", normalisedContent: "second target height is 70 m", value: 70, unit: "m", source: "TEXT", explicitness: "EXPLICIT", role: "TARGET", visualElementId: null, usedByPartIds: ["Q13_b"] },
  ],
  reasoning: { reasoningTypes: ["MULTI_STAGE", "METHOD_SELECTION", "SOLUTION_FILTERING", "VALIDATION", "JUSTIFICATION", "CONTEXT_INTERPRETATION"], difficulty: { overallDifficulty: "VERY_HIGH", methodSelectionLoad: "HIGH", arithmeticLoad: "MEDIUM", algebraicLoad: "HIGH", representationLoad: "LOW", languageLoad: "MEDIUM", contextInterpretationLoad: "MEDIUM", reasoningDepth: "VERY_HIGH", dependencyCount: 3, difficultyDrivers: ["forming and solving a contextual quadratic", "selecting the first of two mathematical times", "choosing a valid way to prove a larger height is unattainable", "converting algebraic evidence into a contextual conclusion"] } },
  numbers: { numberTypes: ["INTEGER", "ALGEBRAIC"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: true, perfectSquareDesigned: true, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["first target produces two distinct exact positive times", "second target lies above the model maximum", "maximum and factorisation remain Paper-1-friendly"], safeVariationAxes: ["quadratic coefficients", "first target", "second target", "physical context"], invariantRelationships: ["downward-opening quadratic", "first target attainable twice", "second target unattainable", "first-time selection required"], degeneracyConditionsToAvoid: ["first target equals maximum", "negative physical time as only relevant solution", "second target becomes attainable", "awkward non-factorising first equation"] },
  constraints: { mathematicalDomainConstraints: ["t≥0 in the physical context"], contextValidityConstraints: ["height and time interpretations must be physically sensible"], calculatorModeConstraints: ["Target equations and justification must be feasible without calculator."], methodConstraints: [], presentationConstraints: ["Part a requires the first valid time; part b requires a justified contextual conclusion."] },
  answerSpecification: { answerForm: "MIXED", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: "mixed time/conclusion", unitSymbol: null, conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 2, domainRestriction: "t≥0", contextualWordsRequired: true, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: true, contextDomain: "projectile motion", contextRole: "MODEL_DEFINING", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: true, realismConstrainsAnswer: true, contextObjects: ["rocket", "height", "time"], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "MEDIUM", scaffoldingLevel: "LOW", bulletStructureUsed: false, naturalLanguageInterpretationRequired: true, promptSummary: "A downward quadratic models height over time; find the first time one height is reached and justify whether a higher target can be reached.", styleNotes: "The open justification in part b permits more than one valid mathematical route; the Answer Catalogue must later capture method equivalence and marking behaviour." },

  // ============================================================================
  // SECTION 12 — VISUAL EVIDENCE
  // ============================================================================
  visuals: catalogValue({ elements: [{
    id: "VIS_Q13", sourceOrder: 1, visualType: "GRAPH", roles: ["CONTEXT_MODEL", "SUPPORTIVE"], dependency: "SUPPORTIVE_ONLY", candidateInteraction: "READ_ONLY", textRelationship: "FULLY_DUPLICATED",
    scale: { mode: "SCHEMATIC", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: false, notes: "No numerical values are intended to be read from the schematic." },
    orientation: { verticalDirectionMeaningful: true, horizontalDirectionMeaningful: true, northReferenceMeaningful: false, groundReferenceMeaningful: true, startPositionMeaningful: true, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: false, rotationSafe: false },
    labels: [{ entityId: "Q13_T", role: "AXIS", normalisedValue: "t", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }, { entityId: "Q13_H", role: "AXIS", normalisedValue: "h", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }],
    semanticModel: { entities: [
      { id: "Q13_T", entityType: "AXIS", semanticName: "time axis", printedLabel: "t", numericValue: null, symbolicValue: "t", unit: "s", mathematicallyEssential: false, orientationMeaningful: true, candidateEditable: false, attributes: { origin: 0 } },
      { id: "Q13_H", entityType: "AXIS", semanticName: "height axis", printedLabel: "h", numericValue: null, symbolicValue: "h", unit: "m", mathematicallyEssential: false, orientationMeaningful: true, candidateEditable: false, attributes: { origin: 0 } },
      { id: "Q13_CURVE", entityType: "CURVE", semanticName: "rocket height parabola", printedLabel: null, numericValue: null, symbolicValue: "h(t)=16t-t^2", unit: null, mathematicallyEssential: false, orientationMeaningful: true, candidateEditable: false, attributes: { opensDown: true } },
    ], relations: [{ id: "Q13_R1", relationType: "REPRESENTS", fromEntityIds: ["Q13_CURVE"], toEntityIds: ["Q13_T", "Q13_H"], normalisedMeaning: "The downward parabola represents rocket height as time increases.", essentialToSolution: false, sourceEvidence: [visualEvidence] }], facts: [{ id: "Q13_F1", factType: "SHAPE", normalisedFact: "height-time model is a downward-opening parabola starting at ground level", relatedEntityIds: ["Q13_CURVE"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: false, sourceEvidence: [visualEvidence] }] },
    layout: { sourcePageNumber: 13, sourcePagePosition: "MIDDLE", sourceRelativeWidth: "MEDIUM", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: null, minimumReadableHeightMm: null, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
    specialisedProfiles: { geometry: notApplicable(), circle: notApplicable(), graph: catalogValue({ graphFamily: "CONTEXTUAL_GRAPH", xAxis: { variable: "t", label: "time", unit: "s", numericScaleShown: false, tickInterval: null, minimumShown: 0, maximumShown: null }, yAxis: { variable: "h", label: "height", unit: "m", numericScaleShown: false, tickInterval: null, minimumShown: 0, maximumShown: null }, originShown: true, gridShown: false, rootsRelevant: true, turningPointsRelevant: true, asymptotesRelevant: false, symmetryRelevant: true, labelledPointIds: [], referenceLinesPresent: false, candidateMustReadValues: false, candidateMustProduceGraph: false, accuracyExpectation: "SCHEMATIC" }, [visualEvidence]), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable() },
    generation: { readiness: "PARTIAL", strategy: "PROCEDURAL_GRAPH", rendererFamilyId: "CONTEXTUAL_FUNCTION_GRAPH", allowedMediaAssetIds: [], requiredAssetTags: [], semanticInvariants: ["downward parabola", "time horizontal and height vertical", "curve is consistent with generated quadratic model"], safeVariationAxes: ["plot proportions", "line styling", "amount of visible post-maximum descent"], unsafeVariations: ["graph shape contradicts model", "numerical-looking scale that suggests false read-off data"], permittedOrientationChanges: [], permittedStyleChanges: ["line weight", "axis length", "label spacing"], requiredRendererCapabilities: ["contextual function graph", "schematic axes", "parameter-driven quadratic shape"], requiredValidationChecks: ["curve direction agrees with quadratic coefficient", "graph is clearly schematic", "labels are readable"], provenance: "GENERATION_ANALYSIS" },
    originality: visualOriginality(), validation: visualValidation(true, true), sourceEvidence: [visualEvidence], confidence: "HIGH",
  }], visualCount: 1, relationships: [], containsEssentialVisualData: false, containsContextImage: false, containsProcedurallyReproducibleDiagram: true, containsResponseSurface: false, generationRequiresMultipleVisuals: false }, [visualEvidence]),

  // ============================================================================
  // SECTION 13 — MODEL / SPECIALISED PROFILES
  // ============================================================================
  mathematicalModel: catalogValue({ modelFamily: "QUADRATIC", normalisedModel: "h(t)=16t-t^2", independentVariable: "t", dependentVariable: "h", physicalOrContextDomain: "rocket flight for non-negative time", modelProvidedToCandidate: true, candidateMustConstructModel: false, candidateMustInterpretModel: true, solveForIndependentVariable: true, targetDependentValueProvided: true, modelParameters: { linearCoefficient: 16, quadraticCoefficient: -1 } }, [evidence], "SOURCE_FACT"),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: catalogValue({ expansionRequired: false, factorisationRequired: true, completingSquareRequired: false, rationalExpressionPresent: false, changeOfSubjectRequired: false }, [evidence]), equationsInequalities: catalogValue({ equationFamily: "QUADRATIC", inequalityPresent: false, algebraicMethodRequired: false, repeatedSubstitutionInvalid: true, expectedSolutionCount: 2, rejectedSolutionReason: "Part (a) explicitly requires the first physically valid time." }, [evidence]), functionsGraphs: catalogValue({ functionFamily: "QUADRATIC", functionNotationUsed: true, transformationParametersPresent: false, rootsRelevant: true, turningPointsRelevant: true, graphInterpretationRequired: false }, [evidence]), statistics: notApplicable(), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },

  // ============================================================================
  // SECTION 15 — FAMILY / GENERATION / REVIEW
  // ============================================================================
  family: { familyId: "ALG_CONTEXTUAL_QUADRATIC_HEIGHT_MODEL", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["downward quadratic contextual model", "solve target height", "select first time", "test higher target attainability"], surfaceStyleIds: ["CONTEXTUAL_MODEL_WITH_SCHEMATIC_GRAPH", "MULTIPART_JUSTIFICATION"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "CONTEXTUAL", proseAmount: "HIGH", visualAmount: "MEDIUM", layoutComplexity: "HIGH", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: false },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["ALG_CONTEXTUAL_QUADRATIC_HEIGHT_MODEL"], invariantMathematics: ["downward quadratic model", "attainable first target with two times", "unattainable second target", "justified contextual conclusion"], variableParameters: ["quadratic coefficient profile", "target heights", "physical context"], parameterConstraints: ["first target factors exactly", "second target exceeds model maximum", "physical times remain sensible"], safeContextVariations: ["projectile height", "arched motion", "other downward quadratic physical models"], safeRepresentationVariations: ["schematic graph may vary while remaining mathematically consistent"], unsafeVariations: ["target ordering that makes part b attainable", "first target with repeated root at maximum"], difficultyControls: ["factorisation complexity", "distance of first target from maximum", "method freedom in part b"], requiredVisualCapabilities: ["contextual quadratic graph renderer"], requiredValidationChecks: ["mark total and part structure remain valid", "generated values satisfy all parameter constraints", "required answer form remains attainable without calculator", "generated instance is mathematically non-degenerate"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(true),
} satisfies QuestionCatalogEntry;
