import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation, visualOriginality, visualValidation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("12", 12);
const visualEvidence = qpEvidence("12", 12, "VISUAL");

export const N5_MATHS_2014_P1_Q12 = {
  // ============================================================================
  // SECTION 1 — IDENTITY / SOURCE
  // ============================================================================
  identity: { id: "N5_MATH_2014_P1_Q12", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "12", answerCatalogId: "N5_MATH_2014_P1_Q12_MS" },
  sourceLayout: { sourcePages: [12], printedPageLabels: ["Page 12"], continuesAcrossPages: false, answerSpace: { category: "LARGE", estimatedWritingLines: 12, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Circle/chord diagram occupies the upper-middle page with working space below." }, sourceEvidence: [evidence] },

  // ============================================================================
  // SECTION 3 — STRUCTURE / CURRICULUM / TASK
  // ============================================================================
  structure: { structureType: "SINGLE", totalMarks: 4, parts: [{ id: "Q12_MAIN", label: "", marks: 4, primarySkillId: "geo-g04-pythagoras-chord", secondarySkillIds: [], conceptIds: ["geo-g4-2"], topic: "GEO", commandTypes: ["CALCULATE"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: [], visualElementIds: ["VIS_Q12"] }], dependencyType: "INDEPENDENT", sharedStimulus: false, sharedVisuals: false, sharedGivenData: false, requiredResultProvided: false },
  curriculum: { primaryTopic: "GEO", primarySkillId: "geo-g04-pythagoras-chord", secondarySkillIds: [], primaryConceptId: "geo-g4-2", conceptIds: ["geo-g4-2"], paperSuitability: "P1", standardProfile: "C+A", thinkingProfile: "REASONING", crossSkillQuestion: false, skillMarkDistribution: { "geo-g04-pythagoras-chord": 4 }, conceptMarkDistribution: { "geo-g4-2": 4 } },
  task: { commandTypes: ["CALCULATE"], responseTypes: ["NUMBER"], responseCount: 1, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },

  // ============================================================================
  // SECTION 6 — MATHEMATICAL STRUCTURE
  // ============================================================================
  mathematics: { primaryGoal: "Use circle/chord structure to form a right triangle, apply Pythagoras, and recover the full chord length.", subgoals: [
    { id: "Q12_S1", summary: "Use the diagram and radius to obtain the centre-to-midpoint distance CA.", dependsOnSubgoalIds: [] },
    { id: "Q12_S2", summary: "Use the theorem that the line from the centre to a chord midpoint is perpendicular to the chord.", dependsOnSubgoalIds: ["Q12_S1"] },
    { id: "Q12_S3", summary: "Apply Pythagoras to find half the chord.", dependsOnSubgoalIds: ["Q12_S2"] },
    { id: "Q12_S4", summary: "Double the half-chord because A is the midpoint.", dependsOnSubgoalIds: ["Q12_S3"] },
  ], operationTypes: ["SUBTRACT", "CONSTRUCT", "EVALUATE", "MULTIPLY"], requiredFormulaIds: ["PYTHAGORAS"], requiredTheoremIds: ["CENTRE_TO_CHORD_MIDPOINT_PERPENDICULAR"], stageCount: 4, intermediateQuantityTypes: ["centre-to-chord distance", "half-chord length"], methodSelectionRequired: true, solutionCountExpected: 1, validitySelectionRequired: false, representationTransitions: [{ from: "circle diagram", to: "right-triangle model", purpose: "make Pythagoras available" }] },
  information: [
    { id: "Q12_INFO_RADIUS", informationType: "radius", normalisedContent: "circle radius is 15 cm", value: 15, unit: "cm", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q12", usedByPartIds: ["Q12_MAIN"] },
    { id: "Q12_INFO_MID", informationType: "midpoint", normalisedContent: "A is the midpoint of chord PQ", value: null, unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: "VIS_Q12", usedByPartIds: ["Q12_MAIN"] },
    { id: "Q12_INFO_AB", informationType: "length", normalisedContent: "AB has length 27 cm", value: 27, unit: "cm", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q12", usedByPartIds: ["Q12_MAIN"] },
    { id: "Q12_INFO_COLLINEAR", informationType: "diagram relationship", normalisedContent: "A, C and B lie on the same straight line with B on the circle", value: null, unit: null, source: "DIAGRAM", explicitness: "IMPLIED", role: "RELATIONSHIP", visualElementId: "VIS_Q12", usedByPartIds: ["Q12_MAIN"] },
  ],
  reasoning: { reasoningTypes: ["VISUAL_INTERPRETATION", "INFORMATION_MARSHALLING", "STRUCTURE_RECOGNITION", "MULTI_STAGE"], difficulty: { overallDifficulty: "HIGH", methodSelectionLoad: "MEDIUM", arithmeticLoad: "LOW", algebraicLoad: "VERY_LOW", representationLoad: "MEDIUM", languageLoad: "MEDIUM", contextInterpretationLoad: "VERY_LOW", reasoningDepth: "HIGH", dependencyCount: 3, difficultyDrivers: ["using visual collinearity and boundary position", "recognising the chord-midpoint perpendicular theorem", "forming the correct right triangle", "doubling the half-chord"] } },
  numbers: { numberTypes: ["INTEGER"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: true, pythagoreanTripleUsed: true, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["AB exceeds the radius so A lies inside the circle on the same radial line", "derived CA is positive and less than radius", "radius and CA form a Pythagorean pair with an exact half-chord"], safeVariationAxes: ["radius", "AB", "chord orientation", "point labels"], invariantRelationships: ["A is midpoint of chord", "C is centre", "A-C-B are collinear", "B lies on circle"], degeneracyConditionsToAvoid: ["CA=0 unless diameter case intended", "CA≥radius", "non-exact square root for this Paper 1 family"] },
  constraints: { mathematicalDomainConstraints: ["0<CA<radius"], contextValidityConstraints: [], calculatorModeConstraints: ["Pythagorean arithmetic must remain manageable without calculator."], methodConstraints: [], presentationConstraints: [] },
  answerSpecification: { answerForm: "EXACT", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: "length", unitSymbol: "cm", conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 1, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: false, contextDomain: null, contextRole: "NONE", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: true, realismConstrainsAnswer: false, contextObjects: [], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "MEDIUM", scaffoldingLevel: "LOW", bulletStructureUsed: false, naturalLanguageInterpretationRequired: false, promptSummary: "A circle diagram supplies a chord midpoint, radius and radial distance; calculate the chord length.", styleNotes: "The diagram carries the collinear A-C-B relationship and the fact that B is on the circumference; these should not be discarded in regeneration." },

  // ============================================================================
  // SECTION 12 — VISUAL EVIDENCE
  // ============================================================================
  visuals: catalogValue({ elements: [{
    id: "VIS_Q12", sourceOrder: 1, visualType: "CIRCLE_DIAGRAM", roles: ["ESSENTIAL_DATA", "STRUCTURAL_MODEL"], dependency: "REQUIRED_TO_SOLVE", candidateInteraction: "READ_ONLY", textRelationship: "PARTLY_DUPLICATED",
    scale: { mode: "SCHEMATIC", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: true, notes: "Topology and collinearity matter; source proportions do not." },
    orientation: { verticalDirectionMeaningful: false, horizontalDirectionMeaningful: false, northReferenceMeaningful: false, groundReferenceMeaningful: false, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: true, rotationSafe: true },
    labels: ["P", "Q", "A", "C", "B"].map((v) => ({ entityId: `Q12_${v}`, role: "POINT_NAME" as const, normalisedValue: v, placementMathematicallyConstrained: true, collisionPriority: "HIGH" as const })),
    semanticModel: { entities: [
      { id: "Q12_CIRCLE", entityType: "CIRCLE", semanticName: "circle", printedLabel: null, numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: { radius: 15 } },
      { id: "Q12_C", entityType: "POINT", semanticName: "centre C", printedLabel: "C", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
      { id: "Q12_P", entityType: "POINT", semanticName: "chord endpoint P", printedLabel: "P", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
      { id: "Q12_Q", entityType: "POINT", semanticName: "chord endpoint Q", printedLabel: "Q", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
      { id: "Q12_A", entityType: "POINT", semanticName: "midpoint A of chord PQ", printedLabel: "A", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
      { id: "Q12_B", entityType: "POINT", semanticName: "point B on circumference", printedLabel: "B", numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
      { id: "Q12_CHORD", entityType: "SEGMENT", semanticName: "chord PQ", printedLabel: null, numericValue: null, symbolicValue: "PQ", unit: "cm", mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
    ], relations: [
      { id: "Q12_R1", relationType: "CENTRE_OF", fromEntityIds: ["Q12_C"], toEntityIds: ["Q12_CIRCLE"], normalisedMeaning: "C is the centre of the circle", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q12_R2", relationType: "CHORD_OF", fromEntityIds: ["Q12_CHORD"], toEntityIds: ["Q12_CIRCLE"], normalisedMeaning: "PQ is a chord of the circle", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q12_R3", relationType: "MIDPOINT_OF", fromEntityIds: ["Q12_A"], toEntityIds: ["Q12_CHORD"], normalisedMeaning: "A is midpoint of chord PQ", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q12_R4", relationType: "COLLINEAR_WITH", fromEntityIds: ["Q12_A", "Q12_C"], toEntityIds: ["Q12_B"], normalisedMeaning: "A, C and B are collinear", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q12_R5", relationType: "PART_OF", fromEntityIds: ["Q12_B"], toEntityIds: ["Q12_CIRCLE"], normalisedMeaning: "B lies on the circumference", essentialToSolution: true, sourceEvidence: [visualEvidence] },
    ], facts: [
      { id: "Q12_F1", factType: "COLLINEARITY", normalisedFact: "A, C and B share one straight radial line", relatedEntityIds: ["Q12_A", "Q12_C", "Q12_B"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: true, sourceEvidence: [visualEvidence] },
      { id: "Q12_F2", factType: "CIRCUMFERENCE_POINT", normalisedFact: "B lies on the circle so CB is a radius", relatedEntityIds: ["Q12_B", "Q12_C", "Q12_CIRCLE"], explicitness: "VISUALLY_IMPLIED", essentialToSolution: true, sourceEvidence: [visualEvidence] },
    ] },
    layout: { sourcePageNumber: 12, sourcePagePosition: "TOP", sourceRelativeWidth: "MEDIUM", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: 70, minimumReadableHeightMm: 55, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
    specialisedProfiles: { geometry: catalogValue({ dimension: "2D", shapeFamilies: ["CIRCLE", "CHORD", "RIGHT_TRIANGLE_DERIVED"], labelledPointIds: ["Q12_P", "Q12_Q", "Q12_A", "Q12_C", "Q12_B"], rightAnglesPresent: false, parallelRelationshipsPresent: false, equalLengthRelationshipsPresent: true, similarityPresent: false, congruencePresent: false, shadedRegionsPresent: false, auxiliaryLinesPresent: true, algebraicDimensionsPresent: false, compoundShapePresent: false }, [visualEvidence]), circle: catalogValue({ circleCount: 1, centresExplicitlyShown: true, radiiPresent: true, diametersPresent: false, chordsPresent: true, tangentsPresent: false, secantsPresent: false, sectorsPresent: false, segmentsPresent: false, majorMinorArcDistinctionRelevant: false, intersectingCirclesPresent: false, commonChordPresent: false }, [visualEvidence]), graph: notApplicable(), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable() },
    generation: { readiness: "PARTIAL", strategy: "PROCEDURAL_SVG", rendererFamilyId: "CIRCLE_CHORD_GEOMETRY", allowedMediaAssetIds: [], requiredAssetTags: [], semanticInvariants: ["C is centre", "PQ is chord", "A is midpoint of PQ", "A-C-B are collinear", "B lies on circumference"], safeVariationAxes: ["chord orientation", "rotation/mirroring", "label placement", "non-semantic proportions"], unsafeVariations: ["draw explicit right-angle marker unless the generated prompt intends to supply that fact", "break A-C-B collinearity", "place B away from circumference"], permittedOrientationChanges: ["rotate or mirror whole construction while preserving topology"], permittedStyleChanges: ["line weight", "label spacing", "overall size"], requiredRendererCapabilities: ["circle", "chord", "labelled points", "collinear radial construction"], requiredValidationChecks: ["topology preserved", "B on circle", "A is chord midpoint", "no accidental supplied right-angle marker", "labels readable"], provenance: "GENERATION_ANALYSIS" },
    originality: visualOriginality(), validation: visualValidation(false, true), sourceEvidence: [visualEvidence], confidence: "HIGH",
  }], visualCount: 1, relationships: [], containsEssentialVisualData: true, containsContextImage: false, containsProcedurallyReproducibleDiagram: true, containsResponseSurface: false, generationRequiresMultipleVisuals: false }, [visualEvidence]),

  // ============================================================================
  // SECTION 13 — SPECIALISED / GENERATION / REVIEW
  // ============================================================================
  mathematicalModel: notApplicable(),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: notApplicable(), statistics: notApplicable(), geometryMeasureCircleSimilarity: catalogValue({ geometryFamilies: ["CIRCLE_CHORD", "RIGHT_TRIANGLE"], dimensions: ["2D"], compoundShapeOrSolid: false, similarityUsed: false, circleGeometryUsed: true, pythagorasUsed: true, areaRequired: false, volumeRequired: false, surfaceAreaRequired: false }, [evidence]), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },
  family: { familyId: "GEO_CIRCLE_CHORD_PYTHAGORAS", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["circle centre", "chord midpoint", "radial line through midpoint", "Pythagoras on half-chord"], surfaceStyleIds: ["LABELLED_CIRCLE_DIAGRAM", "VISUAL_RELATIONSHIP_REQUIRED"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "ABSTRACT", proseAmount: "MEDIUM", visualAmount: "HIGH", layoutComplexity: "MEDIUM", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: true },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["GEO_CIRCLE_CHORD_PYTHAGORAS"], invariantMathematics: ["centre-to-chord-midpoint theorem", "Pythagorean half-chord construction"], variableParameters: ["radius", "radial distances", "labels", "orientation"], parameterConstraints: ["derived half-chord is real, positive and Paper-1-friendly"], safeContextVariations: [], safeRepresentationVariations: ["rotate or mirror geometry while preserving topology"], unsafeVariations: ["supply a right-angle marker when theorem recognition is intended", "lose circumference/collinearity facts"], difficultyControls: ["number of inferred lengths", "Pythagorean triple complexity"], requiredVisualCapabilities: ["circle/chord semantic renderer"], requiredValidationChecks: ["all geometric relations are true", "no unintended visual facts", "numeric values produce valid circle geometry"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(true),
} satisfies QuestionCatalogEntry;
