import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation, visualOriginality, visualValidation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("7", 8);
const visualEvidence = qpEvidence("7", 8, "VISUAL");

export const N5_MATHS_2014_P1_Q7 = {
  identity: { id: "N5_MATH_2014_P1_Q7", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "7", answerCatalogId: "N5_MATH_2014_P1_Q7_MS" },
  sourceLayout: { sourcePages: [8], printedPageLabels: ["Page 8"], continuesAcrossPages: false, answerSpace: { category: "LARGE", estimatedWritingLines: 12, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Graph occupies the upper section with working space below." }, sourceEvidence: [evidence] },
  structure: { structureType: "SINGLE", totalMarks: 2, parts: [{ id: "Q7_MAIN", label: "", marks: 2, primarySkillId: "alg-a10-quadratic-from-graph", secondarySkillIds: [], conceptIds: ["alg-a10-1"], topic: "ALG", commandTypes: ["FIND"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: [], visualElementIds: ["VIS_Q7"] }], dependencyType: "INDEPENDENT", sharedStimulus: false, sharedVisuals: false, sharedGivenData: false, requiredResultProvided: false },
  curriculum: { primaryTopic: "ALG", primarySkillId: "alg-a10-quadratic-from-graph", secondarySkillIds: [], primaryConceptId: "alg-a10-1", conceptIds: ["alg-a10-1"], paperSuitability: "P1", standardProfile: "C+A", thinkingProfile: "REASONING", crossSkillQuestion: false, skillMarkDistribution: { "alg-a10-quadratic-from-graph": 2 }, conceptMarkDistribution: { "alg-a10-1": 2 } },
  task: { commandTypes: ["FIND"], responseTypes: ["NUMBER"], responseCount: 1, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },
  mathematics: { primaryGoal: "Determine the coefficient of y=ax^2 from a supplied point on its graph.", subgoals: [{ id: "Q7_S1", summary: "Read the labelled point and substitute it into y=ax^2.", dependsOnSubgoalIds: [] }, { id: "Q7_S2", summary: "Solve the resulting equation for a.", dependsOnSubgoalIds: ["Q7_S1"] }], operationTypes: ["SUBSTITUTE", "REARRANGE", "DIVIDE"], requiredFormulaIds: [], requiredTheoremIds: [], stageCount: 2, intermediateQuantityTypes: ["linear equation in a"], methodSelectionRequired: false, solutionCountExpected: 1, validitySelectionRequired: false, representationTransitions: [{ from: "graphical point", to: "algebraic substitution", purpose: "determine the unknown function parameter" }] },
  information: [
    { id: "Q7_INFO_FUNC", informationType: "function family", normalisedContent: "graph has form y=ax^2", value: "y=ax^2", unit: null, source: "GRAPH", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: "VIS_Q7", usedByPartIds: ["Q7_MAIN"] },
    { id: "Q7_INFO_POINT", informationType: "coordinate", normalisedContent: "labelled point is (-3,45)", value: "(-3,45)", unit: null, source: "GRAPH", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q7", usedByPartIds: ["Q7_MAIN"] },
  ],
  reasoning: { reasoningTypes: ["VISUAL_INTERPRETATION", "REPRESENTATION_TRANSLATION", "DIRECT_PROCEDURE"], difficulty: { overallDifficulty: "MEDIUM", methodSelectionLoad: "LOW", arithmeticLoad: "LOW", algebraicLoad: "LOW", representationLoad: "MEDIUM", languageLoad: "LOW", contextInterpretationLoad: "VERY_LOW", reasoningDepth: "MEDIUM", dependencyCount: 0, difficultyDrivers: ["extracting the labelled coordinate from the graph", "translating graph membership into substitution"] } },
  numbers: { numberTypes: ["INTEGER", "NEGATIVE", "ALGEBRAIC"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: false, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["labelled x-coordinate is non-zero", "coordinate produces an exact manageable value of a"], safeVariationAxes: ["coefficient a", "labelled x-coordinate", "graph proportions"], invariantRelationships: ["labelled point lies exactly on y=ax^2"], degeneracyConditionsToAvoid: ["x=0", "coordinate inconsistent with chosen coefficient"] },
  constraints: { mathematicalDomainConstraints: [], contextValidityConstraints: [], calculatorModeConstraints: ["Non-calculator arithmetic must remain feasible."], methodConstraints: [], presentationConstraints: [] },
  answerSpecification: { answerForm: "EXACT", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: null, unitSymbol: null, conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 1, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: false, contextDomain: null, contextRole: "NONE", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: false, realismConstrainsAnswer: false, contextObjects: [], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "LOW", scaffoldingLevel: "LOW", bulletStructureUsed: false, naturalLanguageInterpretationRequired: false, promptSummary: "Read a labelled point from a parabola of form y=ax² and determine a.", styleNotes: null },
  visuals: catalogValue({ elements: [{
    id: "VIS_Q7", sourceOrder: 1, visualType: "GRAPH", roles: ["ESSENTIAL_DATA", "STRUCTURAL_MODEL"], dependency: "REQUIRED_TO_SOLVE", candidateInteraction: "READ_ONLY", textRelationship: "VISUAL_ONLY",
    scale: { mode: "SCHEMATIC", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: false, notes: null },
    orientation: { verticalDirectionMeaningful: true, horizontalDirectionMeaningful: true, northReferenceMeaningful: false, groundReferenceMeaningful: false, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: false, rotationSafe: false },
    labels: [{ entityId: "Q7_POINT", role: "COORDINATE", normalisedValue: "(-3,45)", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }],
    semanticModel: { entities: [
      { id: "Q7_CURVE", entityType: "CURVE", semanticName: "parabola y=ax^2", printedLabel: "y=ax^2", numericValue: null, symbolicValue: "y=ax^2", unit: null, mathematicallyEssential: true, orientationMeaningful: true, candidateEditable: false, attributes: {} },
      { id: "Q7_POINT", entityType: "POINT", semanticName: "labelled point", printedLabel: "(-3,45)", numericValue: null, symbolicValue: "(-3,45)", unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: { x: -3, y: 45 } },
    ], relations: [{ id: "Q7_R1", relationType: "PART_OF", fromEntityIds: ["Q7_POINT"], toEntityIds: ["Q7_CURVE"], normalisedMeaning: "the labelled point lies on the parabola", essentialToSolution: true, sourceEvidence: [visualEvidence] }], facts: [{ id: "Q7_F1", factType: "COORDINATE", normalisedFact: "the graph contains the point (-3,45)", relatedEntityIds: ["Q7_POINT", "Q7_CURVE"], explicitness: "EXPLICIT_LABEL", essentialToSolution: true, sourceEvidence: [visualEvidence] }] },
    layout: { sourcePageNumber: 8, sourcePagePosition: "TOP", sourceRelativeWidth: "MEDIUM", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: null, minimumReadableHeightMm: null, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
    specialisedProfiles: { geometry: notApplicable(), circle: notApplicable(), graph: catalogValue({ graphFamily: "PARABOLA", xAxis: { variable: "x", label: "x", unit: null, numericScaleShown: false, tickInterval: null, minimumShown: null, maximumShown: null }, yAxis: { variable: "y", label: "y", unit: null, numericScaleShown: false, tickInterval: null, minimumShown: null, maximumShown: null }, originShown: true, gridShown: false, rootsRelevant: false, turningPointsRelevant: false, asymptotesRelevant: false, symmetryRelevant: true, labelledPointIds: ["Q7_POINT"], referenceLinesPresent: false, candidateMustReadValues: true, candidateMustProduceGraph: false, accuracyExpectation: "SCHEMATIC" }, [visualEvidence]), scatter: notApplicable(), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable() },
    generation: { readiness: "PARTIAL", strategy: "PROCEDURAL_GRAPH", rendererFamilyId: "FUNCTION_GRAPH", allowedMediaAssetIds: [], requiredAssetTags: [], semanticInvariants: ["curve has form y=ax^2", "labelled non-zero point lies exactly on curve"], safeVariationAxes: ["coefficient", "labelled point", "plot window", "styling"], unsafeVariations: ["point does not satisfy generated function"], permittedOrientationChanges: [], permittedStyleChanges: ["line weight", "axis length", "label spacing"], requiredRendererCapabilities: ["function plotting", "axes", "labelled point"], requiredValidationChecks: ["point satisfies function", "label is readable", "plot is not misleading"], provenance: "GENERATION_ANALYSIS" },
    originality: visualOriginality(), validation: visualValidation(true, true), sourceEvidence: [visualEvidence], confidence: "HIGH",
  }], visualCount: 1, relationships: [], containsEssentialVisualData: true, containsContextImage: false, containsProcedurallyReproducibleDiagram: true, containsResponseSurface: false, generationRequiresMultipleVisuals: false }, [visualEvidence]),
  mathematicalModel: notApplicable(),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: catalogValue({ functionFamily: "QUADRATIC", functionNotationUsed: false, transformationParametersPresent: true, rootsRelevant: false, turningPointsRelevant: false, graphInterpretationRequired: true }, [evidence]), statistics: notApplicable(), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },
  family: { familyId: "ALG_QUADRATIC_PARAMETER_FROM_GRAPH_POINT", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["y=ax^2", "labelled graph point", "solve coefficient"], surfaceStyleIds: ["SUPPLIED_PARABOLA", "LABELLED_POINT"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "ABSTRACT", proseAmount: "LOW", visualAmount: "HIGH", layoutComplexity: "MEDIUM", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: true },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["ALG_QUADRATIC_PARAMETER_FROM_GRAPH_POINT"], invariantMathematics: ["point-on-y=ax^2 parameter recovery"], variableParameters: ["a", "point", "graph scale"], parameterConstraints: ["point satisfies function and yields Paper 1 arithmetic"], safeContextVariations: [], safeRepresentationVariations: ["plot window and styling"], unsafeVariations: ["source point/function mismatch"], difficultyControls: ["coordinate magnitude", "sign of x"], requiredVisualCapabilities: ["quadratic function graph renderer"], requiredValidationChecks: ["generated point lies on graph", "visual labels match data", "instance remains non-degenerate"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(true),
} satisfies QuestionCatalogEntry;
