import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("11", 11);

export const N5_MATHS_2014_P1_Q11 = {
  identity: { id: "N5_MATH_2014_P1_Q11", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "11", answerCatalogId: "N5_MATH_2014_P1_Q11_MS" },
  sourceLayout: { sourcePages: [11], printedPageLabels: ["Page 11"], continuesAcrossPages: false, answerSpace: { category: "LARGE", estimatedWritingLines: 18, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Two short algebraic parts share a large working area." }, sourceEvidence: [evidence] },
  structure: { structureType: "MULTIPART", totalMarks: 4, parts: [
    { id: "Q11_a", label: "a", marks: 2, primarySkillId: "alg-a06-gradient-from-equation", secondarySkillIds: [], conceptIds: ["alg-a6-3"], topic: "ALG", commandTypes: ["FIND"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: ["Q11_INFO_LINE"], visualElementIds: [] },
    { id: "Q11_b", label: "b", marks: 2, primarySkillId: "alg-a06-gradient-from-equation", secondarySkillIds: [], conceptIds: ["alg-a6-3"], topic: "ALG", commandTypes: ["FIND"], responseTypes: ["COORDINATES"], dependsOnPartIds: [], sharedInformationIds: ["Q11_INFO_LINE"], visualElementIds: [] },
  ], dependencyType: "SHARED_SETUP", sharedStimulus: true, sharedVisuals: false, sharedGivenData: true, requiredResultProvided: false },
  curriculum: { primaryTopic: "ALG", primarySkillId: "alg-a06-gradient-from-equation", secondarySkillIds: [], primaryConceptId: "alg-a6-3", conceptIds: ["alg-a6-3"], paperSuitability: "P1", standardProfile: "C", thinkingProfile: "OPERATIONAL", crossSkillQuestion: false, skillMarkDistribution: { "alg-a06-gradient-from-equation": 4 }, conceptMarkDistribution: { "alg-a6-3": 4 } },
  task: { commandTypes: ["FIND"], responseTypes: ["MIXED"], responseCount: 2, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },
  mathematics: { primaryGoal: "Extract gradient and x-axis intercept information from a straight-line equation.", subgoals: [
    { id: "Q11_S1", summary: "Rearrange the line equation to identify the gradient.", dependsOnSubgoalIds: [] },
    { id: "Q11_S2", summary: "Set y=0 and solve for the x-axis intercept.", dependsOnSubgoalIds: [] },
  ], operationTypes: ["REARRANGE", "SOLVE", "DIVIDE"], requiredFormulaIds: [], requiredTheoremIds: ["STRAIGHT_LINE_FORM"], stageCount: 2, intermediateQuantityTypes: ["gradient", "intercept coordinate"], methodSelectionRequired: false, solutionCountExpected: 2, validitySelectionRequired: false, representationTransitions: [] },
  information: [{ id: "Q11_INFO_LINE", informationType: "straight-line equation", normalisedContent: "line is given in general linear form", value: "4x+3y=12", unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: null, usedByPartIds: ["Q11_a", "Q11_b"] }],
  reasoning: { reasoningTypes: ["DIRECT_PROCEDURE", "STRUCTURE_RECOGNITION"], difficulty: { overallDifficulty: "MEDIUM", methodSelectionLoad: "LOW", arithmeticLoad: "LOW", algebraicLoad: "MEDIUM", representationLoad: "LOW", languageLoad: "LOW", contextInterpretationLoad: "VERY_LOW", reasoningDepth: "LOW", dependencyCount: 0, difficultyDrivers: ["rearranging general line form", "interpreting x-axis intercept as y=0"] } },
  numbers: { numberTypes: ["INTEGER", "NEGATIVE", "FRACTION"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: false, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["non-zero x and y coefficients", "gradient and intercept remain exact and Paper-1-friendly"], safeVariationAxes: ["x coefficient", "y coefficient", "constant"], invariantRelationships: ["one equation supports both gradient and x-intercept tasks"], degeneracyConditionsToAvoid: ["zero y coefficient", "zero x coefficient", "awkward fractional arithmetic"] },
  constraints: { mathematicalDomainConstraints: [], contextValidityConstraints: [], calculatorModeConstraints: ["Non-calculator arithmetic must remain feasible."], methodConstraints: [], presentationConstraints: ["Part b requires coordinate form."] },
  answerSpecification: { answerForm: "MIXED", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: null, unitSymbol: null, conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 2, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: true, bracketsRelevant: true, visualAnswerRequired: false },
  context: { contextualised: false, contextDomain: null, contextRole: "NONE", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: false, realismConstrainsAnswer: false, contextObjects: [], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "LOW", scaffoldingLevel: "MEDIUM", bulletStructureUsed: false, naturalLanguageInterpretationRequired: false, promptSummary: "Given one straight-line equation, find its gradient and the coordinate where it crosses the x-axis.", styleNotes: null },
  visuals: notApplicable("No supplied visual material is used in this Question."),
  mathematicalModel: notApplicable(),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: catalogValue({ expansionRequired: false, factorisationRequired: false, completingSquareRequired: false, rationalExpressionPresent: false, changeOfSubjectRequired: false }, [evidence]), equationsInequalities: catalogValue({ equationFamily: "LINEAR_RELATION", inequalityPresent: false, algebraicMethodRequired: false, repeatedSubstitutionInvalid: false, expectedSolutionCount: null, rejectedSolutionReason: null }, [evidence]), functionsGraphs: catalogValue({ functionFamily: "LINEAR", functionNotationUsed: false, transformationParametersPresent: false, rootsRelevant: true, turningPointsRelevant: false, graphInterpretationRequired: false }, [evidence]), statistics: notApplicable(), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: catalogValue({ coordinateDimension: "2D", midpointRequired: false, gradientRequired: true, distanceRequired: false, lineEquationRequired: true, perpendicularGradientRequired: false, coordinateVectorReasoningRequired: false }, [evidence]), vectors: notApplicable() },
  family: { familyId: "ALG_STRAIGHT_LINE_GRADIENT_AND_X_INTERCEPT", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["general linear equation", "gradient extraction", "x-axis intercept"], surfaceStyleIds: ["TWO_PART_SHARED_EQUATION"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "ABSTRACT", proseAmount: "LOW", visualAmount: "NONE", layoutComplexity: "LOW", informationOrderCanVarySafely: true, visualPlacementCanVarySafely: true },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["ALG_STRAIGHT_LINE_GRADIENT_AND_X_INTERCEPT"], invariantMathematics: ["same line equation feeds both tasks"], variableParameters: ["coefficients", "constant"], parameterConstraints: ["gradient and x-intercept are exact and non-calculator-friendly"], safeContextVariations: [], safeRepresentationVariations: ["equivalent general-form sign arrangements"], unsafeVariations: ["coefficients that remove one variable"], difficultyControls: ["fractional gradient complexity", "sign pattern"], requiredVisualCapabilities: [], requiredValidationChecks: ["both requested properties match generated line", "part marks sum to total", "Paper 1 arithmetic remains feasible"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(false),
} satisfies QuestionCatalogEntry;
