import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("9", 9);

export const N5_MATHS_2014_P1_Q9 = {
  identity: { id: "N5_MATH_2014_P1_Q9", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "9", answerCatalogId: "N5_MATH_2014_P1_Q9_MS" },
  sourceLayout: { sourcePages: [9], printedPageLabels: ["Page 9"], continuesAcrossPages: false, answerSpace: { category: "LARGE", estimatedWritingLines: 10, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Short contextual prompt followed by a substantial working area." }, sourceEvidence: [evidence] },
  structure: { structureType: "SINGLE", totalMarks: 3, parts: [{ id: "Q9_MAIN", label: "", marks: 3, primarySkillId: "num-n4-reverse-percentage", secondarySkillIds: [], conceptIds: ["num-n4-1"], topic: "NUM", commandTypes: ["CALCULATE"], responseTypes: ["NUMBER"], dependsOnPartIds: [], sharedInformationIds: [], visualElementIds: [] }], dependencyType: "INDEPENDENT", sharedStimulus: false, sharedVisuals: false, sharedGivenData: false, requiredResultProvided: false },
  curriculum: { primaryTopic: "NUM", primarySkillId: "num-n4-reverse-percentage", secondarySkillIds: [], primaryConceptId: "num-n4-1", conceptIds: ["num-n4-1"], paperSuitability: "P1", standardProfile: "C", thinkingProfile: "REASONING", crossSkillQuestion: false, skillMarkDistribution: { "num-n4-reverse-percentage": 3 }, conceptMarkDistribution: { "num-n4-1": 3 } },
  task: { commandTypes: ["CALCULATE"], responseTypes: ["NUMBER"], responseCount: 1, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: false, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },
  mathematics: { primaryGoal: "Recover a whole amount from a known percentage of that whole.", subgoals: [{ id: "Q9_S1", summary: "Interpret the known amount as 80% of the unknown total.", dependsOnSubgoalIds: [] }, { id: "Q9_S2", summary: "Scale from the known percentage to 100%.", dependsOnSubgoalIds: ["Q9_S1"] }], operationTypes: ["DIVIDE", "MULTIPLY"], requiredFormulaIds: [], requiredTheoremIds: [], stageCount: 2, intermediateQuantityTypes: ["value of 1% or equivalent percentage scale"], methodSelectionRequired: false, solutionCountExpected: 1, validitySelectionRequired: false, representationTransitions: [] },
  information: [
    { id: "Q9_INFO_PART", informationType: "count", normalisedContent: "480000 tickets is the known sold quantity", value: 480000, unit: "tickets", source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: null, usedByPartIds: ["Q9_MAIN"] },
    { id: "Q9_INFO_PCT", informationType: "percentage", normalisedContent: "the known quantity represents 80% of all available tickets", value: 80, unit: "%", source: "TEXT", explicitness: "EXPLICIT", role: "RELATIONSHIP", visualElementId: null, usedByPartIds: ["Q9_MAIN"] },
  ],
  reasoning: { reasoningTypes: ["REVERSE_REASONING", "CONTEXT_INTERPRETATION"], difficulty: { overallDifficulty: "MEDIUM", methodSelectionLoad: "MEDIUM", arithmeticLoad: "MEDIUM", algebraicLoad: "VERY_LOW", representationLoad: "VERY_LOW", languageLoad: "LOW", contextInterpretationLoad: "LOW", reasoningDepth: "MEDIUM", dependencyCount: 0, difficultyDrivers: ["recognising reverse percentage rather than taking 80% of the given quantity"] } },
  numbers: { numberTypes: ["INTEGER", "PERCENTAGE"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: "Large whole-number context is deliberately compatible with simple 80% scaling." },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: false, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["percentage lies strictly between 0 and 100", "known amount and percentage produce a Paper-1-friendly whole"], safeVariationAxes: ["known amount", "percentage rate", "surface context"], invariantRelationships: ["given amount is a known percentage of a larger whole"], degeneracyConditionsToAvoid: ["100%", "pairings producing impractical hand arithmetic"] },
  constraints: { mathematicalDomainConstraints: [], contextValidityConstraints: ["Recovered whole must be at least the known part."], calculatorModeConstraints: ["Non-calculator arithmetic must remain feasible."], methodConstraints: [], presentationConstraints: [] },
  answerSpecification: { answerForm: "EXACT", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: "count", unitSymbol: "tickets", conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 1, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: true, contextDomain: "event ticketing", contextRole: "MATHEMATICALLY_RELEVANT", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: false, realismConstrainsAnswer: false, contextObjects: ["tickets", "tournament"], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "MEDIUM", scaffoldingLevel: "MEDIUM", bulletStructureUsed: false, naturalLanguageInterpretationRequired: true, promptSummary: "A known count represents a stated percentage of a larger total; calculate the whole.", styleNotes: null },
  visuals: notApplicable("No supplied visual material is used in this Question."),
  mathematicalModel: notApplicable(),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: catalogValue({ relationshipType: "REVERSE", percentageValues: [80], multiplierValues: [0.8], periods: null, originalValueKnown: false, finalValueKnown: true, reverseCalculationRequired: true }, [evidence]), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: notApplicable(), statistics: notApplicable(), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },
  family: { familyId: "NUM_REVERSE_PERCENTAGE_TOTAL_FROM_PART", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["known part", "known percentage", "recover whole"], surfaceStyleIds: ["SHORT_CONTEXT", "REVERSE_PERCENTAGE"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "CONTEXTUAL", proseAmount: "MEDIUM", visualAmount: "NONE", layoutComplexity: "LOW", informationOrderCanVarySafely: true, visualPlacementCanVarySafely: true },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["NUM_REVERSE_PERCENTAGE_TOTAL_FROM_PART"], invariantMathematics: ["reverse-percentage whole-from-part structure"], variableParameters: ["percentage", "known part", "context object"], parameterConstraints: ["answer remains non-calculator friendly", "whole is contextually sensible"], safeContextVariations: ["attendance", "sales", "capacity", "survey totals"], safeRepresentationVariations: [], unsafeVariations: ["wording that makes the given amount the whole rather than the part"], difficultyControls: ["percentage denominator complexity", "magnitude of known amount"], requiredVisualCapabilities: [], requiredValidationChecks: ["mark total and part structure remain valid", "generated values satisfy parameter constraints", "answer remains non-calculator friendly", "instance is non-degenerate"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(false),
} satisfies QuestionCatalogEntry;
