import type { QuestionCatalogEntry } from "../../QuestionCatalogTypes";
import { catalogValue, notApplicable, qpEvidence, questionReviewInProgress, sourceIsolation, visualOriginality, visualValidation } from "../../QuestionCatalogHelpers";

const evidence = qpEvidence("6", 6);
const visualEvidence = qpEvidence("6", 6, "VISUAL");

export const N5_MATHS_2014_P1_Q6 = {
  // ============================================================================
  // SECTION 1 — IDENTITY
  // ============================================================================
  identity: { id: "N5_MATH_2014_P1_Q6", schemaVersion: "N5_CATALOG_V2", courseId: "N5_MATH", paperContextId: "N5_MATH_2014_P1_CONTEXT", year: 2014, paper: "P1", questionNumber: "6", answerCatalogId: "N5_MATH_2014_P1_Q6_MS" },
  sourceLayout: { sourcePages: [6, 7], printedPageLabels: ["Page 6", "Page 7"], continuesAcrossPages: true, answerSpace: { category: "LARGE", estimatedWritingLines: 16, responseSurfaceVisualIds: [], separateFinalAnswerAreaPresent: false, notes: "Question begins with a supplied graph and continues with both response parts on the following page." }, sourceEvidence: [evidence] },

  // ============================================================================
  // SECTION 3 — QUESTION STRUCTURE
  // ============================================================================
  structure: { structureType: "MULTIPART", totalMarks: 4, parts: [
    { id: "Q6_a", label: "a", marks: 3, primarySkillId: "stat-s02-linear-model", secondarySkillIds: [], conceptIds: ["stat-s2-1"], topic: "STAT", commandTypes: ["FIND"], responseTypes: ["EQUATION"], dependsOnPartIds: [], sharedInformationIds: ["Q6_INFO_A", "Q6_INFO_B"], visualElementIds: ["VIS_Q6"] },
    { id: "Q6_b", label: "b", marks: 1, primarySkillId: "stat-s02-linear-model", secondarySkillIds: [], conceptIds: ["stat-s2-1"], topic: "STAT", commandTypes: ["ESTIMATE"], responseTypes: ["NUMBER"], dependsOnPartIds: ["Q6_a"], sharedInformationIds: ["Q6_INFO_A", "Q6_INFO_B"], visualElementIds: ["VIS_Q6"] },
  ], dependencyType: "FOLLOW_ON", sharedStimulus: true, sharedVisuals: true, sharedGivenData: true, requiredResultProvided: false },
  curriculum: { primaryTopic: "STAT", primarySkillId: "stat-s02-linear-model", secondarySkillIds: [], primaryConceptId: "stat-s2-1", conceptIds: ["stat-s2-1"], paperSuitability: "P1", standardProfile: "C", thinkingProfile: "MIXED", crossSkillQuestion: false, skillMarkDistribution: { "stat-s02-linear-model": 4 }, conceptMarkDistribution: { "stat-s2-1": 4 } },
  task: { commandTypes: ["FIND", "ESTIMATE"], responseTypes: ["MIXED"], responseCount: 2, explicitMethodCue: false, methodRestricted: false, workingRequestedInPrompt: true, justificationRequested: false, contextualConclusionRequested: false, visualResponseRequired: false },

  // ============================================================================
  // SECTION 6 — MATHEMATICAL STRUCTURE
  // ============================================================================
  mathematics: { primaryGoal: "Construct a linear model from two labelled points on a best-fit line, then use it for extrapolation.", subgoals: [
    { id: "Q6_S1", summary: "Determine the gradient from the two supplied points.", dependsOnSubgoalIds: [] },
    { id: "Q6_S2", summary: "Determine the intercept and form the line equation.", dependsOnSubgoalIds: ["Q6_S1"] },
    { id: "Q6_S3", summary: "Substitute a new fat value into the model to estimate calories.", dependsOnSubgoalIds: ["Q6_S2"] },
  ], operationTypes: ["SUBTRACT", "DIVIDE", "MODEL", "SUBSTITUTE", "EVALUATE"], requiredFormulaIds: [], requiredTheoremIds: [], stageCount: 3, intermediateQuantityTypes: ["gradient", "intercept"], methodSelectionRequired: false, solutionCountExpected: 2, validitySelectionRequired: false, representationTransitions: [{ from: "graph and labelled points", to: "linear equation", purpose: "form a mathematical model" }, { from: "linear equation", to: "contextual estimate", purpose: "use the model for a new input" }] },
  information: [
    { id: "Q6_INFO_A", informationType: "coordinate pair", normalisedContent: "point A corresponds to F=5 and C=200", value: "(5,200)", unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q6", usedByPartIds: ["Q6_a", "Q6_b"] },
    { id: "Q6_INFO_B", informationType: "coordinate pair", normalisedContent: "point B corresponds to F=25 and C=500", value: "(25,500)", unit: null, source: "TEXT", explicitness: "EXPLICIT", role: "GIVEN_VALUE", visualElementId: "VIS_Q6", usedByPartIds: ["Q6_a", "Q6_b"] },
    { id: "Q6_INFO_TARGET", informationType: "new input", normalisedContent: "new item has F=40", value: 40, unit: "g", source: "TEXT", explicitness: "EXPLICIT", role: "TARGET", visualElementId: null, usedByPartIds: ["Q6_b"] },
  ],
  reasoning: { reasoningTypes: ["METHOD_SELECTION", "MULTI_STAGE", "REPRESENTATION_TRANSLATION", "CONTEXT_INTERPRETATION"], difficulty: { overallDifficulty: "MEDIUM", methodSelectionLoad: "MEDIUM", arithmeticLoad: "MEDIUM", algebraicLoad: "MEDIUM", representationLoad: "MEDIUM", languageLoad: "MEDIUM", contextInterpretationLoad: "LOW", reasoningDepth: "MEDIUM", dependencyCount: 2, difficultyDrivers: ["forming gradient/intercept from contextual coordinates", "using a model for extrapolation"] } },
  numbers: { numberTypes: ["INTEGER"], nonCalculatorFriendly: true, exactAndApproximateMixed: false, magnitudeNotes: null },
  parameterDesign: { deliberatelyConstructedValues: true, exactResultDesigned: true, roundingDesigned: false, factorisableDesigned: false, perfectSquareDesigned: false, pythagoreanTripleUsed: false, niceRatioUsed: true, validSolutionCountDesigned: null, parameterConstraints: ["labelled points have distinct input values", "gradient and intercept remain manageable without calculator", "new input preserves meaningful model use"], safeVariationAxes: ["point coordinates", "new input", "surface context"], invariantRelationships: ["two labelled points determine the best-fit line", "part b uses the equation from part a"], degeneracyConditionsToAvoid: ["vertical line", "new input identical to a labelled point"] },
  constraints: { mathematicalDomainConstraints: [], contextValidityConstraints: [], calculatorModeConstraints: ["Non-calculator arithmetic must remain feasible."], methodConstraints: [], presentationConstraints: [] },
  answerSpecification: { answerForm: "MIXED", simplestFormRequired: false, rationalDenominatorRequired: false, positivePowersRequired: false, scientificNotationRequired: false, precisionType: "NONE", precisionValue: null, units: { dimension: null, unitSymbol: null, conversionRequired: false, unitsExplicitlyRequested: false }, multipleAnswersRequired: 2, domainRestriction: null, contextualWordsRequired: false, coordinateOrderRelevant: false, bracketsRelevant: false, visualAnswerRequired: false },
  context: { contextualised: true, contextDomain: "food nutrition", contextRole: "MATHEMATICALLY_RELEVANT", namedPeoplePresent: false, currencyPresent: false, realWorldUnitsPresent: true, realismConstrainsAnswer: false, contextObjects: ["sandwiches"], contextCanBeSafelyReplaced: true },
  language: { informationDensity: "MEDIUM", scaffoldingLevel: "MEDIUM", bulletStructureUsed: false, naturalLanguageInterpretationRequired: true, promptSummary: "Use two labelled points on a contextual best-fit line to form a linear equation and estimate an output for a new input.", styleNotes: "The mathematical coordinates are repeated in text, so the graph supports context and representation but is not the sole source of the two key values." },

  // ============================================================================
  // SECTION 12 — VISUAL EVIDENCE
  // ============================================================================
  visuals: catalogValue({ elements: [{
    id: "VIS_Q6", sourceOrder: 1, visualType: "SCATTERGRAPH", roles: ["STRUCTURAL_MODEL", "CONTEXT_MODEL", "SUPPORTIVE"], dependency: "REDUNDANT_WITH_TEXT", candidateInteraction: "READ_ONLY", textRelationship: "PARTLY_DUPLICATED",
    scale: { mode: "SCHEMATIC", measurementFromDrawingPermitted: false, proportionalAppearanceDesirable: true, exactGeometryRequiredForRenderer: false, notes: "The labelled coordinates are stated in text and should not be inferred by measuring the drawing." },
    orientation: { verticalDirectionMeaningful: true, horizontalDirectionMeaningful: true, northReferenceMeaningful: false, groundReferenceMeaningful: false, startPositionMeaningful: false, rotationDirectionMeaningful: false, viewpointMeaningful: false, mirroringSafe: false, rotationSafe: false },
    labels: [{ entityId: "Q6_X", role: "AXIS", normalisedValue: "F: fat (g)", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }, { entityId: "Q6_Y", role: "AXIS", normalisedValue: "C: calories", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }, { entityId: "Q6_A", role: "POINT_NAME", normalisedValue: "A", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }, { entityId: "Q6_B", role: "POINT_NAME", normalisedValue: "B", placementMathematicallyConstrained: true, collisionPriority: "HIGH" }],
    semanticModel: { entities: [
      { id: "Q6_X", entityType: "AXIS", semanticName: "fat axis", printedLabel: "F", numericValue: null, symbolicValue: "F", unit: "g", mathematicallyEssential: false, orientationMeaningful: true, candidateEditable: false, attributes: {} },
      { id: "Q6_Y", entityType: "AXIS", semanticName: "calorie axis", printedLabel: "C", numericValue: null, symbolicValue: "C", unit: null, mathematicallyEssential: false, orientationMeaningful: true, candidateEditable: false, attributes: {} },
      { id: "Q6_A", entityType: "POINT", semanticName: "point A", printedLabel: "A", numericValue: null, symbolicValue: "(5,200)", unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: { F: 5, C: 200 } },
      { id: "Q6_B", entityType: "POINT", semanticName: "point B", printedLabel: "B", numericValue: null, symbolicValue: "(25,500)", unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: { F: 25, C: 500 } },
      { id: "Q6_LINE", entityType: "LINE", semanticName: "line of best fit", printedLabel: null, numericValue: null, symbolicValue: null, unit: null, mathematicallyEssential: true, orientationMeaningful: false, candidateEditable: false, attributes: {} },
    ], relations: [{ id: "Q6_R1", relationType: "PART_OF", fromEntityIds: ["Q6_A", "Q6_B"], toEntityIds: ["Q6_LINE"], normalisedMeaning: "A and B lie on the supplied best-fit line", essentialToSolution: true, sourceEvidence: [visualEvidence] }], facts: [] },
    layout: { sourcePageNumber: 6, sourcePagePosition: "MIDDLE", sourceRelativeWidth: "MEDIUM", preferredGeneratedAspectRatio: "4:3", minimumReadableWidthMm: null, minimumReadableHeightMm: null, allowInlinePlacement: false, allowFullWidthPlacement: true, labelCollisionSensitive: true },
    specialisedProfiles: { geometry: notApplicable(), circle: notApplicable(), graph: catalogValue({ graphFamily: "STRAIGHT_LINE", xAxis: { variable: "F", label: "Fat", unit: "g", numericScaleShown: false, tickInterval: null, minimumShown: 0, maximumShown: null }, yAxis: { variable: "C", label: "Calories", unit: null, numericScaleShown: false, tickInterval: null, minimumShown: 0, maximumShown: null }, originShown: true, gridShown: false, rootsRelevant: false, turningPointsRelevant: false, asymptotesRelevant: false, symmetryRelevant: false, labelledPointIds: ["Q6_A", "Q6_B"], referenceLinesPresent: false, candidateMustReadValues: false, candidateMustProduceGraph: false, accuracyExpectation: "SCHEMATIC" }, [visualEvidence]), scatter: catalogValue({ xVariable: "F", yVariable: "C", dataPointCount: null, lineOfBestFitPresent: true, candidateDrawsBestFitLine: false, correlationInterpretationRequired: false, interpolationRequired: false, extrapolationRequired: true, highlightedObservationIds: ["Q6_A", "Q6_B"] }, [visualEvidence]), table: notApplicable(), vector: notApplicable(), bearing: notApplicable(), solid3D: notApplicable(), mechanism: notApplicable(), contextImage: notApplicable(), responseSurface: notApplicable() },
    generation: { readiness: "PARTIAL", strategy: "PROCEDURAL_GRAPH", rendererFamilyId: "SCATTER_BEST_FIT", allowedMediaAssetIds: [], requiredAssetTags: [], semanticInvariants: ["axes represent the two contextual variables", "A and B lie on the best-fit line", "positive association is shown"], safeVariationAxes: ["non-essential scatter points", "line styling", "graph size"], unsafeVariations: ["move A or B off the line without updating the mathematics"], permittedOrientationChanges: [], permittedStyleChanges: ["line weight", "label spacing", "overall size"], requiredRendererCapabilities: ["axes", "scatter points", "best-fit line", "point labels"], requiredValidationChecks: ["semantic entities and relations resolve", "labels agree with parameters", "print remains readable"], provenance: "GENERATION_ANALYSIS" },
    originality: visualOriginality(), validation: visualValidation(true, true), sourceEvidence: [visualEvidence], confidence: "HIGH",
  }], visualCount: 1, relationships: [], containsEssentialVisualData: false, containsContextImage: false, containsProcedurallyReproducibleDiagram: true, containsResponseSurface: false, generationRequiresMultipleVisuals: false }, [visualEvidence]),

  // ============================================================================
  // SECTION 13 — MODEL / SPECIALISED PROFILES
  // ============================================================================
  mathematicalModel: catalogValue({ modelFamily: "LINEAR", normalisedModel: "C=mF+c", independentVariable: "F", dependentVariable: "C", physicalOrContextDomain: "fat content and calories", modelProvidedToCandidate: false, candidateMustConstructModel: true, candidateMustInterpretModel: true, solveForIndependentVariable: false, targetDependentValueProvided: false, modelParameters: {} }, [evidence]),
  specialisedProfiles: { arithmetic: notApplicable(), percentage: notApplicable(), powersSurdsScientific: notApplicable(), algebra: notApplicable(), equationsInequalities: notApplicable(), functionsGraphs: catalogValue({ functionFamily: "LINEAR", functionNotationUsed: false, transformationParametersPresent: false, rootsRelevant: false, turningPointsRelevant: false, graphInterpretationRequired: true }, [evidence]), statistics: catalogValue({ rawDataProvided: false, summaryStatisticsProvided: false, sampleSize: null, statisticsRequired: ["gradient", "linear model", "model estimate"], comparisonRequired: false, interpretationRequired: false }, [evidence]), geometryMeasureCircleSimilarity: notApplicable(), trigonometry: notApplicable(), bearings: notApplicable(), coordinateGeometry: notApplicable(), vectors: notApplicable() },

  // ============================================================================
  // SECTION 15 — FAMILY / GENERATION / REVIEW
  // ============================================================================
  family: { familyId: "STAT_LINEAR_MODEL_FROM_BEST_FIT_GRAPH", subFamilyId: null, familyConfidence: "HIGH", structuralSignature: ["best-fit line", "two labelled points", "linear equation", "new-input estimate"], surfaceStyleIds: ["CONTEXTUAL_SCATTERGRAPH", "FOLLOW_ON_ESTIMATE"], relatedFamilyIds: [] },
  surface: { abstractOrContextual: "CONTEXTUAL", proseAmount: "HIGH", visualAmount: "HIGH", layoutComplexity: "HIGH", informationOrderCanVarySafely: false, visualPlacementCanVarySafely: false },
  generation: { readiness: "PARTIAL", linkedGeneratorFamilyIds: ["STAT_LINEAR_MODEL_FROM_BEST_FIT_GRAPH"], invariantMathematics: ["linear-model construction followed by model use"], variableParameters: ["point coordinates", "context labels", "new input"], parameterConstraints: ["two points define a manageable non-vertical line", "new input produces a sensible contextual output"], safeContextVariations: ["other contexts involving two associated numerical variables"], safeRepresentationVariations: ["graph styling and scatter noise may vary while labelled-point semantics remain"], unsafeVariations: ["graph contradicts labelled coordinates or equation"], difficultyControls: ["gradient arithmetic", "intercept arithmetic", "distance of extrapolation"], requiredVisualCapabilities: ["scatter/best-fit graph renderer", "axis and point labels"], requiredValidationChecks: ["mark total and part structure remain valid", "generated values satisfy parameter constraints", "required answer form remains attainable without calculator", "generated instance is non-degenerate"], provenance: "GENERATION_ANALYSIS" },
  sourceIsolation: sourceIsolation(),
  review: questionReviewInProgress(true),
} satisfies QuestionCatalogEntry;
